### ISSUE TITLE
set ip to internal address when connected to home router

### ISSUE THREAD

**Issue by mrmoth** [ubergeek42/weechat-android#101]
Something like how transdroid does it:  http://www.transdroid.org/download/using-deluge-on-ubuntu/ (see the section titled, "Local Wifi Network Access")
Would save me the effort of changing the ip address everytime I want to connect while at home!

**Comment by jiggie42** [comment]
recommended to close (duplicate?)  This is better described in referenced issue.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
