### ISSUE TITLE
Feature request: Use the `ping` verb to keep the connection alive.

### ISSUE THREAD

**Issue by skyhighwings** [ubergeek42/weechat-android#103]
Currently, the app will randomly disconnect after a period of time I have not been able to determine any rhyme nor reason to. This disconnection is invisible to the user until they attempt to send a message, at which point they will realize that the disconnection has occurred because the message will never appear. Reconnecting solves the issue.

References:
[`ping` verb usage](http://www.weechat.org/files/doc/devel/weechat_relay_protocol.en.html#command_ping)

**Comment by mhoran** [comment]
Ping functionality has been merged. The latest dev build will include it, and we'll get a Play store release out shortly.
