### ISSUE TITLE
WebSocket Disconnect/Reconnect Fails

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#114]
The library we are using for WebSocket support apparently doesn't deal well with disconnects at all(it never times out so the app never knows we lost the connection).

Upstream issue here: https://github.com/TooTallNate/Java-WebSocket/issues/180

**Comment by jpatel531** [comment]
+1

**Comment by jiggie42** [comment]
Do we still use that library? If so it appears to have been fixed since 2017
