### ISSUE TITLE
Merged buffer support

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#12]
At the very least for the status/server buffers.  A few possibilities:
- An item representing the merged buffers, that when clicked shows the individual buffers.  In this mode the lines wouldn't be merged together.
- A psuedo buffer that collects lines for all buffers, but tags them accordingly.  I think this might actually be the way to go(merge according to buffer number).

I like the second method best, and creating a psuedobuffer for the merged contents seems relatively simple.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.

**Comment by bqv** [comment]
What happens currently...?
