### ISSUE TITLE
More detail in notifications about hot message/highlights

### ISSUE THREAD

**Issue by azizLIGHT** [ubergeek42/weechat-android#129]
It would be nice if it said more than the nick and text. Maybe a buffer number? Maybe a buffer name 

Something like what highmon.pl does:
72:freenode#weechat <singalaut> azizLIGHT: read_marker

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
