### ISSUE TITLE
Duplicate buffer numbers after moving buffer with /buffer move #

### ISSUE THREAD

**Issue by azizLIGHT** [ubergeek42/weechat-android#130]
This is unrelated to merged buffers AFAIK. 

When a buffer #weechat is moved using /buffer move 4,  and assuming ##linux is already at buffer 4, Weechat-Android considers both buffers to be at 4, as seen in the buffer list. 

Weechat itself adjusts appropriately: it moves ##linux to 5 and places #weechat to 4.

I have "settings -  connection settThe s -  only sync open buffers" turned off

The issue is compounded when additional /buffer move commands are issued. Weechat-Android moves the buffers to correct numbers but neglects updating the position of all other buffers. 

The issue is fixed when I quit and restart Weechat-Android.

**Comment by oakkitten** [comment]
this should be fixed now
