### ISSUE TITLE
Make about page data selectable and actionable 

### ISSUE THREAD

**Issue by azizLIGHT** [ubergeek42/weechat-android#131]
The about page has a email address listed for contacting about bugs or feature requests. There is no way to select this email address: long press does nothing. There is no way to act on this email address: regular click does nothing. There is no way to use this email address besides writing it manually in your email client.

There is also a build number listed in the about page. There is also no way to copy this information. You would have to type this manually, if you want to refer to this build is, and it's very easy to misspell this piece of information.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
