### ISSUE TITLE
Enter button on keyboard to send message

### ISSUE THREAD

**Issue by madyoda** [ubergeek42/weechat-android#152]
Hi.

Is it possible to use the enter button on the keyboard to send a message? Currently it just brings up the emoji section of the keyboard.

**Comment by mhoran** [comment]
Fixed in a3dc0a2.

**Comment by madyoda** [comment]
Thank you. :)

**Comment by bqv** [comment]
Is there some hope of this being an option? Not being able at all to input an actual return in any way is inconvenient for me

cc @oakkitten

**Comment by oakkitten** [comment]
@bqv i created #524 but don't expect this to be done soon unless you want to do it yourself :p
