### ISSUE TITLE
Window/buffer close behavior

### ISSUE THREAD

**Issue by kh4** [ubergeek42/weechat-android#153]
I noticed some odd behavior with closing the buffer.
- Selecting the 'Close' on the app doesn't really close the buffer it merely hides the Tab as the Server side buffer remains open. I think this should be renamed to hide.
- doing '/close' on the app it seems to close the server buffer and also remove the tab which is more like desired behavior. I would add this in the menu as 'Close'.

It would be useful to be able to close buffers from the buffer list directly e.g. by swiping them off screen.

**Comment by vext01** [comment]
+1 on @kh4's original suggestion. "close" didn't do what I expected, and typing '/buffer close' is too long for a mobile app.

I think separate "hide" and "close" buttons should suffice.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
