### ISSUE TITLE
Toggle timestamps easier

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#158]
From a google play review. Not sure if there is a good way to do this. Maybe double tap on a timestamp to hide? But then how to bring them back?

> If we only could show/hide timestamps without leaving conversation window, it would make this program a perfect

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
