### ISSUE TITLE
Respect weechat notification levels

### ISSUE THREAD

**Issue by Isgar** [ubergeek42/weechat-android#163]
I get hot list notifications where i set '/buffer notify none'.
This should not be the case.

**Comment by unhammer** [comment]
I also get notifications for things that are filtered out. For example, there's a commit bot in #apertium that says `apertium: unhammer: * 63198: Informative commit message`; I filter out those messages on the server, and they don't show up in the actual channel in the weechat app, but I still see them in the notification drop-down, and they make my phone LED blink. The whole reason for filtering them on the server was that my phone LED was blinking too much :)

**Comment by oakkitten** [comment]
please test http://weechat-android.ubergeek42.com.s3.amazonaws.com/index-woah.html

the funny part is, weechat's default beep trigger respects visibility but doesn't respect notify levels

**Comment by unhammer** [comment]
I can't get the v0.10-dev to connect; I'm using Weechat SSL just like with the standard client, got the same connection info (host,port,pass) as far as I can tell, but it never catches the balloon. 
    
server shows something like

    09:29:00        weechat     | relay: disconnected from client 60/ssl.irc/1.2.3.4
    09:29:00        weechat     | relay: new client on port 9001: 61/ssl.irc/1.2.3.4
    09:29:35        weechat =!= | relay: reading data on socket for client 61/ssl.irc/1.2.3.4: error 0 (connection closed by peer)
    09:29:35        weechat     | relay: disconnected from client 61/ssl.irc/1.2.3.4
    09:29:35        weechat     | relay: new client on port 9001: 62/ssl.irc/1.2.3.4

etc.

**Comment by unhammer** [comment]
So this respects my filter, but it seems to work a bit too well … I got one notification light for a mention in a channel, but then no notifications for PM's, and now when I try again I don't even get notification lights for channel mentions.

**Comment by oakkitten** [comment]
amended the commit, should be fine now (5b1db88c54468a5c7ce8437fd235ea362c510368)

forgot that weechat doesn't send us the notify level for new buffers, and the default one was wrong. defaults to 3 (all) now. will have to do until weechat decides to start sending us them notify levels

**Comment by unhammer** [comment]
will http://weechat-android.ubergeek42.com.s3.amazonaws.com/index-woah.html get the update?

**Comment by oakkitten** [comment]
the page says 5b1db88 for me

**Comment by unhammer** [comment]
oh sorry, I saw a cache I suppose

**Comment by oakkitten** [comment]
:tada:

**Comment by BlacklightShining** [comment]
Is there an open `weechat` issue for this? Quick search didn't find one.

**Comment by oakkitten** [comment]
opened one yesterday https://github.com/weechat/weechat/issues/593
