### ISSUE TITLE
option request: light theme

### ISSUE THREAD

**Issue by ghost** [ubergeek42/weechat-android#165]
an option to have a light theme would be nice, people would probably stop looking at my phone when i have the app open and call me 'hacker'...

**Comment by piesu** [comment]
Agree. While I like this dark theme, on eink screen (Onyx T68) it basically is a black text on black background. I could help debug if this would be needed.

**Comment by charafau** [comment]
That might be easy to implement, but I'm not sure what to do with nick colors. Will check it and post the screenshot later today.

**Comment by flocke** [comment]
I would love a light theme as well. Any news on this?

**Comment by oakkitten** [comment]
this has been implemented
