### ISSUE TITLE
Make the buffer list more like weechat's hotlist

### ISSUE THREAD

**Issue by BlacklightShining** [ubergeek42/weechat-android#172]
Not sure if this is possible, but it'd be nice if the relay's buffer list was ordered like it is in `weechat` proper (according to `weechat.look.hotlist_sort`), displayed new-message counts the same way (according to `weechat.look.hotlist_count_max`, `weechat.look.hotlist_count_min_msg`, etc.), and maybe even used the same coloration for the badges with the counts on them.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
