### ISSUE TITLE
Try multiple DNS records when connecting

### ISSUE THREAD

**Issue by mjholtkamp** [ubergeek42/weechat-android#175]
Hi!

First off, I want to say that weechat-android is a great product and I'm happily using it for a while now. The new version was a huge improvement as well, the interface looks really slick now.

Due to problems with my network setup at home (NAT, broken modem, IPv4, you probably know what the problem is), I need to connect to my external IP address when not at home and to my internal IP address when I'm at home. Alternatively, if I have IPv6 connectivity I can just connect to the IPv6 address from anywhere, except that at home IPv6 is flakey on my phone due to a combination of Android versions and Modem firmwares (a problem not related to weechat-android at all).

My problem would be fixed with implementing multiple relays, as in: #160 #83. But I think these are difficult to solve quickly. I have an alternative solution and I'm curious if you are interested in that one.

I have a separate hostname for my weechat client, resolving both to the external IPv4, as well as the internal IPv4 address (and also the IPv6 address). I noticed that the source code uses http://docs.oracle.com/javase/6/docs/api/java/net/InetSocketAddress.html#InetSocketAddress(java.lang.String,%20int) to resolve the hostname, but that just takes the IPv6 or any of the IPv4 records, whichever comes first I guess. It does not try all of them.

Would you consider changing the code so it tries all IP-addresses, connecting to the first one that works (and retrying other records until it finds one)? I think this can be done with InetAddress.getAllByName (http://www.java2s.com/Code/JavaAPI/java.net/InetAddressgetAllByNameStringname.htm), but it requires more code to loop through all of them + more error handling.

Please let me know if you would consider making this.

Thanks in advance!

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
