### ISSUE TITLE
Connection preferences not accepted

### ISSUE THREAD

**Issue by nijotz** [ubergeek42/weechat-android#176]
I upgraded to WA v0.9 and could no longer connect.   I had configured the previous version (not sure which one) to use SSH tunnel for the connection settings.  When trying to connect, it says "Click to edit your preferences and connect".  I checked my connection settings and they were fine.  So, I went into settings and cleared data/cache for WA and tried again.  It still is saying I need to configure my connection settings. I'm using SSH password, no private key file set.

**Comment by mhoran** [comment]
There is now a notification on incorrect password. However, this should be extended to pop up the configuration notification so that it is more clear.

**Comment by mhoran** [comment]
I've opened #188 for the crash issue.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
