### ISSUE TITLE
Dark blue buffer text is incredibly hard to read on a dark background.

### ISSUE THREAD

**Issue by paritybit** [ubergeek42/weechat-android#181]
Each user has a different text color in the buffer. Sometimes a user has a dark blue color and with the dark background of the app it makes it nearly impossible to read. Dark text colors shouldn't show up on dark backgrounds.

**Comment by oakkitten** [comment]
it's funny that this issue comes a day after #180. until it is merged, you can use a workaround mentioned there.

**Comment by paritybit** [comment]
Oh my bad. I searched for any mention of "blue" in the previous issues. Somehow I missed that. I'll close this issue so we don't have duplicates.
