### ISSUE TITLE
Disable notification vibration

### ISSUE THREAD

**Issue by mikolino** [ubergeek42/weechat-android#182]
I'd like to be able to have truly silent notifications. We can already set sound to "None", I think an option to also disable vibration would be nice.

**Comment by oakkitten** [comment]
I'm not getting any vibration at all, no matter the notification sound :confused:

**Comment by mikolino** [comment]
I'm on Moto X kitkat 4.4.4, maybe it's a Motorola thing to change sound to vibration? Although Gmail is set to have a sound and it doesn't vibrate when on vibrate...


But if it's just me you can close the issue I guess, I "fixed" my issue by using App Ops to remove vibration permission from weechat!

Thanks for your reply

**Comment by clemux** [comment]
I added an option fixing that in my PR. If mikolino or someone else wants to try, my APK is available here: http://www.mux.me/weechat/weechat-android-debug.apk (though you really should build it yourself, and not trust me.)

**Comment by sekh** [comment]
Seems to work for me. (Nexus 4, Android 5.0.1)

**Comment by jdhore** [comment]
whoops, i didn't see this. I implemented this in my PR, #198 which was merged. Sorry. :(

I've also implemented full silencing (sound, vibrate, even display, all off) of hot message notifications.
