### ISSUE TITLE
Add an option to adjust the scrollback size

### ISSUE THREAD

**Issue by BlacklightShining** [ubergeek42/weechat-android#184]
In especially active channels, 200 lines might be only a few hours. It'd be useful to be able to either request more than 200 lines when opening buffers, or keep more than 200 lines locally.

**Comment by agn4965** [comment]
Downloading more lines as you're scrolling up would be a welcome addition.

**Comment by whompy** [comment]
+1 on the request for increased scrollback akin to the web client.

**Comment by epitron** [comment]
+10 from me. I'm spending all my karma on this feature. :)

**Comment by dummys** [comment]
Sorry for duplicate. I'm spending all my karma too :D:D

**Comment by oakkitten** [comment]
this thing is useful, long overdue and probably easy to implement, but somehow no one wants to work on implementing it for whatever reason :/

i'm planning on doing it when i've fixed some other things but that might be not very soon

**Comment by bqv** [comment]
+1

Someone, please do this

**Comment by oakkitten** [comment]
this has been added in dcb0938b06192d46ca5a56a30b5f82e353ed3c0d

**Comment by bqv** [comment]
Wow, throwback wednesday..
