### ISSUE TITLE
Allow closing buffers without focusing on them

### ISSUE THREAD

**Issue by ghost** [ubergeek42/weechat-android#185]
I like reading backlog, but if it becomes too much I want to bail the buffer on WA so I don't accidentally lose my unread marker, but I have to switch to it just to close the buffer.

Perhaps long pressing in the buffer in the side list or swiping it to the right again could just close it without claiming I've read everything.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
