### ISSUE TITLE
Mention-Option in Buffer ContextMenu

### ISSUE THREAD

**Issue by mweinelt** [ubergeek42/weechat-android#189]
Hi!

It would be great if the Buffer Contextmenu could offer the option to mention the user that wrote the currently selected message, prefixing the current message with "nick:" (nickname, followed by a colon).

This is great when interacting with bitlbee, which needs this to address other users.

**Comment by mhoran** [comment]
Hey @mweinelt! There is a tab button that can be enabled in the preferences. This should allow "mentions", or at least does so on IRC. A context option could be useful, we'll just have to figure out how to work it into the UI.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
