### ISSUE TITLE
Unicode buffer names aren't displayed correctly

### ISSUE THREAD

**Issue by BlacklightShining** [ubergeek42/weechat-android#190]
I'm in a channel called `#☃`, but it shows up as just `#` in the buffer list.

**Comment by mhoran** [comment]
I can't reproduce this myself. I'm not sure where the trouble could be, but with the latest dev build and Android 5.0.1 on the Nexus 5, this works fine.

**Comment by BlacklightShining** [comment]
Mmm, that might be it. Nexus 5, but I'm still on the stable Play Store release and Android 4.4.4.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
