### ISSUE TITLE
Connect option is ambiguous

### ISSUE THREAD

**Issue by JoelMon** [ubergeek42/weechat-android#192]
Hello,

The user interface does not guide new users to settings when Connect is clicked. 
## WA

Weechat Android v0.9
## Problem

When I click the three dots on the upper right a drop-down menu containing menu items: Connect, Settings, Close, About, and Quit appears.

When I click on Connect, the drop-down menu fades away but nothing else happens.
## Solution

When a new user clicks Connect and no remote server is configured, prompt the user to enter a server before connecting.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
