### ISSUE TITLE
New TLDs are not being linkified

### ISSUE THREAD

**Issue by zertap** [ubergeek42/weechat-android#193]
Links like http://nic.moe are not being detected by the Linkify class.
https://github.com/ubergeek42/weechat-android/blob/a49c6e88b0b3ce24559636bf25c9bee70cd77da3/weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/Buffer.java#L625

Apparently it has been fixed in android 5, but devices using older versions will not linkify these TLDs.
https://code.google.com/p/android/issues/detail?id=66032

**Comment by ubergeek42** [comment]
I don't think this is something I want to try fixing. No reason this app needs to know all the TLDs, and writing our own linkifier seems like overkill.

**Comment by gdude2002** [comment]
This is extremely annoying on a mobile device, honestly, especially when we can't simply extract the link from the message (which would be impractical for people like me that use overlay browsers such as link bubble). 

I'd imagine you could do this pretty easily with a basic regex anyway? What's overkill about that?

**Comment by Sheraf1** [comment]
You don't need to add each new TLD, just, if it starts with http(s):// .. make it clickable

**Comment by ubergeek42** [comment]
I guess my logic was that it's overkill because it's resolved in the latest android. But if there is demand(and there apparently is), I'll reopen this issue and maybe take a look at it.

**Comment by ubergeek42** [comment]
I think the regex is likely going to be slightly more complicated than that, but we may be able to get away with a simpler one and not care about being overly greedy. It gets complicated when you get unicode involved.

For reference, here's the patterns android is using to match web urls:
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/util/Patterns.java

We could probably just copy these and things would work.

Does anyone have a suggested regex we should use?

**Comment by gdude2002** [comment]
In python I'd probably do something like.. 

`[^\s]+://[^\s]+`

Would that be too greedy?

**Comment by gdude2002** [comment]
(Obviously that would match more than http/s, but ftp and others are often supported)
