### ISSUE TITLE
High battery usage (higher than the screen!)

### ISSUE THREAD

**Issue by epitron** [ubergeek42/weechat-android#194]
I've been building the master branch of weechat-android and running it on my phone for the last couple of months. For some reason, it uses a lot of battery when idling. 

My battery stats from today say: __33% Weechat__, 6% Screen, 5% Google Services, etc... and I didn't use weechat android at all today!

Is there an easy way to profile weechat's performance and power saving states?

**Comment by domenkozar** [comment]
+1, most battery used app is weechat

**Comment by epitron** [comment]
I haven't had this issue in a long time, so I guess it's fixed!
