### ISSUE TITLE
Error: length=805; index=805

### ISSUE THREAD

**Issue by thcipriani** [ubergeek42/weechat-android#200]
App seems to work fine if I open up iptables on my server, even using SSL seems to work fine, so weechat relay seems to be setup correctly.

If I try to use a known working ssh key ([rsync4android](http://android.kowalczuk.eu/rsync4android/) works fine using this key) to tunnel the SSH Connection, I get the rather cryptic message, "Error: length=805; index=805"

Willing to help troubleshoot the best I can with very limited Java knowledge (and frankly, limited android knowledge)—great app, really want to get it working!
## General Info
- Moto X (2nd Generation)
- Android 5.0.2
- Host port: 22
- Relay ports tried: 8001, 9001
- SSH host and relay host are the same
- Tried with weechat ssl and without
- SSH private key file: /storage/emulated/0/.ssh/android.key

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
