### ISSUE TITLE
add timestamp prefix alignment

### ISSUE THREAD

**Issue by shawnbon206** [ubergeek42/weechat-android#202]
Please consider adding timestamp alignment,  the text will wrap from the right side of the time stamp to the right side of the screen.

To me timestamp alignment is more readable than no alignment at all, and very condensed allowing largish fonts to be used on smaller screens.

**Comment by ubergeek42** [comment]
I'm not sure I follow. Can you provide a screenshot or something showing what is happening vs what you expect to happen?

**Comment by shawnbon206** [comment]
http://i.imgur.com/lbmAKCB.png

**Comment by mhoran** [comment]
Ah, so the text is aligned with the timestamp instead of the nick. I was not aware of this configuration.
