### ISSUE TITLE
[Feature Request] No Notifications when Status isn't Away

### ISSUE THREAD

**Issue by t3chguy** [ubergeek42/weechat-android#205]
How about a configuration option to only listen for notifications when you are marked as away - this would be extremely handy in conjunction with Auto_Away or Tmux_Away in WeeChat

**Comment by t3chguy** [comment]
For example - I use WeeChat within GNU Screen, when not using it or out or whatever I detach its screen session, screen_away.py picks up on this and marks me as /away, at this point weebullet.py kicks in and sends me notifications. This is the right behaviour but with W-A instead of pushbullet, that you only get notifications when you're not logged in on other devices, (screen_away also marks me as away/not away depending on whether or not there's relay clients connected)

Obviously some people would always want notifications but it makes sense to only get the notifications in the place you need them

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
