### ISSUE TITLE
last read line is always at last line

### ISSUE THREAD

**Issue by jspricke** [ubergeek42/weechat-android#206]
Since https://github.com/ubergeek42/weechat-android/commit/a17d36c71030e1ed6add80a3a44a0123018d1bc5 red the last read line is always at the bottom and it doesn't scroll back to the last read line.

**Comment by ubergeek42** [comment]
Hmm, this only seems to happen when you leave the app and go back to it. I'll try to take a look later and get this fixed.

**Comment by ubergeek42** [comment]
I think this is fixed with 840bcdc952e2122a0bf5e5a03064365a111a7f2e. Feel free to reopen if it still isn't what you expect(and detail what you expect should happen, or the cases where it doesn't work right).

**Comment by jspricke** [comment]
It seems to be better now, but sometimes it's still at the last line, although the unread counter seems to be right all the time. This happens reproducible when the app is first started, but sometimes in between as well. It seems almost like the value gets lost. Sorry for not giving clearer descriptions. Btw. I can't reopen, can you do it?
