### ISSUE TITLE
Crash when losing connection while connecting

### ISSUE THREAD

**Issue by Phyks** [ubergeek42/weechat-android#208]
Hi,

When connecting to a Weechat relay and internet connection is lost on the phone, the app will crash and restart.

**Comment by Phyks** [comment]
Not that this only happen when connecting for the first time. If signal is lost after first connection, the app reconnects when signal is back. I can still reproduce it with up to date F-droid builds.

**Comment by ubergeek42** [comment]
What connection method? plain? Ssl? Ssh tunnel?

**Comment by Phyks** [comment]
SSL

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
