### ISSUE TITLE
"Ghost" private messages / highlights

### ISSUE THREAD

**Issue by Phyks** [ubergeek42/weechat-android#209]
Hi,

It seems that this app is keeping track of which messages / buffers where read. However, when changing IP (I think, as it happens often when I move from 3G to wifi), it loses the buffers status.

Moreover, I often have "ghost" hilights or private messages. This means that if I have some private messages, read them, close the app, sometimes it will show up a non-zero unread count when restarted, even before having successfully connected to the weechat relay.

**Comment by oakkitten** [comment]
This is a drawback of how w-a synchronizes with weechat. We are relying on last_read_line data to determine if buffer has been read in weechat. But this information can be not present in certain circumstances. See weechat/weechat#180, weechat/weechat#185, weechat/weechat#517
