### ISSUE TITLE
App Crashes Upon Connecting

### ISSUE THREAD

**Issue by AKPWebDesign** [ubergeek42/weechat-android#212]
When I try to connect to my relay, the app crashes with the following stack trace:

```
java.lang.OutOfMemoryError: Failed to allocate a 1013478521 byte allocation with 14818168 free bytes and 170MB until OOM
    at com.ubergeek42.a.c.a (Unknown Source)
    at com.ubergeek42.a.a.d.run (Unknown Source)
    at java.lang.Thread.run (Thread.java:818)
```

I'm on a Nexus 5 running a CyanogenMod 12.1-20150629-NIGHTLY-hammerhead (Android 5.1.1). I can gladly provide more information if needed.

**Comment by ubergeek42** [comment]
Can you see if it's reproducible with the development version?

http://weechat-android.ubergeek42.com

It'll be a couple days before I get to my computer where I (hopefully) still have the proguard output that can help me figure out where that "unknown source" actually is.

**Comment by AKPWebDesign** [comment]
I just tried with the development version and got the same error. If it helps any, I've got the full logcat from the time of the error below, although I'm not sure it provides any more helpful information.

```
I/Timeline( 6320): Timeline: Activity_launch_request id:com.ubergeek42.WeechatAndroid.dev time:267096189
I/ActivityManager( 5634): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ubergeek42.WeechatAndroid.dev/com.ubergeek42.WeechatAndroid.WeechatActivity (has extras)} from uid 10134 on display 0
I/Keyboard.Facilitator( 6077): onFinishInput()
I/Timeline(13688): Timeline: Activity_idle id: android.os.BinderProxy@10a01a59 time:267096281
I/Timeline( 5634): Timeline: Activity_windows_visible id: ActivityRecord{1ebfb9f1 u0 com.ubergeek42.WeechatAndroid.dev/com.ubergeek42.WeechatAndroid.WeechatActivity t4708} time:267096840
V/WindowManager( 5634): Adding window Window{101d2d6a u0 PopupWindow:235f51c7} at 5 of 9 (after Window{18b07b99 u0 com.ubergeek42.WeechatAndroid.dev/com.ubergeek42.WeechatAndroid.WeechatActivity})
W/InputMethodManagerService( 5634): Window already focused, ignoring focus gainof: com.android.internal.view.IInputMethodClient$Stub$Proxy@3e58b636 attribute=null, token = android.os.BinderProxy@b1edce0
W/CronetSyncConnectionRcs( 6536): Upload content type not set.
I/art     (13688): Alloc sticky concurrent mark sweep GC freed 59949(2MB) AllocSpace objects, 8(125KB) LOS objects, 16% free, 21MB/25MB, paused 1.691ms total 51.881ms
I/art     (13688): Alloc partial concurrent mark sweep GC freed 1444(117KB) AllocSpace objects, 1(1181KB) LOS objects, 39% free, 20MB/33MB, paused 1.657ms total 28.892ms
I/art     (13688): Alloc concurrent mark sweep GC freed 15(12KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 20MB/33MB, paused 1.274ms total 25.807ms
I/art     (13688): Forcing collection of SoftReferences for 966MB allocation
I/art     (13688): Alloc concurrent mark sweep GC freed 11(344B) AllocSpace objects, 0(0B) LOS objects, 39% free, 20MB/33MB, paused 1.379ms total 23.850ms
E/art     (13688): Throwing OutOfMemoryError "Failed to allocate a 1013478521 byte allocation with 14191140 free bytes and 171MB until OOM"
I/art     (13688): Alloc partial concurrent mark sweep GC freed 6(192B) AllocSpace objects, 0(0B) LOS objects, 39% free, 20MB/33MB, paused 920us total 8.811ms
I/art     (13688): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 39% free, 20MB/33MB, paused 944us total 16.305ms
I/art     (13688): Forcing collection of SoftReferences for 966MB allocation
I/art     (13688): Alloc concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 39% free, 20MB/33MB, paused 940us total 15.469ms
E/art     (13688): Throwing OutOfMemoryError "Failed to allocate a 1013478521 byte allocation with 14191140 free bytes and 171MB until OOM"
E/AndroidRuntime(13688): FATAL EXCEPTION: Thread-1014
E/AndroidRuntime(13688): Process: com.ubergeek42.WeechatAndroid.dev, PID: 13688
E/AndroidRuntime(13688): java.lang.OutOfMemoryError: Failed to allocate a 1013478521 byte allocation with 14191140 free bytes and 171MB until OOM
E/AndroidRuntime(13688):        at com.ubergeek42.a.c.a(Unknown Source)
E/AndroidRuntime(13688):        at com.ubergeek42.a.a.d.run(Unknown Source)
E/AndroidRuntime(13688):        at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 5634):   Force finishing activity 1 com.ubergeek42.WeechatAndroid.dev/com.ubergeek42.WeechatAndroid.WeechatActivity
D/OpenGLRenderer( 5634): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/Atlas   ( 5634): Validating map...
I/Adreno-EGL( 5634): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/14/15, ab0075f, Id3510ff6dc
I/OpenGLRenderer( 5634): Initialized EGL, version 1.4
D/OpenGLRenderer( 5634): Enabling debug mode 0
I/Timeline( 6320): Timeline: Activity_idle id: android.os.BinderProxy@1a6dcb53 time:267109424
I/Timeline( 5634): Timeline: Activity_windows_visible id: ActivityRecord{a21aa74 u0 com.teslacoilsw.launcher/.NovaLauncher t4706} time:267109705
W/ResourceType( 5856): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 5856): Failure retrieving resources for com.ubergeek42.WeechatAndroid.dev: Resource ID #0x0
W/OpenGLRenderer( 6320): Incorrectly called buildLayer on View: aD, destroying layer...
W/OpenGLRenderer( 6320): Incorrectly called buildLayer on View: aD, destroying layer...
```

**Comment by ubergeek42** [comment]
Thanks for testing. I hate proguard, can't see the actual source of the issue :/

Are you in any particularly large channels(or in a large number of channels)?

**Comment by AKPWebDesign** [comment]
I'm in 28 channels across 3 networks. None of them are very large that I can think of, but one thing to note is that I joined the #twitch channel on Twitch.TV during the height of E3 (I mention that because the log for that channel on that day was about 16 MB large, opposed to the normal 200 KB per channel I'm used to). I'm not in that channel anymore, though.

I can try to build the app on my machine and run it that way, although I'm not very keen to the process of building apps. I have Android Studio on my machine, though, so I can try.

**Comment by ubergeek42** [comment]
This app should build pretty easily, and if you could get a trace from that it'd be the most useful. It'd be a couple days before I could build you a debug build myself(away from my development machine for a few days)

Large scrollback shouldn't be an issue(we only ask weechat for the last 200 lines). Odds are we're doing something really dumb in the code.

**Comment by AKPWebDesign** [comment]
Alright, I'll build it and let you know as soon as I can.

**Comment by ubergeek42** [comment]
Great! Thanks for reporting and hopefully we can get the app fixed for you!

**Comment by AKPWebDesign** [comment]
Alright, I ran the app on my phone, and here's the deobfuscated error:

```
07-06 16:03:58.410  21746-22950/? E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-1203
    Process: com.ubergeek42.WeechatAndroid.debug, PID: 21746
    java.lang.OutOfMemoryError: Failed to allocate a 1013478521 byte allocation with 13763796 free bytes and 172MB until OOM
            at com.ubergeek42.weechat.Helper.copyOfRange(Helper.java:32)
            at com.ubergeek42.weechat.relay.RelayConnection$2.run(RelayConnection.java:178)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by ubergeek42** [comment]
What version of weechat?
Which connection method?

This is a rather interesting bug. Can you also include the output of `/relay raw` on the weechat side of things when you attempt to connect?(Make sure to obfuscate your relay password)

**Comment by ubergeek42** [comment]
Also, I note that 1013478521(the size it's trying to allocate), is 0x3C687479 in hex, which if you break into bytes and look at as ascii it's `<hty`. Might be a coincidence, or it might be that whatever you're connecting to looks sorta like a web server.(That's a difference of 12 bytes to get `<htm` instead, and I could believe there is 12bytes of overhead for whatever reason during it's allocation).

**Comment by AKPWebDesign** [comment]
It turns out that your idea about the number looking like a web server was spot on. Apparently some software I installed took over that port the last time I restarted my server. Sorry for wasting your time with my stupidity, and thanks so much for helping me figure it out. :P

**Comment by t3chguy** [comment]
Not completely pointless though, its a push towards better error messages :P

**Comment by AKPWebDesign** [comment]
That's a fair point.

**Comment by ubergeek42** [comment]
I'm glad that sorted it out! We'll definitely have to look at adding some better error handling.

**Comment by barnaba** [comment]
For posterity: I experienced a similar problem while trying to connect using a plain method to the encrypted relay (in my case websocket + SSL).
