### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#214]
https://github.com/ubergeek42/weechat-android/wiki/Getting-started-with-the-code

Eclipse? Who uses that anymore. Android studio all the way. Development should be easy for anyone to get started!

**Comment by adymitruk** [comment]
+1 to this. Eclipse is HORRIBLE compared to Android studio.

**Comment by Zopieux** [comment]
Nobody uses Eclipse anymore. The wiki may not be up-to-date, but it's just a matter of opening the project in Android Studio, really.
