### ISSUE TITLE
Error: null when connecting.

### ISSUE THREAD

**Issue by LimEJET** [ubergeek42/weechat-android#217]
Connecting through a plain connection on the default port to my server that has the relay set up and responds properly to netcat probing just pops up a toast notification with "Error: null" on the android client.

Version (client): v0.9-rc1
Version (server): 1.2 [compiled on May 11 2015 22:11:28]
Android 4.3

**Comment by t3chguy** [comment]
Maybe consider updating WeeChat, as you are very outdated.

**Comment by LimEJET** [comment]
I'm running Debian. They promised me it's the latest version!

No, but seriously, it says in the guide that 0.3.8 and up works.

**Comment by t3chguy** [comment]
I know, but a few functionalities within W-A are only functional from v1+, and you can add these official repositories, https://weechat.org/download/debian/ to get the latest versions.

**Comment by LimEJET** [comment]
...Wow. I AM out of date. That should probably fix it then.

**Comment by LimEJET** [comment]
Nope. Same issue.

**Comment by t3chguy** [comment]
What is the command you are using to create the relay?

**Comment by LimEJET** [comment]
OH!

...There was a space at the end of the hostname. Do I feel stupid now.
