### ISSUE TITLE
Backlog not loading when system language is Arabic

### ISSUE THREAD

**Issue by ShevaDas** [ubergeek42/weechat-android#222]
On Android 4.4.2 and Weechat Android v0.10, when the system language is set to Arabic only the most recently sent message appears when opening a buffer. None of the rest of the backlog shows up. 

When the system is set to any other language (I've tested it with English, Spanish, Russian, Korean, Japanese, Chinese, and had a friend on a Nexus 5 test it with Hebrew), or when the "force RTL" option is used, everything works normally.

**Comment by ubergeek42** [comment]
Can you post a screenshot? If you send/receive message while the buffer is open, do those lines show up properly? Or does it only show the most recent message?

Can you try the new dev version? I don't expect it to have fixed the issue but there were a few changes made that might impact it. You can download it here: http://weechat-android.ubergeek42.com/, and it'll install alongside the release version.

**Comment by ShevaDas** [comment]
All lines sent after connecting show up properly, at least until I close and restart the app. I tried the dev version and it has the same behavior.

![Lines](https://dl.pushbulletusercontent.com/9L15MlVge9f0bRTrIqqX5cwKy5A7i9mQ/Screenshot_2015-08-21-10-26-34.png)
After restarting the app:
![After restart](https://dl.pushbulletusercontent.com/JHOJgH67uxmytGD25meuHxbeT0W0zCP2/Screenshot_2015-08-21-10-27-09.png)
On dev:
![Dev version](https://dl.pushbulletusercontent.com/tNoiyp8cuvZeCGDnP0jy1agE0go0SA3M/Screenshot_2015-08-21-10-41-30.png)

**Comment by ubergeek42** [comment]
Thanks for the details, this is quite an interesting bug. I'll try to take a look at it and see if I can reproduce it/get it fixed sometime this weekend.

**Comment by ubergeek42** [comment]
@ShevaDas Can you try the new development build(it should be built in a couple of minutes). I believe this should fix the issue you were seeing. If not, please reopen this ticket and provide any details you can.

**Comment by ShevaDas** [comment]
This works! Thank you very much.
