### ISSUE TITLE
Error when connecting to secure WebSocket "boolean a.b.e.a.c(java.lang.String)

### ISSUE THREAD

**Issue by Skrupellos** [ubergeek42/weechat-android#224]
When I try to connect to a TLS secured WebSocket with Version 0.10, I get the following Error message:

```
Error: Attempt to invoke interface method 'boolean a.b.e.a.c(java.lang.String)' on a null object reference.
```

Interestingly the menu already shows a "Disconnect" option.

A CAcert certificate is used, and the CAcert root certificate is in the trust store (https connections via the browser are working).

**Comment by ubergeek42** [comment]
Can you try with the latest development version, found here:
http://weechat-android.ubergeek42.com

**Comment by Skrupellos** [comment]
Thanks, the 0.10-dev version works, except for the following message when disconnecting.
```
Error: ssl == null
```

**Comment by oakkitten** [comment]
the error itself is related to TooTallNate/Java-WebSocket#263. i don't see where this bug originates and how to solve it. the bigger problem here is TooTallNate/Java-WebSocket#346, which can be mitigated.

at the moment websocket connections are not properly closed, sockets and threads can remain open and running, and in some cases the application never notices it has disconnected. i'll try get it more or less fixed

**Comment by hacst** [comment]
I'm still encountering this issue in 0.11 . Any news on this? Cert is a valid let's encrypt with the a secure websocket provided by proxying through apache.

**Comment by Zopieux** [comment]
@hacst did you try the [latest build](http://weechat-android.ubergeek42.com/)?

**Comment by grantwwu** [comment]
Can confirm that the bug no longer occurs on 0.12-dev, however, I am having other issues with websocket support (will open separate bug).

**Comment by Zopieux** [comment]
K thanks.
