### ISSUE TITLE
implement hierarchical buffer list (order by server) 

### ISSUE THREAD

**Issue by arnottcr** [ubergeek42/weechat-android#226]
Currently the weechat buffer list is sorted by the index from the weechat relay. This is definitely the easiest way and follows with how weechat-ncurses sorts buffers, but it makes it difficult to know what buffers are attached to irc servers. Would it be possible to implement the hierarchical buffer list that glowing-bear uses?

screenshot: https://4z2.de/images/gb-desktop.png
github repo: https://github.com/glowing-bear/glowing-bear

**Comment by oakkitten** [comment]
you change the ordering in weechat and w-a will follow it
(also, buffer list filter actually works on full buffer names (such as `irc.freenode.#foo`) so you can type `freenode` there to get freenode buffers)

**Comment by adymitruk** [comment]
+1 to get this implemented. It's a ridiculous interface when you have world of fed up slack users wanting a thin client for the 10+ irc groups they are part of.

**Comment by oakkitten** [comment]
you can use `autosort.py` for this
