### ISSUE TITLE
Version 0.10 has not been pushed to the stores

### ISSUE THREAD

**Issue by Fale** [ubergeek42/weechat-android#230]
I've looked at the Google Play Store and F-Droid and both have the 0.9 version. Can you please propagate the version 0.10?
Thanks a lot :)

**Comment by ubergeek42** [comment]
It's available as a beta on the google play store, see the readme for how to become a "beta tester".

Additionally there are now nightly builds in the google play store as well. Again, refer to the readme for details.

I don't know if it's possible to do something similar for f-droid.
