### ISSUE TITLE
Enable secure Alogrithms for the use with ssh

### ISSUE THREAD

**Issue by balu-** [ubergeek42/weechat-android#232]
In the light of the current Snowden pulibcations (https://www.spiegel.de/international/germany/inside-the-nsa-s-war-on-internet-security-a-1010361.html) it would be nice if the weechat for android app could support more secure Algorythms while using ssh.

[more background info https://stribika.github.io/2015/01/04/secure-secure-shell.html]

In detail it would be nice to at least be able to use one of theese
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
and one of theese
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

I didn't quite dig to deep into it, but currently if a ssh server is configured to use only the further mentioned algorihms the app reports "Error: Algorithm negotiation failed"

**Comment by oakkitten** [comment]
oh my god

**Comment by ubergeek42** [comment]
@oakkitten not very helpful

@balu- do you know if any android apps support that?

We simply implement ssh using a java library we didn't develop(JSch), and it doesn't have support for a lot of things. I would consider changing to a different library as JSch hasn't been all that great to us, but this isn't really something I'm going to add myself. It'll all come down to whether we can find a suitable ssh library with support for those algorithms.

**Comment by balu-** [comment]
@ubergeek42 thanks for the info,

i'll try to find out about the supported stuff of JSch

**Comment by balu-** [comment]
I found the Changelog of JSch (http://www.jcraft.com/jsch/ChangeLog).
if I read this right it seems that diffie-hellman-group-exchange-sha256, and aes256-ctr were enabled by default in version 0.1.52.
To me it looks like weechat-android uses version 0.1.51 (weechat-relay/build.gradle -> compile 'com.jcraft:jsch:0.1.51' )
So it would be interessting to check if the upgrade to 0.1.52 can easily be done. 

[If that upgrade is not possible, it seems that diffie-hellman-group-exchange-sha256  can be enabled by config in 1.51 in method startNewSession(...)) by adding it as kex config as follows:
```
newSession.setConfig("kex", "diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256");
```
(source https://netbeans.org/bugzilla/show_bug.cgi?id=251309 )]

**Comment by oakkitten** [comment]
i will continue to be not very helpful by posting the result of using jsch 0.1.53

    10-18 22:07:13.697 I/|   con0 | JschLogger: Connecting to myserver port 22
    10-18 22:07:13.720 I/|   con0 | JschLogger: Connection established
    10-18 22:07:13.832 I/|   con0 | JschLogger: Remote version string: SSH-2.0-OpenSSH_6.7p1 Raspbian-5
    10-18 22:07:13.832 I/|   con0 | JschLogger: Local version string: SSH-2.0-JSCH-0.1.53
    10-18 22:07:13.832 I/|   con0 | JschLogger: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
    10-18 22:07:13.864 I/|   con0 | JschLogger: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
    10-18 22:07:14.199 I/|   con0 | JschLogger: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
    10-18 22:07:14.202 I/|   con0 | JschLogger: SSH_MSG_KEXINIT sent
    10-18 22:07:14.203 I/|   con0 | JschLogger: SSH_MSG_KEXINIT received
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    10-18 22:07:14.203 I/|   con0 | JschLogger: kex: server: none,zlib@openssh.com
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: server: none,zlib@openssh.com
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: server: 
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: server: 
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: none
    10-18 22:07:14.204 I/|   con0 | JschLogger: kex: client: none
    10-18 22:07:14.205 I/|   con0 | JschLogger: kex: client: 
    10-18 22:07:14.205 I/|   con0 | JschLogger: kex: client: 
    10-18 22:07:14.205 I/|   con0 | JschLogger: kex: server->client aes128-ctr hmac-sha1 none
    10-18 22:07:14.205 I/|   con0 | JschLogger: kex: client->server aes128-ctr hmac-sha1 none
    10-18 22:07:14.211 I/|   con0 | JschLogger: SSH_MSG_KEX_ECDH_INIT sent
    10-18 22:07:14.211 I/|   con0 | JschLogger: expecting SSH_MSG_KEX_ECDH_REPLY
    10-18 22:07:14.345 I/|   con0 | JschLogger: ssh_rsa_verify: signature true
    10-18 22:07:14.346 W/|   con0 | JschLogger: Permanently added 'myserver' (RSA) to the list of known hosts.

this text has some of the scary words you mentioned

**Comment by balu-** [comment]
@oakkitten seems helpfull to me :wink: 
This log shows that Version 0.1.53 supports more secure algorithms :+1: 
Further it seems that upgrading to this version wasn't very complicated or am i wrong?
I would be very gratefull if the weechat android client with this jsch version would be availiable, even more if this jsch would make it in the main version.

**Comment by oakkitten** [comment]
bumped to 0.1.53 in 64eba6cc4e3fb703d31aceae0461333f3b3b750f and also added a known hosts preference. mind that the library requests `hmac-sha1` while it can request `hmac-sha2-256`; i'll check later if library supports it but you can def tweak that in your ssh server. i'm told that `aes128-ctr` is secure enough but i've got no idea

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.

**Comment by dregin** [comment]
I'm seeing this with the latest version from F-droid. Here's what the server I'm SSH'ing to supports:
```
➜  ~ sshd -T | grep "\(ciphers\|macs\|kexalgorithms\)"                                                                                                                                              
ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
macs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
kexalgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
```

**Comment by oakkitten** [comment]
@dregin we will soon be using a different ssh library, please see if [this](http://weechat-android.ubergeek42.com/index-sshlib-aks.html) fixes the issue (sorry about http)

**Comment by dregin** [comment]
> @dregin we will soon be using a different ssh library, please see if [this](http://weechat-android.ubergeek42.com/index-sshlib-aks.html) fixes the issue (sorry about http)

Yep, thanks, I saw the PR.

Do you have any idea when there'll be a build available to test? I saw a note say there's a build for every commit, but I'm assuming that's only for those commits merged to master?

**Comment by dregin** [comment]
lol sorry, I didn't realise you'd linked me a build to test 🤣

**Comment by dregin** [comment]
Can confirm, that build works for me. Thanks!

**Comment by oakkitten** [comment]
woo!
