### ISSUE TITLE
out-message loss when idle

### ISSUE THREAD

**Issue by larkvirtual** [ubergeek42/weechat-android#236]
Hello!

Here is situation. Debian GNU/Linux box with weechat (1.0.1) and smartphone (Android 5.1.1) with weechat 0.9-rc1. Both are running and connected. After some idle time when I type a message in smartphone and press enter it just disappears. After it screen is redrawn (due to reconnect to linux host?) and then entered messages going to channels/privates as usual.

Looks like weechat/android must not suffer from outgoing message loss. Resend after reconnect or put it into buffer or something.

**Comment by oakkitten** [comment]
there's a resending mechanism on latest master, get the apk or a nightly build from play store (long-press input field). personally i don't consider automatic resending an option as the message can arrive *very* late. reconnections shouldn't happen often tho, do you get good signal?

**Comment by larkvirtual** [comment]
"nightly build from play store (long-press input field)" - 1) what does it means? searching playstore with "weechat nightly" returns unrelated results.
"personally i don't consider automatic resending an option as the message can arrive very late." - I'm agree, but then should be some error message "message not delivered".
I have good signal and reconnections not too often (and reconnection is goes instantly, without delays), but information loss is insulting me. Hope you will tell me how to install nightly from 1)
Thanks in advince.

**Comment by ubergeek42** [comment]
@larkvirtual Please refer to the readme to install the nightly version from google play(the tl;dr of it is you have to click a link to become a beta tester before you'll see it in the store).

Alternatively, go to http://weechat-android.ubergeek42.com and grab the latest build there.

**Comment by oakkitten** [comment]
weechat doesn't send back to relay clients any confirmations regarding received messages so every method of detecting undelivered messages would be hacky

for apk/nightly builds please see https://github.com/ubergeek42/weechat-android

**Comment by ubergeek42** [comment]
What @oakkitten said. It's basically impossible to know if the message was received by weechat. But as mentioned; in the newer builds you can view your typed message history by long pressing on the input box, so you won't have to retype any messages that managed to get lost.

**Comment by larkvirtual** [comment]
Thanks, guys.
