### ISSUE TITLE
WeeChat cannot start with a malformed time format string

### ISSUE THREAD

**Issue by pmelanson** [ubergeek42/weechat-android#240]
changed the time format string from `HH:mm:ss` to `HH:mm:ss q` and weechatandroid crashes on startup (also crashed immediately). 

hoping a reinstall fixes, but just wanted to make sure you're aware of this :)

**Comment by mhoran** [comment]
I believe this has (or had) been fixed at some point. Check out the latest [development snapshot](http://weechat-android.ubergeek42.com/).

**Comment by pmelanson** [comment]
Wow, good response time! A reinstall fixed it, so I'll take your word for it and wait for it to get to play store.
