### ISSUE TITLE
Tray icon

### ISSUE THREAD

**Issue by Mikaela** [ubergeek42/weechat-android#241]
I want to know if WA is running at a glance, but I have to pull down the notifications to see it as there is no tray icon.

**Comment by oakkitten** [comment]
it was like that before, but then it was decided WA is too long-running an application to warrant a priority notification ¯\\\_(ツ)_/¯  also, hot message notifications should be removable by swiping, while the service notification should be not, which means you can't combine the two, and having two similar icons is sorta ugly

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
