### ISSUE TITLE
Allow seeing full buffer name

### ISSUE THREAD

**Issue by Mikaela** [ubergeek42/weechat-android#242]
Currently I only see the short name (channel name/nick). I would prefer to see the full name as I name all my servers with only the two first letters and it's not impossible for me to have the same channel name or query on multiple networks and it would be easier to see that channel is `fr.#znc` than wondering what networks do the channels above or below it belong to.

```
2015-11-19 11:53:54+0200 All servers:
2015-11-19 11:53:54+0200  * fr [connected], 50 channels, 2 pv
2015-11-19 11:53:54+0200  * pi [connected], 13 channels, 0 pv
2015-11-19 11:53:54+0200  * ch [connected], 4 channels, 0 pv
2015-11-19 11:53:54+0200  * bi [connected], 8 channels, 1 pv
2015-11-19 11:53:54+0200  * vardiera [connected], 0 channels, 0 pv
2015-11-19 11:53:54+0200  * of [connected], 7 channels, 0 pv
```

_Vardiera is secondary ZNC which I don't use so much with WeeChat._

**Comment by Mikaela** [comment]
I am apparently confusing full name with something else, but what I have with buffers.pl in WeeChat directly is inactive channels hidden until they become active and others start with the server name.

![buffers.pl](https://i.imgur.com/HC5lnXN.png)

**Comment by Mikaela** [comment]
Oh and this is done with `/set buffers.look.short_names off` where my assumption of this being full name comes from.

**Comment by oakkitten** [comment]
apparently it's not “full_name”, it's just “name”. should be doable

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
