### ISSUE TITLE
Allow setting for hiding menu bar 

### ISSUE THREAD

**Issue by andreimarcu** [ubergeek42/weechat-android#243]
Love the new update but hiding the menu bar should be an option since for some people it makes navigation harder (the menus now appear from the top of the screen vs bottom of the menu bar).
When the menu bar was fixed, I could rely on it to navigate faster without having to make gestures to bring it up.

**Comment by oakkitten** [comment]
wat.

**Comment by alademan** [comment]
I don't know about where menues appear, but I agree with this.  The action bar is totally hidden and _cannot be opened_ when the soft keyboard is open, which means I have to hit back and then scroll down to make it appear.  Having an option to have the action bar always visible like it used to be would make it less of a hassle to close a buffer or disconnect.  It's actually quite annoying as it is now.

Or, I'd be happier if the action bar could just be displayed in some way while the keyboard is up.

**Comment by andreimarcu** [comment]
Right, my major annoyances are not being able to tap on the hot buffer button while having the buffers drawer on the left open, and not being able to tap the hot buffer button when the keyboard is open or even when scrolling

**Comment by oakkitten** [comment]
as i understand, you are talking two completely different things here. @andreimarcu if you are looking at the buffer list, why not tap on the hot buffer itself instead of the bell button? @alademan bleh everyone was happy with the disappearing action bar. but if there's demand for an option.. it's not impossible. what would the option say tho? always show? don't prevent showing when software keyboard is up?

**Comment by andreimarcu** [comment]
Always show :)

**Comment by wad209** [comment]
+1 for making this a setting, or at least make some way to show the top bar without having to open the list of buffers.

**Comment by TylorF** [comment]
Hey I am wondering if this is being considered at all? I totally am not for the hiding bar and when it changed I was really sad. I never got around to commenting on it thinking it might come as an option but I haven't seen it, so I was just wondering if it's being considered.

**Comment by andreimarcu** [comment]
I've been running the last version which doesn't hide the bar. It's been working pretty well but it would be really cool if the newer versions would have a setting for it.

**Comment by andreimarcu** [comment]
Amazing, thanks @Zopieux

**Comment by Zopieux** [comment]
@andreimarcu The build with this feaure is now available at http://weechat-android.ubergeek42.com/
