### ISSUE TITLE
0.11 Unable to edit settings

### ISSUE THREAD

**Issue by ddwagnz** [ubergeek42/weechat-android#244]
Latest update has somehow stopped me being able to edit settings, the only button in the menu working is about and clear ssl certs :/

**Comment by oakkitten** [comment]
what's the device and android version? as i understand, you can click stuff like “Connection” or “Buffer list”, the background changes, but nothing happens?

**Comment by ddwagnz** [comment]
Android 2.3 LG Optimus 2X (i havent gotten the chance to get a new phone!) I can get to the settings menu where it lists the options like connection, buffer list etc but only About seems to work, as in i can only go into the About tab

**Comment by oakkitten** [comment]
2.3 is api 9. currently api 10 is the minimal supported api. not sure how you got that installed

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
