### ISSUE TITLE
0.11 says "Wrong password" when no password is required

### ISSUE THREAD

**Issue by LimEJET** [ubergeek42/weechat-android#246]
After updating I re-set all my settings as the store page says. However, I still couldn't connect.
I changed my relay password to empty since the client kept saying "Wrong password", but it still happens.

I use an SSH tunnel to connect so I can see that the connection to the server itself has succeeded, but the client fails anyway.

**Sony Xperia Z1 Compact (D5503) running 5.1.1.**

On another note (related, but not sure if it should be a separate issue), when connection fails this way the menu item still says "Disconnect".

**Comment by oakkitten** [comment]
"wrong password" is misleading, it simply detects connection closed by server while not authenticated yet. make sure you don't use ssl and all ports are correct and relay server is accessible from your ssh server.

also try master/nightlies, ssh underwent significant changes there

**Comment by LimEJET** [comment]
I haven't changed my server setup since before the update (besides the password change), so I can't really remember what settings I've got on that side. All I know is that it used to work and I've changed nothing.

Why would it suddenly start closing the connection before auth?

I'll have a look at the nightlies, but it's a bit too much effort to actually use.

**Comment by vext01** [comment]
> "wrong password" is misleading, it simply detects connection closed by server while not authenticated yet.

Agreed, I got this when I didn't even have weechat running. i.e. SSH had authenticated, but connection to the relay then failed. More useful error messages would be useful.

**Comment by mhoran** [comment]
Unfortunately there's no good way, via the relay protocol, to determine what's gone wrong. We implemented the "Wrong password" toast to address the majority of issues users encountered, but as you've noticed, sometimes the detection goes wrong. The only option is to remove the "Wrong password" toast and replace it with something more generic.

**Comment by vext01** [comment]
I'd be in favour of a more generic message.

Is there a connection log the user can inspect perhaps?

**Comment by oakkitten** [comment]
the message has been changed to a less misleading one on master

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
