### ISSUE TITLE
Change place of the close button

### ISSUE THREAD

**Issue by dummys** [ubergeek42/weechat-android#250]
Hi,  is it possible to change the close button because its'the first when we open the menu...  Can you put it before quit for example? 
thanks. 
Love your app man :)

**Comment by oakkitten** [comment]
placed “close“ first deliberately as it's the most often used menu item (and being first can be chosen by long-pressing or double-tapping the three dots). why change?

**Comment by dummys** [comment]
I always type on the three dot to connect because I didn't use autoconnect, so before the update the "connect" button was at the place of the "close" and now I accidently close channels because I have the habbit to do it fast and forgot that it's close now :(
