### ISSUE TITLE
Allow copying a part of a message or several messages at once

### ISSUE THREAD

**Issue by freakyy85** [ubergeek42/weechat-android#253]
Hi. Today I wanted to add a new ssh account on my server. Some person gave me the password they wanted. It was complex. I wasn't able to select just the password to copy/paste it into the new password dialog for the user. So my request is, also be able to select sub parts of the line (like just the password, not the complete chatline) and so be able to copy/paste eg. passwords from within the chat into the password dialog.

Thank you! :)

**Comment by oakkitten** [comment]
we could also support selecting text of several messages at once

**Comment by oakkitten** [comment]
this is now possible 870dc3c57141e49ff721cf5a98ed5d3b8ece0ad8
