### ISSUE TITLE
Improve ipv6 support

### ISSUE THREAD

**Issue by pefoley2** [ubergeek42/weechat-android#255]
I recently had an issue where my relay server had an ipv6 address, but it was temporarily unreachable via that address. This manifested as an inability to connect when my phone was on a network with ipv6 connectivity, but normal operation otherwise.
It would be nice to automatically fall back to the ipv4 address (if any) if the ipv6 address is unreachable.
In addition, a toggle to force ipv4/ipv6 would be handy.

**Comment by mhoran** [comment]
We used to handle this better, but in order to improve timeouts, ended up dropping the fallback. Unfortunately better timeouts require manually implementing fallback support. 

If you want to do manual override, you can just enter the IP address.

I'll look into reimplementing the fallback support.

**Comment by Aerdan** [comment]
Manually entering an IP address doesn't work for TLS connectivity, unfortunately. I would prefer instead a checkbox or so for forcing IPv4 connectivity, either temporarily (for the duration of the session) or permanently.

**Comment by The-Compiler** [comment]
FWIW what I did is adding a DNS record `ipv4.example.com` for my domain which only has an `A` record, adjust the TLS certificate to be valid for that, and use that for weechat-android.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
