### ISSUE TITLE
Connect/disconnect via Tasker

### ISSUE THREAD

**Issue by The-Compiler** [ubergeek42/weechat-android#257]
I'd be nice to be able to connect/disconnect via [Tasker](http://tasker.dinglisch.net/). I think that'd also be possible if it was possible to do so via an Android [intent](https://developer.android.com/reference/android/content/Intent.html).

My usecase is to connect/disconnect via my Pebble smartwatch when my phone is in my pocket (to get notifications, or to stop getting them).

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
