### ISSUE TITLE
Message dropped due to transient connection failure

### ISSUE THREAD

**Issue by pefoley2** [ubergeek42/weechat-android#258]
Sometimes while I'm in the middle of composing a message, the connection to the server will drop and pick up a second later. At the same time, the screen flashes and the text I was composing vanishes.
A dropped connection should not cause an in-progress message to be lost.

**Comment by oakkitten** [comment]
i don't observe such behavior here. does this happen always or only under some special circumstances?

**Comment by pefoley2** [comment]
Not frequently, I think the issue occurs when the app thinks it's connected, you start typing, the app determines the connection was dropped, and the buffer refreshes upon reconnecting. The message compose field gets refreshed as well, causing the text in it to disappear.
Hopefully that helps clarify.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
