### ISSUE TITLE
Buffer loses scroll position on clicking links, and loading more history

### ISSUE THREAD

**Issue by epitron** [ubergeek42/weechat-android#259]
My chat window's reading position tends to get lost or jump while using Weechat-Android; it would be great if it always remembered where you were reading.

For example, if you scroll back, click a link, then return to the channel, the scroll position will be reset to the very end. When scrolling to the top and clicking "LOAD MORE HISTORY", the history is prepended to the buffer, but you stay scrolled to the very top, which makes you lose your position.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
