### ISSUE TITLE
[Feature Request] Buffer history size

### ISSUE THREAD

**Issue by troydm** [ubergeek42/weechat-android#261]
When I connect to my weechat I often see highlights in some channels but when I click on those channels I don't see any messages related to me since by the time I open weechat the message log changes significantly and the message with highlight is already long history.

It would be nice to have an option to set the buffer history length that weechat requests from relay and be able to set it to unlimited value or entire buffer log dispayed in running weechat instance

**Comment by oakkitten** [comment]
this and also the “fetch more lines” thing has been implemented in master
