### ISSUE TITLE
Add file chooser for SSH private key selection.

### ISSUE THREAD

**Issue by vext01** [ubergeek42/weechat-android#262]
When selecting a SSH private key, you have to type in the full path manually. A file chooser would be better suited.

Cheers

**Comment by oakkitten** [comment]
has been implemented on master

**Comment by vext01** [comment]
Great!

I've just noticed that the android version i'm using (from f-droid) is really quite old. I should try something newer.

**Comment by vext01** [comment]
Hrm, looks like the latest release made it to google play but not fdroid.

**Comment by oakkitten** [comment]
master == nightlies != the “main” google play version
