### ISSUE TITLE
Ability to mute notifications on a per-buffer basis

### ISSUE THREAD

**Issue by vext01** [ubergeek42/weechat-android#263]
Hi,

Would it be possible to add a "mute notification" toggle button to each buffer in weechat-android? It would work just like the similar feature in google hangouts.

Cheers

**Comment by oakkitten** [comment]
w-a should respect notification levels set in weechat, so you can use them

**Comment by vext01** [comment]
great, thanks

**Comment by vext01** [comment]
Actually, I would like to be notified of highlights in the weechat terminal, but not with a android notification. I don't think this is possible using the existing mechanism, right?

**Comment by vext01** [comment]
I can turn of *all* notifications in settings, but not on a per-buffer basis.

**Comment by oakkitten** [comment]
`/buffer set notify <level>`, level being a digit from 0 to 3, the digits correspond to the list of possible values of `weechat.look.buffer_notify_default`. not very obvious ikr

you can also hide buffers completely in w-a (see faq) or check “only sync open buffers”, in which case you won't receive notification *sound* for unopened buffers

you can't have a different notify level in w-a. buut that sounds implementable

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
