### ISSUE TITLE
Ability to turn off reordering buffers based upon highlights.

### ISSUE THREAD

**Issue by rymate1234** [ubergeek42/weechat-android#264]
I made this suggestion in the irc channel last night, and somone recommended I opened a github issue for it. Would it be possible to implement this as a preference, as I'd prefer the list of buffers to have the same order as my weechat buffers sidebar.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
