### ISSUE TITLE
Add some sort of share intent functionality

### ISSUE THREAD

**Issue by robcross** [ubergeek42/weechat-android#265]
It would be super nice if weechat-android supported the standard android "share" intents.

If I want to share a webpage or a reddit link through text, I just click the share button -> share with signal -> choose my contact -> hit send.

I would imagine that the flow would be similar with weechat-android.
Share button -> share with weechat -> choose channel or already open query -> hit send.

**Comment by The-Compiler** [comment]
:+1:, definitely one of the little things I'm missing as well

**Comment by oakkitten** [comment]
this has been implemented
