### ISSUE TITLE
SSL doesn't validate hostname

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#266]
The hostname on the certificate isn't validated to make sure it matches what we're connecting to. This is bad.

https://op-co.de/blog/posts/java_sslsocket_mitm/

**Comment by Zopieux** [comment]
I've got a [working implementation](/ubergeek42/weechat-android/compare/master...Zopieux:hostname-verification) that uses `SSLCertificateSocketFactory` as advised by the *op-co.de* article.

Feedback/suggestions appreciated. Open questions:

1. Do we want to allow verification exemptions? If not, there is no need for the `ExemptibleSSLSocketFactory` stuff and corresponding dialog – we just show the error toast.
2. If yes, do we want to store exemptions on disk? This would imply a new preference to clear them.

**Comment by mhoran** [comment]
> Do we want to allow verification exemptions? If not, there is no need for the ExemptibleSSLSocketFactory stuff and corresponding dialog – we just show the error toast.

Let's go with no for now. Given most folks are probably using self-signed certs anyway, they can probably get the hostname correct. Plus, if we're not verifying the hostname, we might as well not be using SSL.

**Comment by Zopieux** [comment]
Fine, I will open a pull request with just the specific code required for hostname verification.

What about websockets? Do we want to upgrade to master so we can use `setSocket`?

**Comment by GLolol** [comment]
I've been using direct IP for my server host, so upgrading suddenly broke my config \*grumble\*

**Comment by Zopieux** [comment]
@GLolol Not an issue, just do as described [in the wiki](https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-WeeChat#create-a-self-signed-certificate).

**Comment by GLolol** [comment]
I've fixed it, but my setup was much older than a 7 day-old wiki page
