### ISSUE TITLE
Connection over an SSH tunnel (JuiceSSH) does not succeed

### ISSUE THREAD

**Issue by manasb** [ubergeek42/weechat-android#267]
Hello,

I am running weechat-android on my android phone. I am running version
0.11 from google play.

I initiate a SSH tunnel using a different app and then I try to connect
to the tunnel with weechat-android by specifying the address as
127.0.0.1 and providing the appropriate port.

On my weechat client which is running the relay, I see a message that
says "relay: new client on port 42040: 2/weechat/127.0.0.1" and I see
the following lines in relay_raw:

```
15:03:12 [2] weechat +| init password=nopassword,compression=zlib
15:03:12              | (checklogin) info version
15:03:12 [2] weechat +| obj: 40 bytes, id: checklogin
15:03:12 [2] weechat +| (listbuffers) hdata buffer:gui_buffers(*)
number,full_name,short_name,type,title,nicklist,local_variables,notify
15:03:12              | (last_read_lines) hdata
buffer:gui_buffers(*)/own_lines/last_read_line/data buffer
15:03:12 [2] weechat +| obj: 3266/9794 bytes (67%, 0.35ms), id: listbuffers
15:03:12 [2] weechat +| obj: 594/1338 bytes (56%, 0.08ms), id:
last_read_lines
15:03:12 [2] weechat +| (hotlist) hdata hotlist:gui_hotlist(*) buffer,count
15:03:12              | sync
15:03:12 [2] weechat +| obj: 356/912 bytes (61%, 0.06ms), id: hotlist
15:03:12 [2] weechat +| obj: 278/398 bytes (31%, 0.05ms), id:
_buffer_line_added
15:03:12 [2] weechat +| obj: 200/280 bytes (29%, 0.04ms), id: _nicklist_diff
15:03:13 [2] weechat +| obj: 253/345 bytes (27%, 0.04ms), id:
_buffer_line_added
```
However, weechat-android does not complete the connection and does not
display the list of buffers. Do you have any idea what could be wrong?

Thanks,
Manas

**Comment by ubergeek42** [comment]
That's really odd since that all looks correct. You can see weechat sending and receiving data from the client.

Which weechat version are you running? Can you try the nightly/development build; see the project readme for how to get it(its got a few new things I think).

**Comment by manasb** [comment]
It was a mistake on my end. My network is a little odd - it was a VPN client running on dd-wrt that was tunneling all traffic that was causing the issue. Disabling the VPN sorted things out.
