### ISSUE TITLE
Provide F-Droid repo for development verions

### ISSUE THREAD

**Issue by jspricke** [ubergeek42/weechat-android#268]
Hi,

would it be possible to provide a simple F-Droid repository? There is a Howto here: https://f-droid.org/docs/Publishing_Nightly_Builds/. This would allow all F-Droid users to get updates automatically. I guess this could be integrated into publish_s3.sh rather easily.

Thanks!

(edit: update link)

**Comment by ubergeek42** [comment]
Ah very neat. I didn't know this was a thing that could be done with f-droid, but I'd be happy to set something like this up!

**Comment by krt16s** [comment]
You can even abuse github.io for this, e.g. see my sample at https://github.com/krt16s/krt16s.github.io

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
