### ISSUE TITLE
Address family not supported by protocol 

### ISSUE THREAD

**Issue by perttuim** [ubergeek42/weechat-android#272]
I'm trying to connect to Weechat via ssh tunnel and I get this error:

`Error: recvfrom failed: ECONNRESET (Connection reset by peer)`

Also, this is what I found from auth.log on the server itself:

`Feb 11 14:49:18 irc sshd[19149]: Accepted publickey for perttuim from 88.195.xxx.xx port 60251 ssh2: RSA cf:07:ff:e6:a0:0b:21:60:ee:79:a1:b9:63:8a:c6:fb
Feb 11 14:49:18 irc sshd[19149]: pam_unix(sshd:session): session opened for user perttuim by (uid=0)                                                    
Feb 11 14:49:18 irc sshd[19151]: error: socket: Address family not supported by protocol                                                                
Feb 11 14:49:18 irc sshd[19151]: error: connect_to localhost port 9001: failed.                                                                         
Feb 11 14:49:18 irc sshd[19149]: pam_unix(sshd:session): session closed for user perttuim`                                         

I'm using Google Play nightly builds. Any ideas?

**Comment by ubergeek42** [comment]
The address family not supported by protocol seems to be related to ipv6(but most indicate it isn't a real issue).
Are you certain weechat is listening on that port(run `/relay listrelay` to double check). You can also try changing the host from 'localhost' to 127.0.0.1, but that probably doesn't matter.
