### ISSUE TITLE
No longer auto-connects

### ISSUE THREAD

**Issue by tribut** [ubergeek42/weechat-android#273]
Just updated to latest nightly and noticed that the app no longer connects on startup. Could not find a setting either. Is this intentional?

**Comment by ubergeek42** [comment]
Yes, that sounds about right. The app is more "android like" these days, the quit button is gone and it's more intended to just stay running and connected. That said, you don't have to go into the menu to connect, you can just tap on the icon in the center of the screen and it'll connect.

**Comment by tribut** [comment]
Hm, the "click the cat" method is certainly less annoying. Thanks.

I still think "auto-connect on open" would be helpful. Not sure if there is actually a use-case where someone wants to open the app but *not* connect.

**Comment by tribut** [comment]
(But feel free to close this issue if you disagree.)

**Comment by brunnre8** [comment]
You can not click the cat if there are still buffer open... I don't want to manually close them all just to reexecute the client.

I have a headless setup for exactly that case, I do not want it to constantly run in the background

**Comment by thejan2009** [comment]
@ubergeek42 
Could that connect/disconnect cat icon live in its own buffer alongside the other chat buffers (with a configuration that allows current hiding behaviour)? Disconnecting via hamburger menu is a bit clumsy. 

I'm willing to implement the feature myself, just asking about your opinion, since I wouldn't want to maintain a single-patch fork.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
