### ISSUE TITLE
Allow temporarily toggling filters per buffer/globally

### ISSUE THREAD

**Issue by Mikaela** [ubergeek42/weechat-android#274]
There isn't need to do it so often, but there are still cases when it's desirable to see everything happening on channel for example:
- checking when netsplit started (no one had talked in 5 minutes so smart filter hid it).
- being op and being requested to ##fix_your_connection -ban user who is hidden by smart filter.
- being op and channel having troll problem with someone on your filter list.

**Comment by demure** [comment]
This would also be nice if it allowed for in-place-buffer-refreshes. Currently if you `/filter toggle` existing open buffers continue show filtered content if you started in the off position; and continue to not show hidden content if you start in the on position. (At least for old content). It takes a disconnect+reconnect to refresh open buffers.

**Comment by oakkitten** [comment]
this has been implemented
