### ISSUE TITLE
Crashes when network changes, or manually try to disconnect

### ISSUE THREAD

**Issue by azizLIGHT** [ubergeek42/weechat-android#275]
If you use ssh tunnel to the machine hosting weechat and connect to the relay on localhost, then any network changes will cause weechat-android to crash: Unfortunately, weechat (dev) has stopped: Report/OK

Going from WLAN to 4G, 4G to WLAN, losing data signal on 4G, disabling WiFi when connected to the relay by WiFi can cause w-a to crash in the background, and manually selecting disconnect from the menu will cause w-a to crash in the foreground. 

This crashing behavior doesn't happen when connected to the same relay using a plain connection.

Details:
Android 4.4.4
Weechat v0.11-50-gfe9bedb

**Comment by azizLIGHT** [comment]
I investigated this some more and found out that weechat-master-d22ef68.apk (v0.11-47-gd22ef68) doesn't have this behaviour. Instead, on a connection change or toggling airplane mode, it only produces a system popup message saying "Error: StreamClosed". The problem is with v0.11-50-gfe9bedb

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
