### ISSUE TITLE
An option to disable the readmarker.

### ISSUE THREAD

**Issue by rgarch** [ubergeek42/weechat-android#276]
I was discussing this in irc at some point. I'd like to have an option to disable the readmarker as I've disabled it on my server's weechat client so I'd like it to also be disabled on this client to match the configuration.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
