### ISSUE TITLE
Android N

### ISSUE THREAD

**Issue by JulienPalard** [ubergeek42/weechat-android#279]
Didn't had time to diagnose, but I'm trying the Android N beta and Weechat can't connect to my server (yes my server is up, my tablet is still connected). Wait for it, I can't decently write an issue without taking a look at logcat ... Oh nothing interesting in logcat, I may take a more deep look later, I'm just opening this ticket so you're aware of it.

**Comment by gilandose** [comment]
what connection method are you using ssh with key?

**Comment by kaniini** [comment]
an interesting observation is that weechat reports a successful connection.

this smells of a caught exception to me, probably in the ui code

**Comment by gromez** [comment]
Same issue, it looks connected but buffers are not opened.

**Comment by ubergeek42** [comment]
@kaniini @gromez double check that your relay type in weechat is 'weechat' or 'ssl.weechat' and not 'irc'. Or paste in the output of `/relay listrelay` here if you aren't sure.

@JulienPalard You might want to check that as well. Unless it was working with an older android.

**Comment by JulienPalard** [comment]
@ubergeek42 I'm 100% sure it worked 10mn before upgrading to Android N, and still work on my tablet. I did not find the time to debug it, I just read the logcat and did not find anything, I found the flags to enable more verbosity in the code but did not have time to try them. I'm having a week of holidays, hope to find the time.

**Comment by gromez** [comment]
Here is the output of `/relay listrelay`

`port 8001, relai : weechat, IPv4+6, démarré le : lun., 22 févr. 2016 11:34:21`

So, it looks good, and like @JulienPalard it was working fine before Android N upgrade. I will try to do a debug with adb and post result soon.

**Comment by JulienPalard** [comment]
@gromez adb did not give nothing, but there's flags in the code to enable more verbosity, it may be a good start to recompile with them and try adb. Otherwise, we'll need to use the debugger, BUT since Android N, my Android Studio won't stop on breakpoints, I did not take time to search why, not needing it for the moment, tell me if you have the same problem (and find the solution, probably simply upgrading Android Studio, dunno).

**Comment by gromez** [comment]
@JulienPalard yesterday I tried to compile the project, I used gradlew and it works fine, 2 APKs were generated (debug version). But I can't see any log in logcat, do you know if there are some flags to set?

**Comment by JulienPalard** [comment]
Yes look at the various `final private static boolean DEBUG_` flags in src/main/java/com/ubergeek42/WeechatAndroid/WeechatActivity.java

**Comment by JulienPalard** [comment]
Still did not take time to look into it myself :(

But I got the monthly Android N release (NPD35K) and I'm still getting the same problem.

**Comment by Rawa** [comment]
I've had the same issue as well, done some research. It seems like the issue lies within Jsch. WeeChat tries to initiate connection by sending the hello ("info version") over the SSHTunnel. However, on the server-side it is not received. I've verified that the connection internally in the Android device is working, weechat correctly sends the hello message over to the localport of Jsch (port 22231).

The problem manifests itself by Weechat disconnecting the SSH connection because it does not get a response from the hello message, due to timeout.

**Comment by kaniini** [comment]
I do not use SSH tunneling and still see this problem, so I disagree.

**Comment by Rawa** [comment]
@kaniini What connection type do you use? I could be two seperate issues.

**Comment by kaniini** [comment]
It occurs on all connection types.  Plaintext, TLS, SSH, Stunnel, and both WebSocket variants.

**Comment by Rawa** [comment]
@kaniini are you sure this is Android N related? A friend of mine is using weechat WebSocket without any issues.

**Comment by kaniini** [comment]
Yes.  It is Android N related.  It runs fine on versions other than Android N.

**Comment by kaniini** [comment]
Regarding the Jsch issue: how are you tracing the I/O to verify that it hits the server at all?  It probably isn't.

**Comment by Rawa** [comment]
@kaniini I didn't say it reached the server. I did several tests and a couple of hours of debugging weechat-android.

1: Tested setting up nc on the server, selecdted corresponding relay port. When using weechat on pre Android N device the nc received data. When using Android N, no data was received server side.
2: I tested using nc on the mobile (same device running Weechat Android) and set the Local tunnelport to a random port corresponding to nc setup. Data was sent from weechat correctly. 

Conclusion: Somewhere between Jsch receiving the data and delivering it on server side something seems to go wrong under Android N. Why this is, I do not know at this moment.

**Comment by kaniini** [comment]
I suggest looking at the plaintext setup if you want to debug further, it is a simpler codepath.

**Comment by Rawa** [comment]
@kaniini What was your conclusion from your debugging the application, it was pretty clear that the issue that I experienced is connected to Jsch.

**Comment by JulienPalard** [comment]
Today I tried settting an nginx proxy, as I'm having HTTPS with letsencrypt:

```
 location /weechat {
     proxy_pass http://127.0.0.1:9000;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection $connection_upgrade;
     proxy_read_timeout 4h;
}
```

with:

```
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
```

And it works, so the bug is really connection-type dependent, so far:

plaintext: don't work
websockets over SSL: work

**Comment by Edholm** [comment]
That seems consistent with what @Rawa  found since `WebSocketConnection` is the only `Connection` that does not use `writeLoop()` from `AbstractConnection`.

**Comment by JulienPalard** [comment]
I wrote my update too soon, using websockets I connect sucessfully, I can send like one message, receive like one, then nothing: Cannot send, cannot receive, cannot disconnect.

Tried a force close + clean data, reconfigure: cannot connect, but I'm getting a:

> Attempt to invoke interface method boolean a.b.e.a.c(Java.lang.string) on a null object reference.

**Comment by JulienPalard** [comment]
Upgraded to Android N version `NPD56N`, force close, clean data, reconfigure using `WebSocket SSL`: it works, for the moment.

**Comment by Edholm** [comment]
I have the same build and Plain and SSH connection does not work.

However the problem seems to be located in SocketChannel. The SocketChannel does not seem to want to write anything. Switching the SocketChannel to a normal Socket in PlainConnection.java solves the problem for the plain connection at least...

**Comment by JulienPalard** [comment]
After a few hours, until I roamed out of my Wi-Fi specifically, the client went to a "frozen" state, where I still can switch buffers, scroll them, but I can't disconnect neither send message. No displayed errors. Nothing happen with I hit "disconnect". Nothing server side when I write a message, and no error displayed when a send a message, but the message does not appear on the buffer.

I'm trying a force close... and it connects back again and it works again.

**Comment by mhoran** [comment]
That's a bummer. I switched over to `SocketChannel` as it is interruptible during connect. There are approaches using `Socket`, but they're not pretty. We may not be left with a choice, though.

**Comment by charafau** [comment]
we can always wrap socket implementation in RxJava and do something reactive ;)

**Comment by etu** [comment]
I've heard that Android N is rolling out soon. Anything happening on this topic?

**Comment by charafau** [comment]
Someone's discovered what's wrong but didn't comment here... As far as I remember it was something wrong with using Socket Channel, and it was working with normal Socket

**Comment by JulienPalard** [comment]
Just got the Android N release, build NRD90M. I'm still having a kind of "frozen" interface on which I can't disconnect, can't communicate, can't get messages when I switch from a network to another. I'm using WebSocket (SSL).

**Comment by charafau** [comment]
I discovered that `master` is broken for ssh connection for `every` android version.

**Comment by etu** [comment]
@charafau Are you sure? I'm running 0.12-dev on Android 6.0.1 build MTC20F (Nexus 5X) with SSH and it works fine.

**Comment by charafau** [comment]
I tried emulator with 22, 23 and 24 and ssh didnt work for me

**Comment by zilti** [comment]
I have the same problem on Android 5.1. Connection type plain. As soon as I select "connect", it connects successfully and then immediately crashes.

**Comment by charafau** [comment]
Did you try building it by yourself ?

**Comment by zilti** [comment]
No, and tbh it's a bit much to install the whole dev kit just to recompile an app.

**Comment by oakkitten** [comment]
@zilti if you are running weechat built after around june, it might be #302

**Comment by zilti** [comment]
I installed it yesterday from Play Store, so, yes.

**Comment by oakkitten** [comment]
@zilti i meant weechat itself

**Comment by zilti** [comment]
Yes, my weechat version is more recent, it's the newest version from FreeBSD ports.

**Comment by Edholm** [comment]
Works in the latest nightly for me now. Just thought I would let you guys know :)

**Comment by etu** [comment]
Wosh, confirmed working on Android N on Nexus 5X!

**Comment by agiz** [comment]
Weechat app off of f-droid crashes as soon as it connects to weechat (ver. 1.7.1, debian). Connection type is WeeChat SSL. OS is android 7.1.1., custom rom.

**Comment by oakkitten** [comment]
@agiz try the nightly please

**Comment by agiz** [comment]
@oakitten thank, it works!
