### ISSUE TITLE
Volume keys for Send history

### ISSUE THREAD

**Issue by bqv** [ubergeek42/weechat-android#281]
As in Andchat, it would be nice to be able to scroll through the send history for each buffer, or even globally, using the volume keys. This shouldn't be hard to implement, and would function as a third option for the volume keys

**Comment by AeliusSaionji** [comment]
Or even, I have up/down arrows on my android keyboard. Definitely missing the input buffer history.

**Comment by Zopieux** [comment]
My face when the code is already written but needs cleanup and refactor against the `recycler` branch.

**Comment by oakkitten** [comment]
do eet boi

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
