### ISSUE TITLE
Weechat android crashes with an out of memory error

### ISSUE THREAD

**Issue by chrisamin** [ubergeek42/weechat-android#283]
Whenever I try to connect to my server using Weechat SSL the app dies. I've attached log output, which reports an error trying to allocate a 1GiB memory block.
[device_info.txt](https://github.com/ubergeek42/weechat-android/files/259199/device_info.txt)
[logcat.txt](https://github.com/ubergeek42/weechat-android/files/259200/logcat.txt)

This is v0.11 from the Play Store.

**Comment by ubergeek42** [comment]
That looks like it happens outside of our code during verification of the certificate chain. Is there anything special about your certificate?

**Comment by chrisamin** [comment]
Not as far as I know. It's a standard LetsEncrypt certificate.

**Comment by Zopieux** [comment]
@chrisamin please check you still have the issue on the [latest dev build](http://weechat-android.ubergeek42.com/). Play Store version has been out of date for more than a year.
