### ISSUE TITLE
Allow fetching all buffers instead of just the ones I open and keep them fetched since connect

### ISSUE THREAD

**Issue by Mikaela** [ubergeek42/weechat-android#284]
`2016-05-12 10:19:16+0300 < Mikaela> would it be possible for WA to keep all lines fetched all the time? I hate it when it fetches for lines forever (without anything confirming it even does anything) and it's easier to just check what has happened at Telegram or only talk on the bridges channels there on mobile.`

`2016-05-12 10:19:36+0300 < Mikaela> I have unlimited data.`

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
