### ISSUE TITLE
cannot specify a custom WebSocket path

### ISSUE THREAD

**Issue by PaulSalden** [ubergeek42/weechat-android#293]
At the moment, websockets can only be connected to if they're accessible at the root of a domain. Say I have a websocket at:

_wss://my.domain.com:port/path_

Using "my.domain.com/path/" as "Relay host" and "port" as "Relay port" causes WeeChat Android to try and connect to:

_wss://my.domain.com/path/:port_

Which obviously fails. I believe an additional "path" option would be the most straightforward solution.

**Comment by ubergeek42** [comment]
If anyone wants to fix this, it's likely pretty straightforward(aside from the mucking about making the preferences screen pretty)

This line here is probably what really needs to change:
https://github.com/ubergeek42/weechat-android/blob/master/weechat-relay/src/main/java/com/ubergeek42/weechat/relay/connection/WebSocketConnection.java#L34

If you change the constructor so it can actually be a preference in the app, you also need to change these lines:
https://github.com/ubergeek42/weechat-android/blob/master/weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/RelayService.java#L230 - To change the call to the constructor
https://github.com/ubergeek42/weechat-android/blob/master/weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/service/P.java#L123 - Add new preference here(and use it in RelayService.java to pass to the constructor)
https://github.com/ubergeek42/weechat-android/blob/fe9bedbad72fa7bc6a982dc5004057b277be09f3/weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/utils/Constants.java - Declare preference constants here
https://github.com/ubergeek42/weechat-android/blob/fe9bedbad72fa7bc6a982dc5004057b277be09f3/weechat-android/src/main/java/com/ubergeek42/WeechatAndroid/PreferencesActivity.java#L170 - modify if you want preferences to be visible only when websocket is selected.

I may have missed something, but if anyone wants to make a PR or needs help, let me know.

**Comment by oakkitten** [comment]
implemented in 841c17f113d7de3f14c131640ef5dc376521d780
