### ISSUE TITLE
OTR support

### ISSUE THREAD

**Issue by lesderid** [ubergeek42/weechat-android#294]
[OTR](https://otr.cypherpunks.ca/) support would be nice to have.

There's a weechat implementation at https://github.com/mmb/weechat-otr.

**Comment by lesderid** [comment]
When the OTR plugin is active in weechat, OTR messages get relayed unencrypted. This poses a security issue for relays without TLS. When you start a conversation using weechat-android, it should probably disable the OTR plugin on the main client.

**Comment by Mikaela** [comment]
Is this even possible to do with WeeChat **relay** client? Also how would you move to the main WeeChat and see the messages there (without OTRvX which brings support for multiple clients)?

How would you fix this in WeeChat-OTR?

**Comment by Zopieux** [comment]
As stated, this is not a feature for WA but for weechat itself. Relays just relay (hah!) the data. It's your responsibility to use a properly encrypted relay channel when using OTR through weechat.
