### ISSUE TITLE
SSH Tunnel no more working with Nougat 7.0 on Nexus 6p

### ISSUE THREAD

**Issue by dummys** [ubergeek42/weechat-android#303]
Got an error when connecting to ssh tunnel. Auth is ok but tunneling is no more working.
Build ID V 0.11

Tryed the nightly dev build 0.12, got problem this time for the authentication, got a "preauth" 

Sep 21 22:40:34 gaia sshd[6074]: error: Received disconnect from 127.0.0.1 port 48507:3: com.jcraft.jsch.JSchException: Auth fail [preauth]
Sep 21 22:40:34 gaia sshd[6074]: Disconnected from 127.0.0.1 port 48507 [preauth]

**Comment by ubergeek42** [comment]
Try the build from the n-fix branch(there's another issue on here about the
same issue with a link to the build)

**Comment by dummys** [comment]
Yes but where ?

**Comment by dummys** [comment]
In fact it's connected after a long long moment with 0.11. But everything is slow inside when I type on IRC.

**Comment by ubergeek42** [comment]
http://weechat-android.ubergeek42.com/index-n-fix.html

**Comment by dummys** [comment]
Yup just found it.
Same error:

error: Received disconnect from 127.0.0.1 port 48581:3: com.jcraft.jsch.JSchException: Auth fail [preauth

**Comment by dummys** [comment]
How can I help you to fix this ? which log do you need ?

**Comment by dummys** [comment]
?

**Comment by IreneKnapp** [comment]
I am also experiencing this, please let me know if I can help

**Comment by dummys** [comment]
ubergeek42: N-fix doesn't fix the issue, got the preauth fail still

**Comment by IreneKnapp** [comment]
Okay, the above-linked n-fix build does fix it for me.

**Comment by nijotz** [comment]
Fixes it for me too.  Nexus 5x on Android 7.0.  Weechat v0.11 does not work but works with the 0.12-dev linked above.  Using SSH tunnel with password

**Comment by IreneKnapp** [comment]
Strangely enough, this build stopped working for me again yesterday. The failure mode looks to be the same as it was for the main-line dev build from the Play store, and as others have described in this thread. Nexus 6P, Android 7.0.

**Comment by peterrus** [comment]
What am I supposed to do with the ssh-keyscan hint? I didnt have to do this in previous vsrsions

**Comment by IreneKnapp** [comment]
@peterrus On the host that is the other end of your ssh tunnel, run the ssh-keyscan command line that the hint gives you. Save that output to a file and provide that file to the Android client.

**Comment by peterrus** [comment]
Where host is the hostname of the server that runs the ssh tunnel? Because
that gives me a 'reject HostKey' error in the android weechat client.

**Comment by peterrus** [comment]
Got it. Thanks for the help Irene! The client from the downloadlink above
also fixes the problem for me.

**Comment by IreneKnapp** [comment]
No problem :)

**Comment by oakkitten** [comment]
this has should be fixed in 308807b9ec082721185ae6c315c50712a111db39 on master. please test master and close the issue if it works

**Comment by IreneKnapp** [comment]
Yes. Works for me! Awesome. I didn't create the bug, so I won't close it; perhaps @dummys wants to.

**Comment by dummys** [comment]
Yes it works in the master for me as well.
Thanks.
closing the issue.
