### ISSUE TITLE
Network connections not closed sometimes

### ISSUE THREAD

**Issue by Phyks** [ubergeek42/weechat-android#306]
Hi,

I have a maximum number of connection set to 5 on my Weechat relay. I am only using Weechat for Android as a relay client (version from F-Droid).

Very often, it happens that the connection fails due to "Connection reset by peer". When checking the logs, there are a lot of clients still connected, which are actually ghost connections from my Android device with Weechat for Android, not closed by the app.

Actually, I manage to keep a connection open with Weechat for Android, while the app is closed (at least I do not have any permanent notification stating otherwise). I did not yet manage to figure out what exactly is happening, but I guess it has something to do with switching between connections (when I lose data network or when I switch from 3G to Wifi for instance).

I know at least two people having this issue, myself on Android 4.4.2 and F-Droid version, and another one on Android 6 and Google Play version. Anyone else is having such issue?

Thanks!

**Comment by Edholm** [comment]
I am experiencing this issue as well on build v0.11-77-gae54c0a

**Comment by oakkitten** [comment]
i'm not sure we can do anything about ghost connections. often one end of the connection is closed but the other end doesn't receive any information about that. what you can try is force close w-a and see if that has any effect on what weechat sees. if it has, we probably have some sockets that weren't closed, if not, welp

**Comment by Phyks** [comment]
Not sure to fully understand your last comment. When going to Weechat, there is indeed clients connected to the relay, and when I force disconnect them, it solves the issue.

Temporary fix I have is to disable the number of relay clients limitation. But I'd rather not.

Force-disconnecting from Weechat itself is not really an option either as very often when I use Weechat for Android, I do not have access to my Weechat session over SSH.

Not sure what can be done about this, nor if it is more of a Weechat issue or a Weechat for Android one. I also have `relay.network.clients_purge_delay = 0` which should purge relay clients immediately, and AFAIK, close automatically sockets when client is not responding, which would mean that Weechat for Android is somehow keeping the connection open.

**Comment by oakkitten** [comment]
i meant force close on android, that's when you long press the app, then go to app info, then press the force stop button

if i read it right weechat only sets TCP_KEEPALIVE and doesn't ping clients. keepalives are dependant on your system and kernel settings and typically will not trigger any action unless 2 hours passed since last contact. so you _definitely_ are going to see some ghost connections. weechat-android still might be responsible for some of them tho

**Comment by Phyks** [comment]
Ok, I'll try to force close the app on Android next time I see this behavior and update the issue.

**Comment by Phyks** [comment]
Seems that force-closing the app does not do much :/

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
