### ISSUE TITLE
Doesn't reconnect upon focus

### ISSUE THREAD

**Issue by brunnre8** [ubergeek42/weechat-android#308]
In the nightly version if one disconnects and hits the back button until the app goes into the background and then again gives focus it does not auto connect.

Only works if the activity is destroyed (eg swiped away in recent)

This is not the case in the old version via the quit button (there it does the right thing)

**Comment by oakkitten** [comment]
are you sure that if you disconnect, and then swipe the app from recent list, and then tap on it, the app attempts to connect? it is supposed to display a cat looking down

**Comment by brunnre8** [comment]
Hm, you are right... What happened to the auto connect option?

But at least it allows you to connect quickly by tapping on the cat, this is not possible when buffers are open

**Comment by oakkitten** [comment]
i suppose it was removed since the option “connect on system boot” was implemented

**Comment by brunnre8** [comment]
But that's a different function in my view... I don't want it running upon boot, but it makes very much sense to connect upon opening the app

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
