### ISSUE TITLE
Tags for versions (F-Droid updates)

### ISSUE THREAD

**Issue by Phyks** [ubergeek42/weechat-android#311]
Hi,

Some users do not have Google Play on their device and rely on third party stores to get apps. Typically, I get most of my apps on F-Droid, including this one.

I think F-Droid relies on tags to check if new versions are available and build the APKs. Although version 0.12 is available, there is no associated tag on Github and (I guess) for this reason F-Droid users are stuck with 0.11.

Would it be possible to see if something can be done to fix this? Also, another option that could be interesting would be to host a third party F-Droid repository to serve Weechat builds directly, without relying on F-Droid compilation mechanism, the same way as it is done on Google Play.

Thanks!

**Comment by jspricke** [comment]
0.12 has not been release yet. See #282 and #268 as well.

**Comment by Phyks** [comment]
Ah, indeed, missed those. Closing as a dupe.
