### ISSUE TITLE
[Dev] Error cannot verify hostname: <IP>

### ISSUE THREAD

**Issue by chosig** [ubergeek42/weechat-android#316]
After yesterday's update I can't connect to my relay (ssl.weechat) anymore. I can't be more specific that's the only error i get in the phone.

Oh, just saw this inside weechat...

09:58 weechat     ╡ relay: new client on port 9001:
                  ╡ 1/ssl.weechat/123.123.123.124
09:58 weechat     ╡ relay: new client on port 9001:
                  ╡ 2/ssl.weechat/123.123.123.124
09:58 weechat  !! ╡ relay: reading data on socket for client
                  ╡ 2/ssl.weechat/123.123.123.124: error -110 The TLS
                  ╡ connection was non-properly terminated.             09:58 weechat     ╡ relay: disconnected from client
                  ╡ 2/ssl.weechat/123.123.123.124             

I connect with IP to a VPS.

Also, an option in the dev version for more verbose error messages, perhaps a local "buffer".

Sorry for the formatting, my phone

**Comment by Zopieux** [comment]
The Android HostnameVerifier is quite strict. It requires that your certificate specifies a *Subject Alternative Name* of type *IP Address*.

#### Step 1: generate relay.pem with the right IP SAN
Within `<weechat home>/ssl`, run this:
```shell
$ export MYIP=1.2.3.4 # change me!
$ openssl req -x509 -nodes -newkey rsa:2048 -keyout relay.pem -subj "/C=US/O=Whatever/CN=example.org" -config <(cat /etc/ssl/openssl.cnf <(printf "\n[v3_ca]\nsubjectAltName = @alternate_names\n[alternate_names]\nIP.1 = \${ENV::MYIP}")) -days 365 -out relay.pem
```
Beware, this will **overwrite** the existing `relay.pem` file if any.

#### Step 2: tell WeeChat you updated the certificate
Run the following in WeeChat (from your VPS, as you can't connect anymore!):
```
/relay sslcertkey
```

**Comment by chosig** [comment]
Aha! Thanks

**Comment by Zopieux** [comment]
I update the [wiki about SSL](/ubergeek42/weechat-android/wiki/Using-SSL-with-WeeChat) with the relevant commands.
