### ISSUE TITLE
Add option to launch intent prior to connecting

### ISSUE THREAD

**Issue by jp-bennett** [ubergeek42/weechat-android#319]
I've recently started using Weechat Android, and it's great!  Thanks for your work on it!  I'm using the ssh tunneling option which works beautifully.  The only snag is that I also protect my ssh port with Fwknop (Next generation port knocking), so to connect to weechat, I have to send an fwknop packet from the Android app, Fwknop2, and then switch over to weechat and connect.

I'm actually the author of the Fwknop2 app, and I plan to add intent handling to Fwknop2 in the near future (Tracking it at https://github.com/jp-bennett/Fwknop2/issues/49).  It would be great to get the two apps working together, and would make for a much better user experience for anyone Fwknop to protect their ports.

--Jonathan Bennett

**Comment by ubergeek42** [comment]
Sounds interesting. I don't think it's something I'll code myself, but if you submit a PR with the feature I'm happy enough to merge it.

**Comment by jp-bennett** [comment]
@ubergeek42 Fair enough.  I'm not sure when I'll get to this, but I plan to get it working eventually.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
