### ISSUE TITLE
Constantly Waiting for Network

### ISSUE THREAD

**Issue by paddatrapper** [ubergeek42/weechat-android#322]
On the Xiaomi Mi 4 the app is constantly "Waiting for network", even when the phone is connected to a network. It happens consistently when switching from wifi to mobile and from mobile to wifi, but it also occasionally happens even when there is no network change. Manually stopping the connecting attempt and connecting again fixes the issue until the next time is occurs.

System Details:
Device: Xiaomi Mi 4
OS: MIMU Global 8.0 (Stable) based on Android 6
Weechat Version: 0.12-dev (nightly release on Google Play)

**Comment by Zopieux** [comment]
What connection method are you using? Plaintext? Weechat? Weechat SSL? SSH? Websocket? Websocket SSL?

I've already been subjected to this issue more than once. I guess there is some kind of race condition on the *network status changed* event.

**Comment by paddatrapper** [comment]
I'm using a plain connection

**Comment by paddatrapper** [comment]
If I'm active in the app it does not happen. Only occurs when weechat is in the background

**Comment by paddatrapper** [comment]
Seems MIMU 8.2.1 OS update fixes this issue
