### ISSUE TITLE
ability to show a tree view based on server->channel

### ISSUE THREAD

**Issue by adymitruk** [ubergeek42/weechat-android#324]
More people are using IRC to deal with the growing number of slack teams that are popping up everywhere. Each slack team has a #general and #random channel. After a couple teams are added, it's really hard to tell which team's general channel a person finds themselves in.

**Comment by Zopieux** [comment]
It's something I always wanted too. It's not *that* simple because we have options to hide non-channel buffers.

**Comment by oakkitten** [comment]
but don't you have the same problem in weechat itself? if you can fix the problem in weechat, it will be reflected in w-a. i personally prefer renaming buffers (/buffer set short_name #whatever)

**Comment by Zopieux** [comment]
I just pushed PR #327 to ease renaming buffers, following @oakkitten's tip.
@adymitruk, would that work for you?

**Comment by oakkitten** [comment]
you can use `autosort.py` for this
