### ISSUE TITLE
Cannot input in buffers whose full name contains spaces

### ISSUE THREAD

**Issue by symphorien** [ubergeek42/weechat-android#325]
I use the matrix script for weechat (https://github.com/torhve/weechat-matrix-protocol-script) which creates buffers that can contain spaces in their full name. They work fine from the ncurses interface, but when typing into those buffers from weechatdroid, the text is fully ignored.
When typing `Test` in a room (buffer) called `The Testing Room` I get those debug messages :
``` 
relay: recv from client 1/weechat/127.0.0.1: "input lua.The Testing Room Test"
relay: invalid buffer pointer in message: "input lua.The"
```
On a room called `Matrix` (without space), everything works just fine.
Is it possible for weechatdroid to use buffer pointers instead of buffer names ?

**Comment by oakkitten** [comment]
it is and it probably should be done https://github.com/glowing-bear/glowing-bear/blob/e5311084e177b41064bc5e946c3e6ee5c6c1c5e4/js/models.js#L507-L515

**Comment by Zopieux** [comment]
Already on it ;-)

**Comment by Zopieux** [comment]
![](http://i.imgur.com/WwnJiMC.png)

**Comment by symphorien** [comment]
Thanks for fixing it so quickly :)

**Comment by nheir** [comment]
658b12a669a0d2580048a21cc3144a2082cdab33 re-opens the issue with
https://github.com/ubergeek42/weechat-android/blob/4645c45ce0dce195572ae7b0d6389b20b21ddfcb/app/src/main/java/com/ubergeek42/WeechatAndroid/service/Events.java#L65-L71
