### ISSUE TITLE
SSL does not work for self-signed cert with IP address as Common Name

### ISSUE THREAD

**Issue by tnguyen14** [ubergeek42/weechat-android#330]
I followed the instructions here http://dev.weechat.org/post/2012/07/27/SSL-in-Relay-plugin to create an SSL relay, with the server's IP address as the Common Name.

However, when trying to connect through the app (I'm using the dev version), I get the error:

```
You are trying to connect to [ip address] but the certificate is only valid for the following hosts:

(none)
```

I am able to connect to the relay using a different client, i.e. glowing bear.

**Comment by ubergeek42** [comment]
An IP address as the common name is not valid. You can put it as the subject alternate name which will work. This is detailed in the guide here:
https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-WeeChat

**Comment by tnguyen14** [comment]
Ok that works. Thanks.
