### ISSUE TITLE
Missing SSH key exchange methods

### ISSUE THREAD

**Issue by emilhem** [ubergeek42/weechat-android#332]
weechat-android is missing some key exchange methods for SSH.

It could be my phone but when I'm using the terminal on my phone the connection succeeds.

The SSH server is set up with
```
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
```
The server log when weechat-android is trying to connect.
```
Jan 24 06:59:17 xxxxxx sshd[15154]: fatal: Unable to negotiate with x.x.x.x port xxxxx: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 [preauth]
```

**Comment by oakkitten** [comment]
i pasted your configuration in /etc/ssh/sshd_config and connected successfully with w-a. here's what logcat said (not sure why the lines are repeated):

    I/Jsch: SSH_MSG_KEXINIT received
    I/Jsch: kex: server: curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
    I/Jsch: kex: server: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
    I/Jsch: kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    I/Jsch: kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    I/Jsch: kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
    I/Jsch: kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
    I/Jsch: kex: server: none,zlib@openssh.com
    I/Jsch: kex: server: none,zlib@openssh.com
    I/Jsch: kex: server: 
    I/Jsch: kex: server: 
    I/Jsch: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
    I/Jsch: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
    I/Jsch: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
    I/Jsch: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
    I/Jsch: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
    I/Jsch: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
    I/Jsch: kex: client: none
    I/Jsch: kex: client: none
    I/Jsch: kex: client: 
    I/Jsch: kex: client: 
    I/Jsch: kex: server->client aes128-ctr hmac-sha2-256 none
    I/Jsch: kex: client->server aes128-ctr hmac-sha2-256 none

OpenSSH_6.7p1 Raspbian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016
WeechatAndroid 0.12 (current development version)

what are your versions? what does the logcat say?

**Comment by emilhem** [comment]
I can verify that this bug doesn't occur on the developer version but occurs on 0.11.
