### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by max13fr** [ubergeek42/weechat-android#333]
Hello,

I try to connect to my weechat relay :
- protocol weechat SSL
- port 9001
- firewall disabled & public ip
- correct password

When I show current connections with /relay, I can see my phone connection with 67 bytes received but 0 byte send (I think this is the issue).

On my phone, I have "connecting now" on task bar & after a while, I have "wrong password" error.

I tried to update weechat from 1.0 to 1.5, use weechat-android-devel and use plain text connection but the issue is still here.

Am I the only one with this issue ?

Thanks in advance,
Max

**Comment by oakkitten** [comment]
weechat doesn't give any reply if correct password has not been provided, so we assume that if weechat drops the connection that the password was wrong. if you type `/relay raw` in weechat, you should see something like 

    init password=hunter2,compression=zlib
    (version) info version

also make sure that if you type `/relay listrelay` you get something like 

    Listening on ports:
      port 9001, relay: ssl.weechat, IPv4, started on: Mon, 06 Feb 2017 10:00:56

perhaps look at logcat to see if there's any errors
also try glowing-bear to see if it can connect

if you can't resolve the issue you can find us on freenode's #weechat-android channel

**Comment by max13fr** [comment]
Hello,

Thanks for you answer, I found my mistake : 
port 9001, relai : ssl.irc.JN, IPv4, started on...

I used irc relay protocol instead of weechat relay protocol. Work like a charm with :
/relay add ssl.weechat 9001

Thanks for you help :)

Have a nice weekend,
Max
