### ISSUE TITLE
connection / ipv6 issues

### ISSUE THREAD

**Issue by NikkyAI** [ubergeek42/weechat-android#334]
i am trying to use multiple weechat relay clients
glowing-bear and weechat-android
i cannot connect with my phone to the relay from my home network (disabling wifi and using 4g works fine)
i guessed it was the fault of using the same ipv4 address so tried connecting to a ipv6-only address
but it fails resolving the address

is this a bug of weechat-android for not supporting ipv6 ?
or is ipv6 not supported in the weechat protocol ?

**Comment by Zopieux** [comment]
#255 & #260 related?

**Comment by oakkitten** [comment]
this sounds like the [nat hairpinning](https://github.com/ubergeek42/weechat-android/issues/238#issuecomment-155827341) issue

**Comment by NikkyAI** [comment]
i pinned it down to my ipv6 no longer working on my server.. no idea why and not that much time to figure out what broke

but that leaves me with only ipv4 connection so nat hairpinning is probably the cause

any way to work around it ?

**Comment by oakkitten** [comment]
there are no easy workarounds. i tried googling and asking folks and the best they came up with was buying a proper router or running your own dns service that does split dns. perhaps using some automation to alter `/etc/hosts` when in home network could do it.

i suppose we better add support for multiple addresses. although i still feel strongly that applications should not address the problem

**Comment by NikkyAI** [comment]
i don't think this is a limitation that my router could solve, but if you know how to configure routeros to handle this i would be very interested
but unless weechat can distinguish my devices i doubt anything is going to work, i think i can try using a ssh tunnel on the android app and connect locally, that did not work at all last time but i did never try to tunnel to that server before.. i guess its just disabled or such
will try next weekend

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
