### ISSUE TITLE
Feature request: Notification LED colour from nick

### ISSUE THREAD

**Issue by ollpu** [ubergeek42/weechat-android#336]
Just an idea: the notification LED could blink in the colour of the nick that caused the highlight. Is this even possible? It wouldn't be very useful either, but it could be a nice touch.

**Comment by oakkitten** [comment]
probably possible, but i think it's not the best idea. i suppose most people who have colored led choose to have different lights for different apps, and having multicolored notifications from a single app would be confusing. besides—cmiiw—we can have only one led color for a notification, so what should we do if we have multiple highlights in a notification?

**Comment by ollpu** [comment]
Of course it would be optional, as it really is a gimmick with possibly negative implications for the user. The colour should probably be determined by the latest highlight.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
