### ISSUE TITLE
Buffer filter for share menu

### ISSUE THREAD

**Issue by nyuszika7h** [ubergeek42/weechat-android#337]
Currently, there is no buffer filter box in the share menu, which may make it hard to find the desired buffer with a lot of buffers open. Also, if the buffer filter is active in the app, it will be applied to the share menu as well, impossible to turn off without going back to the app first. (Also, I think the filter should clear after swiping away the buffer list, at least add an option for that.)

**Comment by oakkitten** [comment]
this has been implemented
