### ISSUE TITLE
STATUSMSG prefix displayed incorrectly

### ISSUE THREAD

**Issue by nyuszika7h** [ubergeek42/weechat-android#340]
If you send a STATUSMSG (e.g. `/msg +#channel something` - need to be voiced/opped), others would see this in WeeChat:

```
-- Msg:+(someone): something
```

In weechat-android, incoming STATUSMSGs display as:

```
<--> Msg:+(someone): something
```

**Comment by Zopieux** [comment]
I beg to differ 😄 . Are you sure you're using the latest dev build?

![if this image does not load, blame Google](https://lh3.googleusercontent.com/DFOGOU5Dj1vRO1S6NrCskbith50BhW0szqE4HSfmbmuduYCJnHhSsNOQfMIXg05arcPEhTX5NjKIEUE=w1107-h771)

**Comment by nyuszika7h** [comment]
Yes, I'm using v0.12-dev (Jan 3), latest nightly in the Play Store.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ubergeek42** [comment]
@Zopieux, @nyuszika7h  do you have the setting "enclose nicks in <>" checked?

**Comment by nyuszika7h** [comment]
Yes, but it shouldn't enclose that prefix for STATUSMSGs, just like it doesn't for JOIN/MODE/PART/QUIT/etc.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
