### ISSUE TITLE
Option to show server buffers when filtering

### ISSUE THREAD

**Issue by nyuszika7h** [ubergeek42/weechat-android#341]
When I filter buffers and there are channels with the same name on different networks, it would be nice if the server buffers would still be displayed above the corresponding channels when filtering. Though this would only work if the channels are already organized below the server buffers in WeeChat, otherwise weechat-android would have to sort them manually, but I already have them sorted in WeeChat.

**Comment by oakkitten** [comment]
this has been implemented (e.g. try typing `.` there)
