### ISSUE TITLE
Breaks with Nougat update

### ISSUE THREAD

**Issue by m0ar** [ubergeek42/weechat-android#343]
Hi,

after updating to Nougat the application refuses to connect to my server. I have noticed many others having the same issues after upgrading. There are no configuration changes in neither the app nor server side for me.

On a fresh app start, the mascot grabs the balloon but nothing happens. When I press `Disconnect`, a quick popup with `Wrong password` is shown. On subsequent connection tries after this I get the following error popup in the app:

`Error: PortForwardingL: local port 127.0.0.1:22231 cannot be bound.`

I know it's not much to go by, but it's something. :tada:

**Comment by ubergeek42** [comment]
Are you using the nightly version? Give it a try if you aren't as there are
a number of fixes in it with regards to newer Android version compatiblity.

**Comment by m0ar** [comment]
@ubergeek42 Can confirm it works with the nightly! Thanks. I guess these fixes will be merged in the next release?

**Comment by Zopieux** [comment]
Thou Shalt Not Invoke the Release Demon. :rage:
