### ISSUE TITLE
'desync' relay command should be sent with a buffer name instead of a pointer to avoid crash

### ISSUE THREAD

**Issue by nyuszika7h** [ubergeek42/weechat-android#345]
I did `/filter toggle` in a channel, and later `/close` in a channel that I parted. Both of these crashed WeeChat because weechat-android sent an invalid pointer as argument to the `desync` relay command. According to @FlashCode, the buffer name should be sent instead (e.g. `irc.freenode.#weechat`). That way it won't crash if the buffer doesn't exist.

Backtraces: https://ptpb.pw/XO-b https://ptpb.pw/8naG

**Edit:** It also just happened while scrolling up the buffers bar in WeeChat with weechat-android connected, but not doing anything from there specifically. https://ptpb.pw/DFVr

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
