### ISSUE TITLE
Does is support elliptic curve certificates?

### ISSUE THREAD

**Issue by jannis-a** [ubergeek42/weechat-android#355]
Hi,

I recently tried to use WeeChat Android (WeeChat SSL as connection type) with me EC cert from Let's Encrypt instead of a self-signed RSA cert. But I can't connect with the app (WebSocket from the browser works).

`relay: TLS handshake failed for client 1/ssl.weechat/<ip>: error -12 A TLS fatal alert has been received.`

This is how I create the cert for WeeChat:

`cat {privkey,fullchain}.pem > .weechat/ssl/relay.pem`

Is the app missing support for EC certs or did I something wrong on cert creation?

**Comment by Zopieux** [comment]
You can check if your version of Android supports a specific ciphersuite using [this page](https://www.ssllabs.com/ssltest/clients.html).

**Comment by mrhanky17** [comment]
I'm on Android 7, so it should support EC certs?

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
