### ISSUE TITLE
Disconnecting causes relay connection to close with error in weechat due to race condition

### ISSUE THREAD

**Issue by sim642** [ubergeek42/weechat-android#365]
When disconnect button is pressed then the following happens:
1. `sendMessage("quit")` - adds the "quit" command to the out queue
2. connection is closed

The problem is that very often (possibly depending on connection type) the connection gets closed before the out queue thread has a chance to write and flush the "quit" command to weechat. This means that in weechat core buffer shows an error like
```
=!= relay: reading data on socket for client 1/weechat/127.0.0.1: error 84 (connection closed by peer)
```
as opposed to the client quiting gracefully. It can be confirmed with `/relay raw` that weechat does not receive the "quit" command in these cases due to the race condition between the threads handling the connection as described above.

Before closing the connection it should be made sure (by waiting) that the out queue has been all sent to ensure that weechat has been sent the "quit" command at all.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
