### ISSUE TITLE
When connection is lost, display a banner instead of disabling UI elements

### ISSUE THREAD

**Issue by yvan-sraka** [ubergeek42/weechat-android#366]
What do you think, when the internet connection is lost, to only block the send button, and not, as currently, the entire bottom bar and the ability to type a message? It's pretty annoying when you have a bad connection, for example in public transports, to constantly lose access to the keyboard.

**Comment by mhoran** [comment]
I agree, it's annoying, and happens a lot on my trip through the NYC transit system. On the other hand, I have the send button disabled, so this is the only way I know that I won't be able to send my message. We used to not disable the text box and I'd have dropped messages all the time, not realizing I sent when disconnected.

**Comment by oakkitten** [comment]
as mentioned in #339, we shouldn't be disabling the drawer either.

i think we should display e.g. a banner on top or a thin line over the bottom toolbar to indicate that there's no connectivity

**Comment by oakkitten** [comment]
this has been implemented. also now the drawer etc is not disabled either 870dc3c57141e49ff721cf5a98ed5d3b8ece0ad8
