### ISSUE TITLE
crashes on connect

### ISSUE THREAD

**Issue by nivex** [ubergeek42/weechat-android#367]
When connecting to my relay, the list of buffers is briefly displayed and then the app crashes. This does not happen all the time. It may be related to the contents (or lack thereof) in the weechat.core buffer, as sometimes I can /buffer clear or run a command in that buffer and it stops crashing for awhile.

I apologize for this lackluster bug report. I am a mere user and not an Android developer. This could well be related to some of the other crash issues in the queue.

**Comment by Zopieux** [comment]
Are you using [the latest development version](http://weechat-android.ubergeek42.com/)?

**Comment by nivex** [comment]
Was using 0.11 from Play Store. I have installed the dev version from the link provided. It connected up on the first go. Will give it a try for a couple days and see how it plays out.

**Comment by nivex** [comment]
dev version has been running with no problems since installation. Looking forward to seeing a new release.
