### ISSUE TITLE
Adaptive Icons

### ISSUE THREAD

**Issue by yvan-sraka** [ubergeek42/weechat-android#368]
Hello,

What do you think about using the new [Adaptive Icons](https://developer.android.com/preview/features/adaptive-icons.html) feature of Android O?

It would be really nice to see them implemented in Weechat Android! Can I help :wink:?

Thank you very much,

**Comment by Zopieux** [comment]
There is no background in the current weechat Android logo, it is a standalone shape. I don't see how this technique would apply.

**Comment by yvan-sraka** [comment]
I think a white background might be enough, that's what Google does for its apps.

**Comment by Zopieux** [comment]
Could work. Would enhance the logo readibility.

**Comment by oakkitten** [comment]
this has been implemented
