### ISSUE TITLE
Bad failure mode when Websocket path is not set properly

### ISSUE THREAD

**Issue by grantwwu** [ubergeek42/weechat-android#373]
I'm using 0.12-dev, installed through Google Play betas.

I have a websocket relay with nginx termination.

Symptoms:
If you don't set the WebSocket path to "weechat" (it's blank by default), it appears like the connection doesn't complete, and there are a variety of undesirable side effects.  It is non-obvious what the issue is.

This is what it looks like from the relay's side:

> relay: reading data on socket for client 3/weechat/127.0.0.1: error 11 (connection closed by peer)
relay: disconnected from client 3/weechat/127.0.0.1
relay: new client on port 9001: 3/weechat/127.0.0.1
relay: reading data on socket for client 3/weechat/127.0.0.1: error 11 (connection closed by peer)
relay: disconnected from client 3/weechat/127.0.0.1  
relay: new client on port 9001: 4/weechat/127.0.0.1
relay: reading data on socket for client 4/weechat/127.0.0.1: error 11 (connection closed by peer)
relay: disconnected from client 4/weechat/127.0.0.1
relay: new client on port 9001: 5/weechat/127.0.0.1
relay: reading data on socket for client 5/weechat/127.0.0.1: error 11 (connection closed by peer)
relay: disconnected from client 5/weechat/127.0.0.1
relay: new client on port 9001: 3/weechat/127.0.0.1

This is what it looks like from nginx's access.log:
> [13/Oct/2017:07:33:15 +0000] "GET / HTTP/1.1" 499 0 "-" "-"
[13/Oct/2017:07:33:30 +0000] "GET / HTTP/1.1" 499 0 "-" "-"
[13/Oct/2017:07:33:39 +0000] "init password=censored,compression=zlib" 400 182 "-" "-"
[13/Oct/2017:07:33:41 +0000] "init password=censored,compression=zlib" 400 182 "-" "-"
[13/Oct/2017:07:33:52 +0000] "init password=censored,compression=zlib" 400 182 "-" "-"
[13/Oct/2017:07:34:22 +0000] "init password=censored,compression=zlib" 400 182 "-" "-"

The password gets leaked into logs.  I wouldn't really call this a security issue, but it's not very hygienic.

I'd suggest making "weechat" the default websocket path.  Additionally, I'd hope that there is a better way of handling surfacing this failure mode to the user, but I'm not an expert on the protocols involved so I'm not sure how difficult this failure mode is to detect.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
