### ISSUE TITLE
App running in background persistent notification

### ISSUE THREAD

**Issue by Phyks** [ubergeek42/weechat-android#375]
Hi,

Starting from Android 8.0 (Oreo), there is [a persistent notification](https://9to5google.com/2017/09/06/how-to-remove-android-oreo-background-app-notification/) for apps running in background. 

There are some ways to remove this notification with [some tricks](https://github.com/iboalali/sysnotifsnooze).

I do not know much about Android dev, but Weechat for Android is the only app I have which is displaying this persistent notification. Apps such as Whatsapp do not display it for example. Then, I am wondering if there is anything that could be done from the app side to remove this persistent notification.

Thanks, and sorry if this is not really an issue and you cannot do anything about it :/

**Comment by mhoran** [comment]
Yeah, this is pretty annoying. I've set the system preference for this notification to low priority, so at least the icon goes away. But based on how weechat-android is architected, I don't think there's any way for us to make this go away permanently. We'd have to move away from the background service that we use today and that would ultimately reduce the utility of the program (for push highlights, etc.)

**Comment by Phyks** [comment]
Thanks for the quick reply on this! 

> But based on how weechat-android is architected, I don't think there's any way for us to make this go away permanently. We'd have to move away from the background service that we use today and that would ultimately reduce the utility of the program (for push highlights, etc.)

How does it work for similar other apps? Whatsapp for instance do not display such a notification, but they do fetch messages in the background somehow.

**Comment by mhoran** [comment]
They're using GCM (or whatever the name of that is this week), which relies on Google's servers to push out notifications. We run a client that keeps a persistent connection to the weechat relay running on your host. It doesn't rely on GCM at all.

**Comment by Phyks** [comment]
Erf, definitely I'd rather not see Weechat for Android having a dependency on GCM :/ If anything can be done from the app side, that would be truly awesome. Otherwise, I guess adding an entry to the FAQ would be a good option to avoid duplicates of this issue in the future :)

Thanks for all the work on the app!

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
