### ISSUE TITLE
High battery usage with current nightly build

### ISSUE THREAD

**Issue by jlu5** [ubergeek42/weechat-android#378]
Hi,

With the current nightly build (v0.11-117-gfcf9439), I've recently seen extremely high CPU usage on two devices running Android 7.1 and 8.0. Settings reports weechat-android using 53% versus the next highest program (Chrome at ~8%). Hopefully something can be done, though I'm not sure where to start debugging this issue.

For reference, I'm using WeeChat SSL on a WeeChat 1.9.1 host.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
