### ISSUE TITLE
OrBot - Tor socks5 option

### ISSUE THREAD

**Issue by nixbits** [ubergeek42/weechat-android#380]
Great app but is missing out on socks5 proxy options to be able to use orbot.
This implementation would be greatly appreciated.

**Comment by peterrus** [comment]
You can use orbot's vpn mode as a workaround for now!

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
