### ISSUE TITLE
Rejected hostkey

### ISSUE THREAD

**Issue by drym3r** [ubergeek42/weechat-android#386]
Hi

Which format does the hostkey need to be? I've tried with both the output of `ssh-keyscan -t rsa $server` and `ssh-keyscan $server`, but still can't connect. 

I'm using latest version.

Thanks for your work.

**Comment by ChinnoDog** [comment]
I get this same thing. I was on nightly build and fell back to stable. I've tried disabling all HostKey lines in my sshd_config besides my RSA key. ssh-keyscan only returns the rsa key now and I paste it in without the comment provided in the ssh-keyscan output. The error is always "HostKey has been changed: <hostname>"

**Comment by oakkitten** [comment]
does putting in `ssh-keyscan host 2>/dev/null` make a difference?

**Comment by ChinnoDog** [comment]
I figured it out, and I feel stupid now. I was copying the key out of ConnectBot. The copy function there only supports block mode which includes extra carriage returns. I removed the carriage returns and now it works.
