### ISSUE TITLE
App crashes on disconnect

### ISSUE THREAD

**Issue by Ketrel** [ubergeek42/weechat-android#392]
Any time I try to disconnect, the app crashes and restarts (in a connected state).

I'm using 0.13 and using Weechat ssl as the connection type (non-standard port)

**Comment by Ketrel** [comment]
I can't seem to produce this reliably.

It seems like it's either related to having X amount of buffers or more open, or possibly
the irc.look.notice_as_pv set to always while having notices from non-existant or offline users.

**Comment by oakkitten** [comment]
it would help a lot to have the log information at the time of the crash. here's [a rough instuction](https://android.stackexchange.com/a/33217/122152) 😬

**Comment by Ketrel** [comment]
I'm trying my best to get it to happen again.
I had rebooted my server (which is where weechat runs) and cleared cache + data on the app, and I haven't been able to replicate it.  (Prior, just clearing cache+data didn't help).

I guess for now, this could be closed as can't reproduce.  If it happens again, I'll get a logcat of it.
