### ISSUE TITLE
Possible to hide action bar on-demand?

### ISSUE THREAD

**Issue by slackhead** [ubergeek42/weechat-android#393]
I don't know if this is possible already, but I'd like it to be an enhancement if not.

I have a very small screen so I'd like a way of turning off the action bar when I don't need it. Perhaps have a feature where you tap on the centre of the screen and have it show/hide?

Perhaps another thing may be to make it smaller. At the moment it seems to be taking 3 lines of text. I have a lot of space above and below the actual text, which makes it larger than I think is necesary.

**Comment by slackhead** [comment]
Here's a screenshot to show what I mean:

http://www.r0t.uk/sshots/weechat.png

There's quite a lot of spare space in the botton bar too.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
