### ISSUE TITLE
Play store says my device is incompatible with the nightly version (Pixel XL, Android 9)

### ISSUE THREAD

**Issue by ashkitten** [ubergeek42/weechat-android#395]

**Comment by noteventhrice** [comment]
I'm running nightly on Pixel 1, Android 9. While there are no crashes, it cannot connect to any of my relays.

**Comment by ashkitten** [comment]
@noteventhrice your comment is unrelated to this issue, but please make sure you are running the latest nightly version (august 4 build) where i have fixed a bug which would cause the app to silently fail to connect to any ssl relay using a self-signed certificate. also, your certificate must use dns subject alternative name in recent android versions. [as i have updated the wiki to point out](https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-WeeChat#when-connecting-i-see-the-error-invalid-hostname). if this does not solve your issue, you can open a new one for it.

**Comment by mhoran** [comment]
Fixed. Thanks!
