### ISSUE TITLE
Cert error in nightly build

### ISSUE THREAD

**Issue by erikpi** [ubergeek42/weechat-android#399]
![image](https://user-images.githubusercontent.com/3598059/45627088-6443f680-ba91-11e8-8f54-6801c6290e5f.png)

How can I fix this error? 
Using weechat ssl + nightly build.

It works fine in the regular app, but it has started to re-render every 30sec or so which is super annoying.

**Comment by Zopieux** [comment]
Follow [the wiki](https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-Weechat#create-a-self-signed-certificate) to create the correct self-signed certificate, including the hostname.

**Comment by erikpi** [comment]
Thanks, it fixed it! Nightly build seems awesome =)
