### ISSUE TITLE
Can't whitelist own certificate

### ISSUE THREAD

**Issue by mtakala** [ubergeek42/weechat-android#401]
Hello

Official update via Google Play turned up today. 

It did not connect. 

There is just a popup that says
"Invalid hostname
You are trying to connect to (server address) but the certificate is for (my name)." 

It is a self signed certificate. There is no way to whitelist it anymore. 

Please add that option.

**Comment by mtakala** [comment]
Ah, nevermind, there is instructions to create a new certificate with the hostname on the wiki.

**Comment by Zopieux** [comment]
:smile:
