### ISSUE TITLE
Invalid Host

### ISSUE THREAD

**Issue by arnauldb** [ubergeek42/weechat-android#404]
Hello,

when trying to connect to my weechat relay I have an error message saying: 

```
Invalid Host
You are trying to connect to xxx.xxx.... but the certificate is only valid for these hosts: 
(none)
```

When I use Glowing Bear, to be able to connect, I have to visit first in the browser https://xx.xxx.250.120:8000/weechat and only after I can connect to my weechat relay.

But how can I do that in weechat-android ?

Thank you.

**Comment by jspricke** [comment]
https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-Weechat#troubleshooting

**Comment by arnauldb** [comment]
> https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-Weechat#troubleshooting

Thank you jspricke, it is working now.
