### ISSUE TITLE
Reintroduce title in buffer list?

### ISSUE THREAD

**Issue by insomniacslk** [ubergeek42/weechat-android#405]
Recently the buffer title was removed from the buffer list, and moved to the top of the scrollback.
However I found very useful the option to show the title in the buffer list, and I would like to know if it can be reintroduced.

Why? Having the title in the buffer list is very useful when using, for example, wee-slack to connect to Slack teams. Slack teams have a default #general channel, and it's now difficult to know which channel belongs to which team without opening it.
I'd be happy to help with testing - I am already enrolled in the beta testing program on the Play Store.
Thanks!

**Comment by oakkitten** [comment]
this particular issue can be solved by renaming the buffer in weechat, try `/buffer set short_name 🐱`, to persist, use script `buffer_autoset.py`: `/set buffer_autoset.buffer.irc.freenode.#channel.short_name "🐱"`

but— if this issue gets enough votes, we can add it back
