### ISSUE TITLE
"Hot message" notifications keep repeating since v0.13

### ISSUE THREAD

**Issue by LeCoyote** [ubergeek42/weechat-android#407]
Steps to reproduce:
1. receive a "hot message" (eg. a highlight)
2. go to buffer in weechat android and read message: notification goes away
3. watch as the same notification for the same message pops up again after a while. Conditions for the notification popup to reappear are unclear: time? "x" new messages in buffer? I couldn't determine that precisely.
The only way to make the notifications go completely away is to acknowledge the hot messages directly in the weechat client itself.
I don't remember this from 0.12 or previous versions, but I might be wrong. I'll look for an older apk if I can.

**Comment by LeCoyote** [comment]
I have just the buff reverted to 0.12-git and the problem went away. In other terms, with 0.12-git, when I click the bell icon to check the various hot messages, weechat-android considers them "read" and never show them again, even though the actual weechat client on the other end has them marked as unread (ie. I do not synchronise the buffer read status)

**Comment by oakkitten** [comment]
what is your weechat version?

**Comment by LeCoyote** [comment]
1.6-1 from debian stretch

**Comment by oakkitten** [comment]
we are synchronizing number of highlights/other messages once 5 minutes. the numbers are taken from weechat's hotlist, and hotlist data does not quite completely correspond to stuff contained in the buffer. moreover, to see if the buffer has been read in weechat, we use a pointer to the last read line, which can disappear if that line is removed from the buffer. also, if a buffer was read in weechat, that highlight can reappear in weechat-android. to sum it up, you can get notifications for already read messages, if:

- something alters hotlist without altering the buffer in the same way, such as a script or a [weechat bug](https://github.com/weechat/weechat/issues/1277)
- buffer is open in weechat for a long time and all messages in the buffer become unread
- between w-a's synchronizations, you read the buffer in weechat, navigate out of it in weechat, receive a highlight in that buffer, read it in w-a, and navigate off the buffer in w-a

please check that your hotlist doesn't have weird numbers. if all seems right, and you still get this often, please contact us on freenode's #weechat-android

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
