### ISSUE TITLE
Tab autocompletion does not work

### ISSUE THREAD

**Issue by Forceflow** [ubergeek42/weechat-android#410]
Using the latest weechat-android version (0.13-dev) on a OnePlus 5T and weechat 2.3 on a VPS, I cannot get tab autocompletion to work in the app.

Connection (plain connection) works fine, I can switch buffers and execute commands, but the builtin tab button in the app does not autocomplete or suggest anything. The button registers a press (bg color changes), but nothing happens.

When I just use weechat through ssh in a terminal, (not through the Android app) tab completion does work.

Any way to debug this?

**Comment by Forceflow** [comment]
Weechat-android 0.13-12-g4aad743 (tried stable version too, same problem).


WeeChat 2.3 Copyright (C) 2003-2018, compiled on Oct 21 2018 13:22:10

**Comment by oakkitten** [comment]
i can't reproduce the problem on these versions. please try with a default config weechat (`$ weechat -d /tmp/foo`). also, did you at some point not have the problem? if you didn't, what changed? also, if you have other devices, are those also affected? what os and architecture you are running weechat on?

the code that's responsible for tab completion hasn't changed in a long while, and i don't remember anyone having issues with it.

p.s. you can find us on freenode's #weechat-android

**Comment by Forceflow** [comment]
Oki doki. 

- On a new weechat instance, I did `/relay add weechat 8001`. Port 8001 is open in my firewall (UFW).
- I added a password with `/set relay.network.password "test"`
- Connected using the Android app (still version 0.13-12-g4aad743), using "plain connection"
- Weechat buffer loads, connection worked
- Tried typing /h (for help), and hitting tab for autocompletion/suggestions
- Nothing :(

It has never worked for me, unfortunately. I only have this Android device to test on. I'm running weechat on Ubuntu Cosmic 18.10 - My kernel version is 4.18.0-10-generic, on a 64-bit architecture. The machine is a VPS hosted at a provider (Vultr).

I would be happy to debug further.

**Comment by Forceflow** [comment]
> oh uhm, at the moment tab completion currently only works for nicknames and only on buffers that have them, like irc channels. no command completion. this is done on the client side so no 1:1 correspondence to what weechat is doing anyway

Aha - then I apologize for my confusion, I thought it was supposed to complete commands as well. Mystery solved :) Closing, and sorry for the little timewasting!
