### ISSUE TITLE
Android P no longer verifies certificates without SAN, error messages should reflect this

### ISSUE THREAD

**Issue by oakkitten** [ubergeek42/weechat-android#417]
[changelog](https://developer.android.com/about/versions/pie/android-9.0-changes-all#certificate-common-name)

**Comment by oakkitten** [comment]
also worth trying figuring out why 0.13-0-gdeca889 (deca889) won't connect to a proper self-signed certificate

**Comment by alarig** [comment]
Plus, it seems that android now requiers a valid certificate. I added a SAN to my certificate but nothing changed, I signed it with certbot instead of my own CA, it worked.

**Comment by oakkitten** [comment]
@alarig we definitely support self-signed certificates. are you still having this problem on 1.0? i'm using `self-signed.badssl.com` to test things
