### ISSUE TITLE
[feature request] Bidi support

### ISSUE THREAD

**Issue by elig0n** [ubergeek42/weechat-android#418]
In weechat there is a python script called biditext.py which makes bidirectional languages appear in their right direction (right to left).
It of-course doesn't affect relay which shows the text in the default, wrong direction.

**Comment by oakkitten** [comment]
sorry for not getting back to this sooner.

i tried right to left text in the app and it appears mostly fine. if you are having problems with it, could you please provide screenshots with bad text rendering, as well as explain how it should look?

**Comment by elig0n** [comment]
seems to be alright now...
