### ISSUE TITLE
application crashes after connecting to relay

### ISSUE THREAD

**Issue by ashinkarov** [ubergeek42/weechat-android#421]
My setup that I have been successfully using for ~2 years sopped working today.
I have a server with a running weechat with a relay opened on port 8001:
```
/relay add weechat 8001
```
On my phone I have an ssh tunnel that forwards 8001 port to localhost:
```sh
ssh -L 8001:localhost:8001 <myserver>
```
In the app I connect to localhost via `WebSocket` to localhost on port 8001.  (Plain connection never worked for me, not sure why).

Now, since today, whenever the app gets connected to the weechat on my server, it immediately crashes.  I fetched the log:
```
10-21 16:46:53.070 19404 19971 E AndroidRuntime: FATAL EXCEPTION: r3
10-21 16:46:53.070 19404 19971 E AndroidRuntime: Process: com.ubergeek42.WeechatAndroid, PID: 19404
10-21 16:46:53.070 19404 19971 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
10-21 16:46:53.070 19404 19971 E AndroidRuntime: 	at com.ubergeek42.weechat.relay.protocol.Data.getHdata(Data.java:173)
10-21 16:46:53.070 19404 19971 E AndroidRuntime: 	at com.ubergeek42.weechat.relay.protocol.Data.getObject(Data.java:273)
10-21 16:46:53.070 19404 19971 E AndroidRuntime: 	at com.ubergeek42.weechat.relay.RelayMessage.<init>(RelayMessage.java:2238)
10-21 16:46:53.070 19404 19971 E AndroidRuntime: 	at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$300(AbstractConnection.java:2147)
10-21 16:46:53.070 19404 19971 E AndroidRuntime: 	at com.ubergeek42.weechat.relay.connection.AbstractConnection$2.run(AbstractConnection.java:83)
10-21 16:46:53.070 19404 19971 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
10-21 16:46:53.074   950  2433 W ActivityManager:   Force finishing activity com.ubergeek42.WeechatAndroid/.WeechatActivity
10-21 16:46:53.092 19404 19971 I Process : Sending signal. PID: 19404 SIG: 9
```

In the weechat instance on my server I can see that:
```
18:46 relay: new client on port 8001: 1/weechat/127.0.0.1
18:46 =!= relay: reading data on socket for client 1/weechat/127.0.0.1: error 11 (connection closed by peer)
18:46 relay: disconnected from client 1/weechat/127.0.0.1
```

I use LineageOS 16 (Android 9), Weechat-Android version 0.12-git (installed from f-droid) build-id v0.11-83-g9426987.

What surprises me is that it *suddently* stopped working, even though I didn't change much in my confiiguration. Any ideas?

**Comment by oakkitten** [comment]
please try 0.13 or perhaps [this](http://weechat-android.ubergeek42.com/weechat-connection-refactor-streams-0b83b7c.apk)

**Comment by ashinkarov** [comment]
Oh, 0.13 seem to work.

However, note that in F-droid, 0.13 is marked incompatible for my system, and doesn't show up; that is why I have been using 0.12-git.  Is it really incompatible or the compatibility spec is unnecessarily too strict?

Also, any insights on why it suddenly stopped working?  Should I be worried about the server misbehaving, or is it one of those bugs that can show up completely unexpectedly?

**Comment by oakkitten** [comment]
did you update weechat recently? sounds like #302

as for f-droid, i'm not using it and iirc it's curated by some third party; otherwise we have no special requirements save android 5 or so

**Comment by ashinkarov** [comment]
0.13 is working fine since the update, so I am closing the issue.  Thanks for your help!
