### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by isene** [ubergeek42/weechat-android#424]
Issue applies to both the normal app and the nightly build.

Server IP is set correctly in the app. Port is set correctly (8001) in the app and in weechat relay on remote server with the port open in the firewall. Password is tripple-checked to be correct in the apps and in weechat.

Upon pressing Connect in the apps, it immediately shows "Error: Connection refused".

Didn't use the app for a few months - didn't change anything in the app or on the server. The app worked fine last time I used it (summer). Getting back to centralizing all my messaging in weechat, I now suddenly discovered it refuses to connect.

What else to check?

**Comment by isene** [comment]
I accidentally checked the app using 4G instead of the wifi at home. It seems the issue could be with my home router - But using 4G it now says "Error: Connection reset by peer".

**Comment by oakkitten** [comment]
has the issue been resolved?
