### ISSUE TITLE
New launcher icon

### ISSUE THREAD

**Issue by oakkitten** [ubergeek42/weechat-android#428]
as of android q my grand idea of having a choice of the application icon came to a bitter end:

> As of Android 10 (API level 29), the Android Sharesheet will only use icons set in the manifest on your application tag. Icons set on intent-filter and activity tags will be ignored. -- https://developer.android.com/training/sharing/receive#sharing-shortcuts-api

therefore i propose making the alternative icon permanent. here are my arguments:

* the original icon is simply... bad. the top bar doesn't really represent anything, and the gradient doesn't go in line with android design
* the round variant of the original icon is still not good—it's using green and blue which are not found in the app
* it kind of implies that weechat-android *is* weechat. different applications should probably use different icons (and names!), even if one is an interface to another. e.g. glowing-bear, irssi connectbot, clients for twitter, reddit, etc.
* the new icon uses the kitty which is found in the application, as well as the colors. the icon looks good^Wawesome if i do say so myself and doesn't feel out of place in the recent app list
* pretty please? 🥺

trust me, it grows on you. here it is, by the way. it is adaptive and works well across all launchers: 
![ic_launcher_kitty](https://user-images.githubusercontent.com/1710718/72234372-981b2780-35c4-11ea-9381-e88d655bedb2.png)

**Comment by mhoran** [comment]
Our branding is weechat-android. That's why we use the WeeChat icon. I have done the same for weechatRN. I don't think it's appropriate to change the icon at this point. We should be consistent with the WeeChat branding. This would be quite jarring to anyone who is not familiar with this issue and hasn't followed the conversation. In addition, the icon does not relate to the WeeChat icon in any way. Personally, I would be quite confused by the icon change; I'm sure others would be as well.

**Comment by oakkitten** [comment]
it's kind of the other way around, the reason we have ~weechat-android~ WeeChat “branding” is because we are using WeeChat's logo. if there's any branding that ~WeeChat~ weechat-android is known for, it's the kitty. we shouldn't be consistent with WeeChat branding as we are not WeeChat, we should be consistent with weechat-android branding instead.

> In addition, the icon does not relate to the WeeChat icon in any way.

this is a good thing, isn't it?

> Personally, I would be quite confused by the icon change; I'm sure others would be as well.

rebrandings happen and often these are pretty drastic. the biggest problem with these is the loss of recognition which is not an issue for us at all—it's not like we can lose our market share.

**Comment by mhoran** [comment]
> it's kind of the other way around, the reason we have weechat-android WeeChat “branding” is because we are using WeeChat's logo. if there's any branding that WeeChat weechat-android is known for, it's the kitty. we shouldn't be consistent with WeeChat branding as we are not WeeChat, we should be consistent with weechat-android branding instead.

You know my thoughts on the kitty related branding. Regardless, the name of our app is weechat-android, not something completely different like Glowing Bear. The branding has been consistent in the past with WeeChat itself, in keeping with this. I think unless the app is renamed, it should stay more or less consistent with WeeChat.
