### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by Tigge** [ubergeek42/weechat-android#435]
I'm tunneling over SSH, then relaying in to localhost. From the server logs, it connects fine to ssh, fine to relay, but then directly disconnects and displays "Error: Connection reset".

Are there any logs I can look at or provide to help debug this?

**Comment by oakkitten** [comment]
what's your version? (Settings → About)

does the latest master work ok for you?

you can view the logs using [adb](https://developer.android.com/studio/command-line/adb) (or Android Studio) [logcat](https://developer.android.com/studio/command-line/logcat)

**Comment by Tigge** [comment]
> what's your version? (Settings → About)

0.14-dev (v0.13-126-g4f1a577)

> does the latest master work ok for you?

Latest master does indeed seem to work! A question regarding that. The README mentions that "Nightly builds are automatically made after every commit and are available as an apk download and on Google Play", but the play versions seems to be lagging behind a bit. Is that expected?

> you can view the logs using [adb](https://developer.android.com/studio/command-line/adb) (or Android Studio) [logcat](https://developer.android.com/studio/command-line/logcat)

I've updated now so I'll skip this for now.

**Comment by oakkitten** [comment]
aight i'll close this then, thanks

> but the play versions seems to be lagging behind a bit

the builds are made and pushed using travis and the script that pushes apks to play store broke as google deprecated older apis. i suppose we'll have to wait until @ubergeek42 fixes it or at least okays a fix
