### ISSUE TITLE
Allow for tab-complete on nicks to match inside strings and not only at the beginning

### ISSUE THREAD

**Issue by Porkepix** [ubergeek42/weechat-android#448]
Currently, tab-complete for nicknames only look for matches from the beginning of the nickname.
It would be better to be able, as WeeChat is, to match as a substring of nicknames, ie. if any nick contains the string we're trying to complete, wherever is it in the string.

**Comment by oakkitten** [comment]
It would be nice to make use of the new `completion` relay command. Meanwhile, perhaps it could be useful to hardcode characters that should be ignored while completing nicks. ``[]`_-^@`` is the default set, defined in `weechat.completion.nick_ignore_chars`

**Comment by oakkitten** [comment]
closing in favor of the linked issue
