### ISSUE TITLE
Play Store release is very old

### ISSUE THREAD

**Issue by legooolas** [ubergeek42/weechat-android#451]
The latest "nightly" on the Play Store appears to be quite old, as the version number shown in Settings->About is v0.13-13-g4645c45.  The "App Info" on the play store says that the last update to this was 26 Dec 2018.

Please could this be updated, and perhaps also the release version be updated to the latest tagged release?

If the recommended method is via F-Droid or side-loaded apk then the Play Store releases should either be removed or updated to say to use an alternative and where to get it from.

  Many thanks!

**Comment by oakkitten** [comment]
we are experiencing some technical difficulties with play store releases. this issues might or might not be resolved. i removed links to play store from the readme for now

**Comment by elig0n** [comment]
can you update store description to imply this ?

**Comment by oakkitten** [comment]
as it turns out, i can! put a warning there.

**Comment by oakkitten** [comment]
as of today, [nightly releases on Play Store](https://play.google.com/store/apps/details?id=com.ubergeek42.WeechatAndroid.dev) are back in town 

(should update metadata)

**Comment by oakkitten** [comment]
i unlisted the main app and updated the metadata for the nigthly listing. i guess it's the main listing now
