### ISSUE TITLE
junk text when both foreground and background color are provided

### ISSUE THREAD

**Issue by jiggie42** [ubergeek42/weechat-android#452]
IRC color formatting shows junk text when both colors are provided

To reproduce:
send ASCII character 0x04 and then "00,04test" for "test" in white text with a red background. this displays correctly in console WeeChat, but displays wrong in weechat-android v0.13-13-g4645c45 as well as v0.13-12-g4aad743

![test text](https://user-images.githubusercontent.com/9276385/86528773-4a97bd00-be79-11ea-9b0c-5f00a3de4f4a.png)

**Comment by jiggie42** [comment]
similar issue still occurs when specifying foreground and background with IRC's reverse formatting character ASCII 0x16

**Comment by oakkitten** [comment]
sounds like a duplicate of #420

**Comment by jiggie42** [comment]
Thanks for the quick response :-)
It looks like a similar issue to me, but I'm experiencing it on the latest released versions
Is this something that's been fixed by version 0.14? I'd be happy to try it out
weechat 2.8 btw

**Comment by jiggie42** [comment]
sooo I had an issue with f-droid, the problem IS FIXED WITH 14.1
thanks!  👍
