### ISSUE TITLE
Get back to more discreet vibrations, or allow user to control how strong it performs

### ISSUE THREAD

**Issue by Porkepix** [ubergeek42/weechat-android#458]
Back to versions `0.13` and earlier, notification vibrations used to be much more discreet. With more recent versions, it became much much stronger ones (old ones, if I remember correctly, was a single light one similar to the one of emails, it's now two strong ones, similar to SMS).

It would be better I think to get back to the previous kind of vibration or, maybe even better, let user pick which kind of vibration they want.

**Comment by oakkitten** [comment]
vibration is a property of notification channels now. we can initialize it with a pattern, but android doesn't allow editing notification channels after. we would have to [delete](https://developer.android.com/reference/android/app/NotificationManager.html#deleteNotificationChannel(java.lang.String)) and create a new notification channel for that each time it's edited. so we'd need a mechanism for that.

also we'd need a place to display the setting. this will require having a whole [new activity](https://stackoverflow.com/questions/46422997/android-notification-channel-link-from-system-settings-to-app-settings).

alternatively, we could hardcode some pattern. this would require users to manually reset app data on upgrade, though
