### ISSUE TITLE
File sharing

### ISSUE THREAD

**Issue by oakkitten** [ubergeek42/weechat-android#459]
i've been toying with file sharing a bit, this is what i got so far (click for video)

[![demo](https://i.imgur.com/kBeHjJQ.png)](https://i.imgur.com/xrgr45h.mp4)

how it works 

* `ShareTextActivity` receives `SEND` and `SEND_MULTIPLE` request for all data types

* it forwards it to the main activity, trying to keep URI permissions

* using Glide, scaled down images are loaded asynchronously; if no image is available, a fake one is made using the file name

* these are simply put into the input field. they act like single-letter words, you select and delete them easily from there

* if any images are in the input field, the send button changes to upload button

* upon pressing it, images are asynchronously uploaded. upload button changes to cancel button; progress indicator shows around it. when the file is 100% uploaded, it changes to indeterminate progress (rotating dot) while we are waiting for server response.

  the progress here is shown as a cumulative percentage of all *currently* uploading files for the current buffer. e.g. (file A transferred + file B transferred) / (file A size + file B size). when file B is finished, this becomes (file A transferred / file A size). this approach is easy as we don't have to deal with failed uploads, but it can sometimes lead to the progress going backwards

  if any images are added to the input while upload is in progress, they are just sit there. if any images are deleted, however, uploads for them stop

* upon success, images change to respective HTTP URIs. upon failure, a toast is shown

* if all images are uploaded, or deleted from the input, the upload cancel button changes back to send. if all pending uploads are done, but some images failed to load, or more were added, it changes back to upload button

how uploading works currently:

* when an upload for an uri is started, and there's already another one active for the same uri, current upload is attached to the existing one

* media type is determined from the uri using content resolver

* file name is determined in the following way: 
  * it's read from `OpenableColumns.DISPLAY_NAME`, or last uri segment, or set to "unknown"
  * if there's no `.` in the name, an extension is added using media type (`getExtensionFromMimeType`), or, if media type is not determined, ".bin" is added

* a wake lock is obtained

* a stream is opened for the uri and it's uploaded via HTTP POST using the determined media type and file name. user will supply:

  * upload uri (`https://example.com/`)
  * name of the file form field (`file`)
  * optionally, additional headers
  * optionally, basic auth credentials

  this is roughly equivalent to:

  `$ curl --user user:pass --header "Additional: Header" --form file=@filename.ext https://example.com/`

questions:

  * in the video you can see a notification icon displayed when an upload is active. at the time, it's a simple progress bar that mirrors the behavior of in-app ui. it's a part of foreground service.

    it's really only useful as an indicator that something is happening, and a way to stop uploads without opening the app. i'm not sure if we need it at all. remove it?

  * how do we cache results? only cache them in memory, or use a database? in either case, for how long should we consider results valid? should this perhaps be user-configurable?

  * should there be ui for picking files? (📎 button)

  * should there be ui for previously uploaded files (cache)?

**Comment by oakkitten** [comment]
note to self: on branch upload:

    java.lang.AssertionError: Actual must be equal to FETCHING (Actual: INIT)
        at com.ubergeek42.WeechatAndroid.utils.Assert$A.fail(Assert.java:20)
        at com.ubergeek42.WeechatAndroid.utils.Assert$A.isEqualTo(Assert.java:47)
        at com.ubergeek42.WeechatAndroid.relay.Lines.addFirst(Lines.java:76)

**Comment by Zopieux** [comment]
> indicator that something is happening, and a way to stop uploads without opening the app. i'm not sure if we need it at all. remove it?

Yes. I don't think you need async feedback for this. You're not uploading a 300MB video.

> how do we cache results? only cache them in memory, or use a database?

What does "results" mean? I don't see anything that would benefit from caching here. Upload, put URL in edit widget, be done.

> should there be ui for picking files?

Isn't the built-in Android multi file pick UI good enough?

>should there be ui for previously uploaded files (cache)?

Ah this is what you meant by cache. I don't think it's necessary. I'd argue image upload is fire-and-forget.

**Comment by oakkitten** [comment]
whether or not the built-in picker is good enough, atm there's no way to open it from the app

and caching is very much needed so that we don't upload the same file several times in case the user decides to share it twice

> Ah this is what you meant by cache. I don't think it's necessary. I'd argue image upload is fire-and-forget.

the thing is, sometimes you do, in fact, forget where that one image came from. i've been using a third-party app with a similar upload mechanism and while rarely but i did use its history feature.

otoh we already have history of sent messages, which is almost the same thing, so this is not a big deal

**Comment by Zopieux** [comment]
I'd say let's start without. It's already going to be a huge improvement over status quo.

**Comment by syyyr** [comment]
Hi,
I have some feedback on this:
1) Imgur backend. I know that the feature (as it is right now) is supposed to work generally (through a curl-like command), and while I would probably figure out how to set everything up, I would definitely be glad with a more no-config setup (similar to Glowing Bear). 
2) I'd definitely like there to be an in-app button/picker to be present in the app. My current "work"flow is:
a. (optional) use weechat-android to chat (before step b)
b. find some image that I want to send to someone, download it
c. switch to the app, look at messages (maybe I want to write something before I post?) then, write: "hey, look at this", then press the upload button, choose my image and then the link appears inside my message (and also it's a pretty "android" way of doing things).

I would also like the current "share" functionality to be there as well, because maybe I don't want to download and look at messages.

This experience is coming from using Glowing Bear and also #463. On PC, it is very flexible. Especially, it reacts to CTRL-V inside the message bar which automatically triggers the imgur upload. I know phones work differently, but I would like for this flexibility to be the same, so that's why I'm proposing the in-app button/picker feature.

**Comment by oakkitten** [comment]
why do you need it to be imgur? if you use a service such as x0.at or 0x0.st, you can share any kind of files, including videos, and these are easy to set up. also you can share huge files

if you absolutely need imgur, you can configure it like this:

* Upload URL: `https://api.imgur.com/3/image.xml`
* Form field name: `image`
* Regex: `https://i.imgur.com/\w+\.\w+`
* Additional headers: `Authorization: Client-ID <your client id>`

we are considering a file picker button as well, but, as the built-in pickers generally suck, we decided to postpone that until we find or implement a decent custom one, or resolve this in some other way.

**Comment by syyyr** [comment]
I don't need it to be Imgur. What I'm suggesting is creating custom built-in APIs that will work with imgur or some other services out of the box. Like I said, I'm coming from Glowing Bear: it allows to upload images with no configuration just like that, with ctrl-v. No configuration. I was wondering if it would be possible for weechat-android to upload images to some sort of an image uploading service by itself, with no configuration.

Side note: I see that this issue is called "File sharing". My usecase is always image sharing, so I base my experience on that. Also, the version I posted in my separate issue uses an image picker, which seems to work the same as in other apps, where images are picked.

**Comment by oakkitten** [comment]
while this doesn't work out of the box, it's easy enough to configure one of the services. for the regular upload services such as [x0](https://github.com/Rouji/single_php_filehost), you only have to set upload url (e.g. `https://yourwebsite.com/`). i think it is reasonable to require the user to do this much.

i have a cat and so i share a lot of pictures and videos of the said cat. so it better work for videos as well :p

i don't really have apps that use the default image picker. whatsapp, telegram use their own pickers. so maybe the default one does a good job, i just have never seen it. anyways, a file picker button (which could double as upload history button) is not in any way ruled out and will probably happen in the future

**Comment by syyyr** [comment]
I understand. In that case, I think it would be good if there (at least) were some instructions (in a Readme?, ideally directly inside the app) for a quick and easy setup with one of the services you mentioned. From my perspective: yeah, I was able to set up weechat, so I'm probably able to set up this thing. But if the app could do it instead of me, I'd be glad.

About the image picker: I have no idea, I don't really have an opinion, but I'm glad you're considering the feature.

**Comment by syyyr** [comment]
By the way, I'm not saying the feature can't go in without the stuff I proposed, it's just something I feel would be useful.

**Comment by Zopieux** [comment]
It shouldn't be too difficult adding a list of a few well-known host services, imgur being one of them.

**Comment by oakkitten** [comment]
as this is also using glide, issue #470 must be also taken into consideration

**Comment by Merlincool** [comment]
Needs further documentation, it's difficult to implement on https://postimage.org

**Comment by oakkitten** [comment]
as per [terms of use of postimage.org](https://postimages.org/terms),

> Automatic/programmatic uploads are not allowed

**Comment by Merlincool** [comment]
I don't get icon/button for uploads, I have to go to my gallery before I can throw some images directly via weechat. Is there any free imagehost which do not require signup? Or account?

**Comment by oakkitten** [comment]
yeah at this time this only supports uploading via sharing/keyboard input. you can look here for compatible image hosters: https://github.com/ShareX/CustomUploaders. some of the ones that work:

* https\://x0.at
* https\://0x0.st
* https\://ttm.sh

to configure, simply put the url into the `Upload URL` setting. please consider running your own instance of one of these services

**Comment by oakkitten** [comment]
so i was experimenting with a file picker button.

one of the issues is that it takes a lot of space. i can imagine only one sane way of dealing with this; hide the button if user has, say, > 10 characters in the input field. and perhaps add the upload action into overflow menu when the button is hidden?

another issue is the kind of intent that we can use to pick files (only considering external pickers for the time being). there's `Intent.ACTION_PICK` that works well for images *or* videos—it opens your favorite gallery app, but it's wonky when it comes to mixed media requests. `Intent.ACTION_GET_CONTENT` otoh works reliably in all cases, but the ui is just ugly.

i think it's reasonable to offer user a choice, especially considering that the picker button could server an additional configurable function via a long press

finally, there's the question of where to save files taken by camera. on Q+, we can just use MediaStore, files are saved into `Pictures/WeechatAndroid/IMG_timestamp.jpg`, no permissions required. before q, this action requires a permission and you can't put files in a folder using MediaStore api... the latter is possible with `getExternalStoragePublicDirectory()` but it also requires a permission. 

alternatively, we can save to our app specific directory using `getExternalFilesDir()`, but this folder is at `Android/data/com.ubergeek42.WeechatAndroid.debug/files/Pictures/` and who is going to look in there. (the idea here is that user shouldn't lose pictures they take)

so maybe we should ask for permission? or not? (manifest modification required too)

**Comment by oakkitten** [comment]
on this branch currently, a rare crash that i've seen before, probably coming from a library

this time it surfaced when unlocking phone with w-a active after a long time; also the don't keep activities option was on if that matters

```
FATAL EXCEPTION: main
Process: com.ubergeek42.WeechatAndroid.debug, PID: 21642
java.lang.NullPointerException: Attempt to read from field 'android.view.View androidx.recyclerview.widget.RecyclerView$ViewHolder.itemView' on a null object reference
       at androidx.recyclerview.widget.DefaultItemAnimator.runPendingAnimations(DefaultItemAnimator.java:157)
       at androidx.recyclerview.widget.RecyclerView$2.run(RecyclerView.java:589)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
       at android.view.Choreographer.doCallbacks(Choreographer.java:852)
       at android.view.Choreographer.doFrame(Choreographer.java:783)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7403)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```
