### ISSUE TITLE
Add Tab-complete for commands

### ISSUE THREAD

**Issue by shawnr13** [ubergeek42/weechat-android#46]
Specifically for /query and other "default" or basic commands, a tab-complete for "/?" where ? is a letter would be nice.

**Comment by oakkitten** [comment]
note: as of 2.9, relays [support completion](https://weechat.org/files/doc/devel/weechat_relay_protocol.en.html#command_completion). [see also](https://github.com/glowing-bear/glowing-bear/pull/1122)

**Comment by oakkitten** [comment]
closing in favor of the linked issue
