### ISSUE TITLE
Freennode Weechat Android Protocol error and Failed to connect error

### ISSUE THREAD

**Issue by gregdegruy** [ubergeek42/weechat-android#466]
I'm using weechat-android that I installed using f-droid and trying to connect to freenode in order to join an irc server. I am able to connect to freenode on my Windows 10 PC using mIRC as expected. Not able to do so on Android due to errors in the title.

I created this [stackexchange post ](https://android.stackexchange.com/questions/229884/freennode-weechat-android-protocol-error-and-failed-to-connect-error)with screenshots and more details.

**Comment by oakkitten** [comment]
Weechat-Android is not an IRC client itself. It is a client for WeeChat, which in turn is an IRC client.

You need to have WeeChat running on your server, and that is something that Weechat-Android can connect to, not Freenode.

**Comment by gregdegruy** [comment]
Would there be a reason why I can connect to my irc channel on Desktop, but not using Android?
