### ISSUE TITLE
Unable to connect to SSH tunnel using IP address since version 1.1 (F-Droid)

### ISSUE THREAD

**Issue by BetaRays** [ubergeek42/weechat-android#469]
I use an IPv4 address as “SSH hostname” and since updating on F-Droid, weechat-android only shows “Error: The hostname <IP address> is not known” (translation from French).

I tried running ssh-keyscan again to redefine the known hosts parameter but I still get the same error message.

What has gone wrong and can I still connect to an SSH tunnel with an IP address?

**Comment by oakkitten** [comment]
is your ssh server running a non-default port by chance?

**Comment by BetaRays** [comment]
> is your ssh server running on a non-default port by chance?

Yes, but only for the public-facing IP address, I could change it to the local address and set the known hosts accordingly temporarily if you think it can help diagnosing the problem

> if you are willing, please try this build (sorry about http) and see if it works for you

Ok, I'll try this, thanks for your help.

**Comment by BetaRays** [comment]
Your build is able to connect to my relay after setting the right options.

**Comment by BetaRays** [comment]
Using the local address with the F-Droid build and setting known hosts accordingly also works. This may be a duplicate of https://github.com/ubergeek42/weechat-android/issues/465 then, sorry for the noise.

**Comment by BetaRays** [comment]
Running `sed -r 's/^\[([0-9.]+)]:PORT/\1/` on the output of `ssh-keygen -p PORT IP` as suggested [here](https://github.com/ubergeek42/weechat-android/issues/465) also works.

**Comment by oakkitten** [comment]
aha, nice. we'll be merging #467 soon, then. thanks for trying out the build!

yes, removing the `[]`s and the port works, because the library only somehow considers only the host and not the port. we should be considering servers on different ports as different servers, though.
