### ISSUE TITLE
Color request

### ISSUE THREAD

**Issue by Merlincool** [ubergeek42/weechat-android#473]
It's more of a request than reporting any bug or so. The nightly should have basic theme of weechat stable version.

Also the nicks of other users need not to be white colour, it's disturbing to read chats with white Nick's and white colour chats.

Just keep user using weechat as white, rest all other users should be in non-white colours.

Skipping white for other users will make some sense.

This is just request.

**Comment by oakkitten** [comment]
in `Theme` preferences, you can use `Basic Terminal` color scheme, is this what you want?

i'm not quite sure about what do you mean by white nicknames, can you provide a screenshot perhaps?

**Comment by Merlincool** [comment]
@oakkitten 

Yes there is basic terminal theme no doubt but there is also other DEFAULT theme in stable version v0.13.12, if that could be integrated.

There is color assigned to other users I weechat, different nicks have different colour (thanks for that) but there is also white colour assigned to few nicks, that I don't want to be. It would be nice only the weechat user i.e only me should be given white colour and not other users should have white colour.

**Comment by oakkitten** [comment]
wasn't the default theme in 0.13 more or less the same as basic terminal theme, anyway? iirc it had a different background color, not sure what else? you can [create a custom theme](https://github.com/ubergeek42/weechat-android/wiki/Custom-Color-Schemes) if you want

> but there is also white colour assigned to few nicks

weechat-android is supposed to be displaying nickname colors as you configured in weechat (`weechat.color.chat_nick_colors`). are the colors wrong for you?

**Comment by Merlincool** [comment]
> weechat-android is supposed to be displaying nickname colors as you configured in weechat (`weechat.color.chat_nick_colors`). are the colors wrong for you?

No they aren't wrong for me, but certain other users get white Nick's which I don't want to be the case, and I don't know how you plan to check that color thing in weechat android? I just want that white colour for others except you should be removed.

**Comment by oakkitten** [comment]
if you remove white colours from `weechat.color.chat_nick_colors`, you won't be seeing them in the app

**Comment by Merlincool** [comment]
I do them in my android or weechat bouncer? Can you tell me how to edit, I haven't done this

**Comment by oakkitten** [comment]
my output for `/help weechat.color.chat_nick_colors`

	Option "weechat.color.chat_nick_colors":
	  description: text color for nicks (comma separated list of colors, background is allowed with format: "fg:bg", for example: "lightred:blue")
	  type: string
	  values: any string
	  default value: "cyan,magenta,green,brown,lightblue,default,lightcyan,lightmagenta,lightgreen,blue"
	  current value: "117,123,225,147,219,193,213,147,177,187,183,113,115,087,084,216,213,074,048"

i think you might want to remove `default` from here if you are using the default value?

**Comment by Merlincool** [comment]
Yes first thing I did was removed default, I will have to still check if I get some white Nick's again. I will come back to you if needed.
