### ISSUE TITLE
SOCKS proxy setting

### ISSUE THREAD

**Issue by jpds** [ubergeek42/weechat-android#474]
Can you please an option to allow users to configure a SOCKS proxy?

For my use-case, I also need this to apply to the SSH tunnel configuration as well.

**Comment by oakkitten** [comment]
in all likeliness this is not going to happen.

for one, this is the first time it has been requested so i guess not many people need something like that. besides, SSH tunnel is already a proxy and you can use a web server or stunnel or whatever to proxy things

for another, the networking code is a bit crazy but finally works fine so i'm not touching that unless absolutely needed. also, my kitten hates when i add new options to the app
