### ISSUE TITLE
Weechat nick color highlight change

### ISSUE THREAD

**Issue by Merlincool** [ubergeek42/weechat-android#476]
I wish to change my highlight colour but I am unable to.

`/set weechat.color.chat_highlight Yellow` fails and it doesn't change.

I want default colour which is in stable version. Yellow nick with magenta background.

`/set weechat.color.chat_highlightbg magenta` fails

**Comment by oakkitten** [comment]
you can use [custom color schemes](https://github.com/ubergeek42/weechat-android/wiki/Custom-Color-Schemes) to do this
