### ISSUE TITLE
Sort buffer list by last visited

### ISSUE THREAD

**Issue by quite** [ubergeek42/weechat-android#477]
Would be a great feature. More recently visited towards bottom.

**Comment by quite** [comment]
Or possibly what i'm after is open channel/user  tabs that persist over reconnect/app restart...

**Comment by oakkitten** [comment]
i think this kind of functionality would be best implemented as weechat script

if using "sync buffer read status", you can intercept our buffer read events

if not, you can reorder buffers when you e.g. send a message

**Comment by quite** [comment]
Yes i see.. 

I think there is some issue with tabs not persisting for me. Will see when we get the new working version.

**Comment by quite** [comment]
Btw @oakkitten tabs do seem to persist over app restart. On 1.2.

I think what i'm missing is a way to quit weechat. If i hit disconnect and swipe the app away (or force stop), it will remember upon starting that it was disconnected, and not connect and open tabs. I have been doing this, because sometimes you want to quit irc (!) and come back later.

**Comment by oakkitten** [comment]
is there a particular reason you want to quit the app?

**Comment by quite** [comment]
@oakkitten  yes, sometimes i just don't want to chat, and want to eliminate the distraction. And later i'd like to come back to the same state. That is why i run weechat (in tmux on server), and why i'd like my weechat-relay client to behave similarly :)

**Comment by oakkitten** [comment]
you can simply disconnect then
