### ISSUE TITLE
file sharing through REST-like endpoint, not form-based

### ISSUE THREAD

**Issue by quite** [ubergeek42/weechat-android#479]
I'm trying to use file sharing with a kind of RESTy endpoint https://github.com/espebra/filebin

It is not based on parsing the result of a HTML Form POST, but raw binary payload. And it requires the filename in a HTTP header. Typically used like so:
```
curl --data-binary "@/some/local/file" -H "filename: file.ext" https://filebin.net
```

This would be awesome to have support for.

**Comment by oakkitten** [comment]
there are many ways to send files over the internet. we could support more than we do now but html forms seem to cover most bases. our settings are already pretty complicated and i'm not sure this is where we want to introduce more of them

as i understand `--data-binary` sends data as `application/x-www-form-urlencoded` which [should not be used to send “large quantities of binary data or text containing non-ASCII characters”](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4). is this not the case? is there a large number of services that only work with `application/x-www-form-urlencoded`?

**Comment by quite** [comment]
You are right, I think filebin should support multipart in this case..

**Comment by oakkitten** [comment]
aha.. so i'll be closing this then. we can revisit this if there's more demand

**Comment by quite** [comment]
You are right, I think filebin should support multipart in this case..
