### ISSUE TITLE
Custom curl command for file upload feature

### ISSUE THREAD

**Issue by 3291823** [ubergeek42/weechat-android#481]
I  was not able to figure out how to use `curl -T image.png`. Perhaps a setting for a custom curl argument may be a better idea.
The reason being, I run https://github.com/andreimarcu/linx-server on my server and POST does not work, only PUT.
TIA.

**Comment by oakkitten** [comment]
we are not using curl internally, it is only given as an example. PUT is not supported. i don't this we should support PUT as it is meant to replace resources. this means that the URL we upload to should be the resulting URL, which is limiting. also we would have to make sure that the URL is unique. this shouldn't be our job.

i understand that PUT requests can also return data, but this is hacky—and why even do it when there's good ol' proper POST that everyone else is using? 

cmiiw

**Comment by 3291823** [comment]
Okay, I have found a way to use post & return a json string.
`curl -s -H 'Accept: application/json' -H 'Linx-Expiry: 60' -F file=@file 'https://shit.websi.it/upload'`
That returns something like this:
`{"access_key":"","delete_key":"dJUsePAF60BAaAwbb5eL4tSxdiEnBj","direct_url":"https://shit.websi.it/f/thx111.txt","expiry":"0","filename":"thx111.txt","mimetype":"text/plain; charset=utf-8","sha256sum":"58e6839b0a267fd875c6c628a4988a3fd1aee5614cc447bf9a6d0d4d4b2d3b99","size":"2780","url":"https://shit.websi.it/thx111.txt"}`
I tried a lot of regex strings that work on my desktop but none seem to work in the app..
I would only like to extract "direct_url". Thanks!

**Comment by oakkitten** [comment]
does this work? https://regex101.com/r/1Gft2n/1

**Comment by 3291823** [comment]
Yes! Thank you so much oakkitten~!

**Comment by Merlincool** [comment]
> does this work? https://regex101.com/r/1Gft2n/1

What is this? I am sorry for poking this topic, how can I add other image hosting? I tried Imgur with client ID but sometimes images fail to upload not always, can you provide couple of other image hosting settings like 2-3 popular ones in simple manner, like you have awesomely made it simple from this topic https://github.com/ubergeek42/weechat-android/issues/459#issuecomment-699555298

Hats off to your work

**Comment by oakkitten** [comment]
@Merlincool you can find instructions on how to set up your own hosting, or how to configure third-party services, [on our wiki](https://github.com/ubergeek42/weechat-android/wiki/File-sharing)

if using third-party services, please make sure you familiarize yourself with terms of use of the service

p.s. are there any particular errors when uploading to imgur?

**Comment by Merlincool** [comment]
> p.s. are there any particular errors when uploading to imgur?

No certainly not, I had just faced few issues like on 5-7 occassions I couldn't upload images and buffering clock was still rotating but didn't upload images, I doubt if I was on slower network that moment.

I just want to stay anonymous while I share images, but keeping client ID for Imgur is good idea? I won't be anonymous, also I tried x0.at but I did not success.

I don't know how to put up settings in android weechat, like you nicely gave detailed explanation above on how to customise settings for Imgur, can you put that for x0.at or any handful of others (probably you might have tested by now). 

It will support junkies like me. Thanks for your all efforts you have put over time.

**Comment by oakkitten** [comment]
as per the wiki, the only thing you should do to set up x0 is to put `https://x0.at` as upload url. the other settings should remain default. can you open https://x0.at in your browser?

> keeping client ID for Imgur is good idea?

i can be wrong but iirc you can't get any information about the account given an image url uploaded using a particular image id

> buffering clock was still rotating
counter-clockwise? this would mean that the server got the file but is not replying with anything. this shouldn't normally happen i think? if you can reproduce it please tell

**Comment by Merlincool** [comment]
> can you open https://x0.at in your browser?
Yes I can open that in my browser and works well. When I put thinks, just upload url and rest all as default (for field - I have kept that as image)

> counter-clockwise? this would mean that the server got the file but is not replying with anything. this shouldn't normally happen i think? if you can reproduce it please tell
Yes I haven't had issue since past two days. it must have been my network lag or something

**Comment by oakkitten** [comment]
> for field - I have kept that as image

do you mean that you set "File field" to "image"? it must be "file" for x0 to work

**Comment by IVData** [comment]
@3291823 I'm also running linx-server. Can you show me how you set up weechat-android to use it? Did you have to modify linx-server?

**Comment by Merlincool** [comment]
> @3291823 I'm also running linx-server. Can you show me how you set up weechat-android to use it? Did you have to modify linx-server?

run screen or tmux whichever you are comfortable with and run weechat in it and configure your android relay port and secret pass so you can connect to weechat from android app, you have to leave that screen running in background 24 x 7 so your android relay is connected to your weechat

**Comment by IVData** [comment]
No no I mean, I'm having the same issue as @3291823, I'm using linx-server as a image host, and I'm trying to use weechat-android to upload and share images to it.

Linx-server normally only accepts PUT requests to upload, but 3291823 says they have managed to get the two to work together.

**Comment by Merlincool** [comment]
> No no I mean, I'm having the same issue as @3291823, I'm using linx-server as a image host, and I'm trying to use weechat-android to upload and share images to it.
> 
> Linx-server normally only accepts PUT requests to upload, but 3291823 says they have managed to get the two to work together.

Sorry I didn't try with that
