### ISSUE TITLE
highlights notification

### ISSUE THREAD

**Issue by Merlincool** [ubergeek42/weechat-android#493]
Hi

I am here to ask for notifications.

I have gone through this scripts working on for like 3-4 days https://weechat.org/scripts/tag/notify/

None of them are Customisable for android. None of them are giving highlighted only notification, I don't want any notification in my notifier but I need certain words when highlighted will send me notification.

https://github.com/jreese/znc-push I found this but thats for znc and I need same like for weechat. this has feature to refuse when some one says my nick. I wish something of that sort is available for weechat. I need only some lines which has particular words to notify me not my names and personal message.

**Comment by oakkitten** [comment]
is this an issue with WeeChat or with Weechat-Android?

perhaps take a look at settings that appear when you run `/fset highlight` in WeeChat? especially `irc.look.highlight_*` and `weechat.look.highlight` and `weechat.look.highlight_regex`

**Comment by Merlincool** [comment]
I am speaking about for weechat android and it says, 

> =!= No help available, "fset" is not a command or an option

**Comment by oakkitten** [comment]
Weechat-Android follows WeeChat. every highlight you get in WeeChat results a notification in Weechat-Android. so I'm not sure we can help

> =!= No help available, "fset" is not a command or an option

please update your weechat, the plugin `fset` was added more than 3 years ago
