### ISSUE TITLE
Modern buffer design

### ISSUE THREAD

**Issue by contyk** [ubergeek42/weechat-android#494]
I was thinking whether it would make sense or be possible to come up with some templates / skins for displaying messages in buffers, more mobile-friendly, drastically extending the colorschemes concept.

My screen is narrow, people's nicks are long. I don't like cutting them short, and I still want to see the timestamps. This message metadata takes a significant portion of the available width. Perhaps a typical modern chat app look would work better here? I'm specifically thinking the common bubbles design, typically with metadata being on separate lines and potentially less prominent but anything could be done if user templates are supported.

I understand this would be a major change and make the rendering more complex but I'm wondering if that's something you might be considering.

**Comment by oakkitten** [comment]
i would like to see a mock-up of such a design

bubbles require quite a bit of both vertical and horizontal spacing to look decent, so in the end the amount of wasted space is more than one additional line per message. this might work for slow-paced chats but many irc rooms can be very fast. if you were ever in a large telegram chat you know that bubbles do a pretty poor job there

i don't think it would be too hard to implement bubbles per se. the hardest part would be animating bubble size changes when re-drawing it with media thumbnails. the text is currently going through a simple fade-out fade-in animation, but the bubble would probably have to be properly animated

...otoh with bubbles one would use proportional fonts and those would save some space

...also bubbles do a poor job with ascii art stuff

**Comment by contyk** [comment]
I'm no designer and didn't have any really specific ideas, although I could try putting something together to illustrate. The main idea was to allow for some templating, ideally so that people could make their own styles. And if they prefer the current, terminal-like view, that'd be fine, too.

You're, of course, correct with really fast-rolling channels being potentially harder to follow with bubbles specifically; however, I think that's always the case simply because sometimes people post faster than I can read. Overall it still depends on the specific style and how much space is "wasted".

I can't comment on the media preview bit but yes, these could easily use any fonts, and yes, ASCII art would break (although I, thank god, never see anyone posting that in channels; it's just server banners).

**Comment by oakkitten** [comment]
i suspect user templates would be a nightmare to implement

also consider that what WeeChat sends was meant to be printed in WeeChat. usually, the nickname and the message is separated by the tab character, but for actions the “nickname” is `*` and the message includes the nickname. now you can just print that, but you wouldn't want to print that in a bubble so what will you do?

also there are non-standard messages such as notices that for some reason have nickname “--” and then the message starts with “Notice(Nick): Message”. ideally you would print this as a bubble but how exactly--

**Comment by oakkitten** [comment]
closing as no info; we can revisit this when there are concrete suggestions
