### ISSUE TITLE
Linkify URLs containing custom domains such as `http://go` or `http://go.r`

### ISSUE THREAD

**Issue by Lassulus** [ubergeek42/weechat-android#497]
hi, I have custom domains in the style of http://go or http://go.r on my vpn. Sadly they are not clickable inside weechat. Would be nice if the url regex could be tuned for that.

**Comment by oakkitten** [comment]
i understand that `http://go` is a valid url but more often than not such urls lead nowhere and so best not be clickable. e.g. someone says something along “yeah you can put http://whatever there”. we are currently require 2+ letter tlds https://github.com/ubergeek42/weechat-android/blob/b11ac39e15f04075aea3513914e3b594ea896550/app/src/main/java/com/ubergeek42/WeechatAndroid/utils/Linkify.java#L112-L114

a self-containted workaround would be to put `go.foo` to your hosts file or your dns server and perhaps have weechat rewrite `http://go` as `http://go.foo` using a trigger

**Comment by Lassulus** [comment]
maybe a one letter TLD would be sufficient? :) It would really solve my usecase. But maybe it would be cooler to have the regex for clickable stuff configurable? But if its to obscure I would understand and continue with my workaround, but I really wanted to make the shortened urls I use as short as possible :D

**Comment by oakkitten** [comment]
i think single-letter tlds are even more rare. why not `http://r.go`? that would work and has the same length

configurable regex is possible but i'm not sure if that would be useful apart from this particular case, and we don't want to support very rare use cases

you can also build an apk with your changes. you can use android studio or [command line](https://github.com/ubergeek42/weechat-android/wiki/Getting-started-with-the-code#building-via-command-line)

**Comment by Lassulus** [comment]
well the vpn uses .r generally. I now need a hosts entry just for this workaround. This is not a big issue for me, but I prefer to stay close to upstream and keep my local config simple. This is not always possible if to obscure, so I will keep my local workaround ;D
thanks for the help!

**Comment by kmein** [comment]
I'm having the same problem, because my VPN also uses a single character TLD for its hostnames.

**Comment by oakkitten** [comment]
may i ask what VPN services these are? and also how are y'all using these fancy URLs in WeeChat?

**Comment by Lassulus** [comment]
I'm using this https://github.com/krebs/retiolum which has a bunch of services and irc servers which all rely on the .r TLD for their urls. I connect to my weechat instance via wireguard from my android.

**Comment by oakkitten** [comment]
so we can go two ways here:

* allow hosts such as `go` and `go.r`. these hosts may not exist in the wild but are still valid urls. while they are valid, however, our goal at large is to linkify text in a way that's sensible for IRC and these URLs will generate some false positives... said that, github's linkifier, for instance, does generate links for both http://go and http://go.r

* we can special-case `.r`, `.w` and `.y`. as i understand, this would cover the use case mentioned above. such URLs will be only useful to those who share a DNS resolver and this probably does not happen outside of environments such as set up by this https://github.com/krebs thing here

**Comment by kmein** [comment]
🥳
