### ISSUE TITLE
Can't connect to relay without password

### ISSUE THREAD

**Issue by DirtYiCE** [ubergeek42/weechat-android#498]
If I leave relay password empty in the settings, I get "Relay password is not set" error when I try to connect. If I set a dummy password in the config, it tries to connect, it fails with "Server unexpectedly closed the connection while connecting". In the weechat buffer I see
```
00:57:32                  weechat     | relay: new client on port 9988: 3/weechat/::1 (waiting auth)
00:57:33                  weechat =!= | relay: authentication failed with client 3/weechat/::1
```
Which makes sense, since the password I supplied in the settings is invalid. But an other client that just sends `init compression=off` works fine:
```
00:58:52                  weechat     | relay: new client on port 9988: 1/weechat/::1 (waiting auth)
00:58:52                  weechat     | relay: client 1/weechat/::1 connected/authenticated
```
Version: f-droid 1.4.1 (build id: v1.4.1-0-g5440f6a5)

**Comment by oakkitten** [comment]
yes, at the moment the app requires that a password is set

**Comment by DirtYiCE** [comment]
Thanks, it works now.
