### ISSUE TITLE
SSH tunnel settings: error (?) when setting key and cannot authenticate

### ISSUE THREAD

**Issue by soratobukuroneko** [ubergeek42/weechat-android#500]
Device: Samsung Galaxy S5e wifi (SM-T720) (gts4lvwifi)
OS: Android AOSP 10 (LuisROM 6.13, based on crDroid)
key algorithm: ED25519

SSH tunnel was working until I reinstalled and reconfigured Android (same ROM). Now, when I try to set my SSH key I get the following message:

```
EdDSA key was stored inside the app.
The key couldn't be stored in the key store. Can't make a certificate for a key algorithm EdDSA
```

logs server-side:

```
sshd[13004]: error: kex_exchange_identification: read: Connection reset by peer
sshd[13004]: Connection reset by 142.93.8.164 port 50587
```

I don't know if I got the same message from weechat-android when it was working before reinstallation. But now it fails to authenticate.

I didn't see anything in logcat.

**Comment by oakkitten** [comment]
> EdDSA key was stored inside the app.
The key couldn't be stored in the key store. Can't make a certificate for a key algorithm EdDSA

this is expected for Ed25519 keys and not an error (android key store needs a certificate to store key pairs and BC can't create Ed25519 certificates, not sure if those exist even)

> sshd[13004]: error: kex_exchange_identification: read: Connection reset by peer

i suppose this is a standard connection reset thing that could mean a few things?

> I didn't see anything in logcat.

this is weird, we definitely should be showing an error toast & printing something to logcat on error. perhaps you could see us on #weechat-android on freenode so we can try to get to the bottom of this. if you can't, please say:

* what's the exact app version / build id?
* does the app continue connecting after failure?
* does it not show the error toast at any time? (red balloon on the bottom of the screen)
* can you connect with the same key using JuiceSSH etc?
* can you connect using other key types (e.g. rsa)? 
* if not, can you connect using password?
* if not, can you connect in any other way?

**Comment by oakkitten** [comment]
closing as this hasn't been followed up
