### ISSUE TITLE
Various Linkify improvements

### ISSUE THREAD

**Issue by winny-** [ubergeek42/weechat-android#501]
This is a issue to track various ideas for improvements for the Link matching logic.  The goal is to avoid creating a bunch of issues to track separately.

- The following URLs are linkified, but should not be:

```
h[://a.com/
h\://a.com/
h]://a.com/
h^://a.com/
h_://a.com/
h`://a.com/
```

- hosts without a subdomain are not linkified, e.g. `http://somehost/`.  Practical use case - oe can configure their local DHCP server to give your android device a list of search domains, which are tacked on the end of domains when resolving the domain fails.  For example in my home lan setup: `http://hades/` resolves to `http://hades.lan/`.

- punycode domains are not linkified, e.g. `https://xn--i-7iq.ws/`

- RFC 1918 (private) IPv4 addresses are not linkified for some reason.  Localhost and IPv4 Link local addresses are not linkified for some reason.  Both may be useful to users who do not have domain name services configured for a specific setup.

- IPv6 Addresses are not linkified, e.g. `http://[2607:f8b0:4009:810::200e]/`  .  Might be useful to users who do not have dns set for a specific ipv6 address.

- The linkifier makes certain assumptions of the size and contents of the TLD.  See also #497.

**Comment by oakkitten** [comment]
a few days ago i added some more stuff to https://github.com/ubergeek42/weechat-android/tree/linkify-fixes, including an [updated regex (now in kotlin!)](https://github.com/ubergeek42/weechat-android/blob/efb71961666aa0eeaa928fc5c287a251f9708a5c/app/src/main/java/com/ubergeek42/WeechatAndroid/utils/Linkify.kt#L70-L161) and also [some tests](https://github.com/ubergeek42/weechat-android/blob/linkify-fixes/app/src/testDebug/java/com/ubergeek42/WeechatAndroid/utils/LinkifyTest.kt)

hopefully it covers all points that you mentioned! (would be nice if someone reviewed or tested it, too)

**Comment by winny-** [comment]
I looked over your changes and they appear a vast improvement over the old linkification code.  And bonus it's in Kotlin.

Here are some URLs to test, all of which work:

```
http://[2607:f8b0:4009:810::200e]/
https://xn--i-7iq.ws/
http://thing/
http://a/
http://a.b/
http://10.0.0.1/
http://127.0.0.1/
http://thing.local/
http://i❤️.ws/
```

I verified the characters between `Z` and `a` (caused by `[A-z]`) will no longer match in the URL scheme.

Found some false positives that may rarely come up in real world use.  The following are linkified in this branch:

```
www.127.0.0.1
www.[2607:f8b0:4009:810::200e]
```

I look forward to assist with more testing. ;-)

**Comment by oakkitten** [comment]
aha, thanks! pushed a62ae6afd14d91cf1362a8fc528ac366009aa500, hopefully it'll take care of that

**Comment by winny-** [comment]
Yup, looks like that fixed the issue with `www.` prefixes.  I'll keep on testing.

**Comment by oakkitten** [comment]
`linkify-fixes` has been merged into master
