### ISSUE TITLE
suggestion: search for a buffer and pin a buffer

### ISSUE THREAD

**Issue by elig0n** [ubergeek42/weechat-android#502]
i would like to suggest two deatures : search all buffer names to narrow and go to selected one, and pin selected buffers to top of the list. Both are pretty useful when there are a lot of buffers and make navigation easier .

**Comment by oakkitten** [comment]
you can filter buffers using buffer filter (yeah i know). it's enabled by default now but wasn't before, see settings - buffer list

you can “pin” buffers by moving them to the top by running `/buffer move 1` etc

**Comment by elig0n** [comment]
wouldn't buffer move also affect the weechat client? i was looking for app specific pins

**Comment by oakkitten** [comment]
it would. we do support app-specific buffer hiding, but not reordering. what's the use case?

**Comment by elig0n** [comment]
temporarily pinning active buffers to the top. be it highmon, private message or script or status buffers.  
easier than typing in filter or scrolling through a list of dozen buffers. especially when such movement need to happen repetitively

**Comment by oakkitten** [comment]
this still sounds like a job for WeeChat and not specifically Weechat-Android

if what you are looking for is dealing with a large number of buffers, i suggest buffer hiding which we i think perfectly support. simply hide all the technical channels and other channels that you are not manually opening. i've got an alias `/h => /buffer hide;/eval /buffer_autoset add ${window.buffer.full_name} hidden 1` that persists hiding. also [this trigger](https://github.com/weechat/weechat/wiki/Triggers#temporarily-unhide-manually-hidden-buffers-when-they-are-relevant) temporarily unhides buffers when they become relevant. works very well for me. just a suggestion
