### ISSUE TITLE
ancient version extant on app store

### ISSUE THREAD

**Issue by mumbleskates** [ubergeek42/weechat-android#505]
since my phone updated to android 11, the app barely works at all. strace on the weechat host shows that many messages and requests are simply not sent from the phone, resulting in most attempts to connect, open buffers, send messages etc. failing to complete.

most incoming irc messages are still processed on the phone, but behavior is at least _similar_ to what you might expect to see if the client application did not flush its outgoing stream; incoming messages will continue to be received as long as you manage to have an open buffer, but you often cannot send messages nor open new buffers nor load more backlog (no packets will be sent to the server). closing the connection still results in an immediate, server-visible closure of the tcp pipe.

i have confirmed that this bug occurs on samsung's android 11 with the 2021-02-01 update, but not on the prior android 10 release nor on my old android 7.1.1 device (both devices running weechat-android v0.13-12-g4aad743).

**Comment by oakkitten** [comment]
0.13 is very old, please update to a more recent version

if the issue remains on 1.5, please specify your connection method. also it would help if you tried other connection methods. also you can find us on irc; something like this would be easier to investigate over irc

**Comment by mumbleskates** [comment]
That might explain it. The version I have in my library and have been using for years is [this one](https://play.google.com/store/apps/details?id=com.ubergeek42.WeechatAndroid); there's never been an indication that there was a transition to a newer app, and the "this version is very old and we're having technical difficulties updating it" warning does not appear on the mobile store page for me.

...

okay, i've got the newer one set up and working fine. What's the best solution here for the older app?

**Comment by oakkitten** [comment]
the publishing process for that version (likely forever) broke so we adopted out nightly version as the primary version. not sure we can do much more here. the version you linked to is unlisted and only opens for those people who have the app in their library. not sure why the warning does not appear on mobile pages. i don't see any other way to communicate with our users

**Comment by mumbleskates** [comment]
in what way is it broken? i wonder if it's possible for me to help

**Comment by mhoran** [comment]
We lost the private key. We can longer publish that version, which is why it has been replaced. We should link to the new version. We have delisted the old version but we can't push anything to those who have the old version installed.

**Comment by mhoran** [comment]
Apparently you can now contact Google to reset the upload key. We need to get @ubergeek42 to do this and he can be difficult to get a hold of, but we'll give it a shot.

**Comment by mhoran** [comment]
Nevermind. You have to be enrolled in app signing by Google Play, and since we weren't when the key was lost, we can't do anything.

**Comment by ubergeek42** [comment]
I saw your first comment as a notification and got hopeful, clicked on it only to see the follow up :(

**Comment by oakkitten** [comment]
closing as not actionable
