### ISSUE TITLE
can't connect to haproxy weechat ssl relay; glowing bear works

### ISSUE THREAD

**Issue by saywebsolutions** [ubergeek42/weechat-android#506]
I setup a relay using haproxy to handle ssl according to these instructions: https://github.com/glowing-bear/glowing-bear/wiki/Proxying-WeeChat-relay-with-a-web-server#haproxy

Glowing bear works but I can't seem to get weechat-android to work (using latest version via f-droid). Any tips on troubleshooting or recommended connection settings for this setup?

Thank you

**Comment by oakkitten** [comment]
i couldn't connect with the configuration in your link (neither g-b nor w-a worked) but this did (exact contents of /etc/haproxy/haproxy.cfg):

```
frontend my.site
  bind *:444 ssl crt /etc/letsencrypt/live/my.site/all.pem

  use_backend my.site

backend my.site
  option forwardfor header X-Real-IP
  server irc 127.0.0.1:9000
```

please double check that you are using either WebSocket (SSL) or WeeChat SSL and that the other settings are correct. please provide the error that w-a gives. you might find addition info using `adb logcat`. also see if `/relay`, `/relay raw` provide anything useful. also run haproxy in debug mode (`/etc/haproxy # haproxy -f haproxy.cfg -d `)

you can also use [stunnel](https://github.com/ubergeek42/weechat-android/wiki/Client-certificates#configuring-server-stunnel)

**Comment by saywebsolutions** [comment]
thanks for the tips and direction; i did end up getting it working by removing all of the default haproxy config entries (something in there must be conflicting / causing issues). I still have it using port 443 and it is working, thanks again
