### ISSUE TITLE
Suggestion; Add connection button to toolbar

### ISSUE THREAD

**Issue by khaytsus** [ubergeek42/weechat-android#509]
It's just a one-tap difference in reality, but it would be really nice to have a connect/disconnect button in the toolbar, primarily for disconnecting but might as well make it a toggle even though connect of course is just tapping the screen when it's not connected.

**Comment by oakkitten** [comment]
i don't suppose manually connecting/disconnecting is something that users are normally doing often? also, you can disconnect using the notification as well

**Comment by khaytsus** [comment]
I can only speak for myself but I tend to launch, connect, check a few channels or send a quick message, then disconnect. I am primarily a desktop client kind of guy, someone who uses irc primarily mobile would have a very different use case.

**Comment by oakkitten** [comment]
i don't have statistics on this but i suppose most people just stay connected all the time. connecting/disconnecting via menu should be easy enough. we can revisit this if more people want this kind of a button
