### ISSUE TITLE
Relay over UNIX domain socket

### ISSUE THREAD

**Issue by jpds** [ubergeek42/weechat-android#513]
WeeChat supports relaying over a UNIX domain socket, would it be possible to add this as a connection option in weechat-android?

**Comment by oakkitten** [comment]
as i understand unix domains are intended for communication on the same machine. weechat-android is meant to connect to a remotely running weechat. i'm not sure how these would be useful here

**Comment by jpds** [comment]
@oakkitten Ah, I thought it might be possible to remotely access the socket over SSH, but now I realize that that might not be the case.

**Comment by oakkitten** [comment]
i think ssh can do that. but i don't think the library we are using (connectbot/sshlib), or in fact any of the libraries we ever attempted to use (jsch, sshj), can do it. and there's little hope that they will 😔 correct me if i'm wrong

**Comment by oakkitten** [comment]
closing as not possible at the time
