### ISSUE TITLE
Failing to connect because "server is attempting to send a message of size 1213486160 bytes"

### ISSUE THREAD

**Issue by lokesh-krishna** [ubergeek42/weechat-android#515]
I'm trying to connect to my relay using the plain connection mode and this is the error I've been getting. I dunno which end the issue is at or how to go about troubleshooting it. I'm on v1.6-dev on Android 11 and attempting to connect to a relay on WeeChat 2.9-1 on Ubuntu 20.10.

What other information can I provide to help me out?

**Comment by oakkitten** [comment]
this often happens when you try to connect to an encrypted endpoint; please make sure there's no ”ssl” in `/relay listrelay` & the ports are correct

**Comment by lokesh-krishna** [comment]
I'm attempting to connect to port 443 because I have a websocket set up with Nginx. If I attempt to connect using WebSocket as the connection type, I get a different error instead. 
```
The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 400 Bad Request.
```

I am however able to connect to the relay just fine using Glowing Bear with my hostname and 443 as the port.

**Comment by lokesh-krishna** [comment]
Using WebSocket (SSL) as the connection type fixed it. Sorry for the noise.
