### ISSUE TITLE
Suggestion: Warn about "battery optimization" when detecting frequent relay disconnects

### ISSUE THREAD

**Issue by SaphireLattice** [ubergeek42/weechat-android#516]
I have had constant spam of reconnects in my weechat buffer as the relay kept connecting and reconnecting practically every half a minute at times. Turns out that turning out the OS "battery optimization" got that solved. But it was annoying that I did not even remember that could affect things ^^'

**Comment by oakkitten** [comment]
weechat-android shouldn't require disabling battery optimization. are you using some kind of a funny rom perhaps? what's your device & os?

**Comment by SaphireLattice** [comment]
Samsung A50 (SM-A505FM/DS) - Stock room, never rooted nor unlocked, 2021 April 1st update - Android 11 / One UI 3.1 / Linux 4.14.113.

Was at ~26% battery and the reconnection spam completely stopped as soon as I disabled optimization? Though I did switch from Websocket SSL to just websocket, fail to make it use the internal VPN IP rather than external VPS IP, then switched back to how it was.

**Comment by oakkitten** [comment]
i guess samsung does qualify as a funny rom given how it's occupying the first position on https://dontkillmyapp.com/. said that, i haven't heard of any reports that its battery optimization shenanigans interfere with us so badly. it would make sense if it simply killed off our process, but if it is able to reconnect it must be alive?

the easiest way to get to the bottom of this would be to install [adb](https://developer.android.com/studio/command-line/adb) and look in logcat for any relevant errors.

if you can't do that, can you please say:
* does the app give any errors when disconnecting?
* does this happen while the app is open?
* does the “Connected to <your server>” notification go away when disconnecting?
* does turning ping on/off have any effect?
* anything funny happening in windows that open in weechat when you run `/relay` & `/relay raw`?

also, what's the exact build id (settings — about)? where did you get the app? if not using v1.6, does using v1.6 help?

**Comment by oakkitten** [comment]
i tested the app on SM-A505F/DS (other numbers the same) and it worked fine with the most strict battery settings i could find

**Comment by oakkitten** [comment]
closing as no info
