### ISSUE TITLE
Can I export a colour scheme or at least view it?

### ISSUE THREAD

**Issue by lokesh-krishna** [ubergeek42/weechat-android#523]
I screwed up by deleting my custom color scheme once I imported it into Weechat-Android after the new update. I however want to tweak it and presently can't see a way to either export the file out or even just view it. Is this possible or will I have to start from scratch again?

**Comment by oakkitten** [comment]
you can likely find the files at `Internal shared storage/Android/data/com.ubergeek42.WeechatAndroid.dev/files/themes` (maybe without `.dev`)

**Comment by lokesh-krishna** [comment]
That worked! Thanks a lot! :D
