### ISSUE TITLE
Network connection may not be being verified in method

### ISSUE THREAD

**Issue by amazuerar** [ubergeek42/weechat-android#528]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of network connection within a method since some network operations are being performed in it.

As you might know, a device may not be connected to a network. In order to get such information see https://developer.android.com/reference/android/net/ConnectivityManager. Therefore it is recommended to identify whether the device has a network connection available before performing a network operation.

In order to address this issue we recommend you to visit:

1. https://developer.android.com/training/basics/network-ops/managing
2. https://developer.android.com/reference/android/net/ConnectivityManager.NetworkCallback

**Potential Method Location in which the network connection may not be being verified**

https://github.com/ubergeek42/weechat-android/blob/379f0863e9eef70d83462a5d13e8de932eb785b5/app/src/main/java/com/ubergeek42/WeechatAndroid/media/OkHttpStreamFetcher.java#L97-L104

Note: `public NetworkInfo getActiveNetworkInfo ()` returns details about the currently active default data network. When connected, this network is the default route for outgoing connections. You should always check `NetworkInfo#isConnected()` before initiating network traffic, it requires `Manifest.permission.ACCESS_NETWORK_STATE`. However, be aware that `isConnected()` was deprecated in `API level 29`, one could instead use the `ConnectivityManager.NetworkCallback` API to learn about connectivity changes, to be more specific the `onAvailable()` method.

**Comment by oakkitten** [comment]
@amazuerar what's the problem with not being connected to a network while performing a request?

**Comment by amazuerar** [comment]
Hello @oakkitten!

Before performing any network operations, one must first check that the device is connected to a network, and complementarily one should also verify the type of network (e.g., `Wi-Fi`), wether it is metered or not, and its Internet availability (i.e., a device can be connected to a `Wi-Fi` network without Internet), otherwise the request may not go through because of a lost connection to network. For such purpose Android provides `ConnectivityManager`

**Comment by oakkitten** [comment]
@amazuerar i am not sure this is a good way to tackle the issue. for one, 

* when you perform a request, if it does not work for internet unavailability or other reasons, you will promptly get an exception that is indicative of the issue and you can use that to inform user of the problem. besides,
* even if you check for network availability before performing a request, you can't rely on that information, as
  * connectivity can change between the check and the subsequent request, and
  * the connection can still fail for other unexpected reasons.

therefore i don't think that checking for network connectivity before issuing a request is useful advice
