### ISSUE TITLE
Error:  Cannot to verify hostname

### ISSUE THREAD

**Issue by ButtonGwinnett** [ubergeek42/weechat-android#531]
weechat-android does not connect using Weechat SSL but connects with plaintext

The app reports:

> Error:  Cannot to verify hostname: 127.0.0.1.

I used the second example in the SSL relay guide with the loopback IP as noted from a 2017 issue report by tnguyen14 [#330](https://github.com/ubergeek42/weechat-android/issues/330#issue-comment-box) . But that didn't seem to be any problem because the connection was attempting with a bogus hostname anyway and being closed according to weechat because of no matching ciphering between weechat and the app.

weechat reports:

> relay: TLS handshake failed for client 2/ssl.weechat/127.0.0.1: error -87 No supported cipher suites have been found.

What SSL cipher suite does the app use? Does the app use Android system defaults? How can I resolve the issue?

**Comment by ButtonGwinnett** [comment]
This appears to be caused by the gnutls libs otherwise called SSL throughout the documentation presumably both weechat and the app pass off the TLS routine to the respective environment libraries for the app the android system TLS which may be inaccessible without root. Does weechat indeed pass on the TLS routine to an gnutls library?

**Comment by ButtonGwinnett** [comment]
The Weechat SSL relay code here https://github.com/weechat/weechat/blob/8b5da3c6cb7e29f3695edaf4d4973d9479a4ed89/src/plugins/relay/relay-network.c

**Comment by ButtonGwinnett** [comment]
According to weechat 4.3 Doc.s 

relay.network.ssl_priorities

description: string with priorities for gnutls (for syntax, see documentation of function gnutls_priority_init in gnutls manual, common strings are: "PERFORMANCE", "NORMAL", "SECURE128", "SECURE256", "EXPORT", "NONE")

type: string

values: any string

default value: "NORMAL:-VERS-SSL3.0"

Thus it is using SSL 3.0 from a gnutls code library as seen included above. When weechat builds does it build the entire library into the binary output or does the gnutls.h only specify to call a dependency on a system lib?

**Comment by oakkitten** [comment]
you probably don't need to use encryption when connecting to localhost in the first place. 

however it should work provided you follow [our SSL guide](https://github.com/ubergeek42/weechat-android/wiki/Using-SSL-with-WeeChat). make sure the hostname (or IP) you connect to is the exact same one you entered when creating the certificate.

the app uses whatever the default TLS environment your device has. please try connecting using other means (glowing bear, or just try pointing your browser at weechat — in the case of a self-signed certificate, it should give you the usual warning). if that works but the app still gives you grief, perhaps

* try launching weechat with a clean profile (`weechat -d /tmp/foo`)
* try connecting to a weechat on a different machine
* maybe try using a reverse proxy sunch nginx or stunnel
* maybe try debugging with `s_client` or similar things. i can't point to things you want to look for there but i hear people having success?

**Comment by oakkitten** [comment]
closing because no reply
