### ISSUE TITLE
Error Unexpected code 400

### ISSUE THREAD

**Issue by Merlincool** [ubergeek42/weechat-android#534]
This is what I am getting when I am trying to add images to Imgur, it was running fine few days ago and today abruptly it's showing such error all the time.

[](https://i.postimg.cc/m249LRPJ/IMG-20211225-103503.jpg)

**Comment by oakkitten** [comment]
> Status Code: 400
> This error indicates that a required parameter is missing or a parameter has a value that is out of bounds or otherwise incorrect. This status code is also returned when image uploads fail due to images that are corrupt or do not meet the format requirements. 
 
-- https://api.imgur.com/errorhandling

perhaps you could try different images. if that fails, you could try replicating the error [using curl](https://github.com/ubergeek42/weechat-android/wiki/File-sharing#configuring-client). if that fails, you might get some clue as a part of the response. if that *doesn't fail*, then perhaps imgur doesn't like your user agent anymore? you could try pointing your device at your own server (`nc -l` would do the job) to figure that out. also if you've got logcat, you might want to see if anything f use is printed in there.

**Comment by oakkitten** [comment]
closing because no further comments
