### ISSUE TITLE
[Feature Request] Show a notification with sound when the connection is broken

### ISSUE THREAD

**Issue by InfinityLoop1309** [ubergeek42/weechat-android#548]
Thanks for your hard work! 
Weechat-android is really a good application and I am using it as my daily irc client. However, there left to be a problem  - I can not get notified when the connection is broken unless checking the notifications regularly. When using irc for work, even a five-minute disconnection is unacceptable, so that is a big drawback. 
Hope you can fix it :)

**Comment by oakkitten** [comment]
I'm not sure if this is functionality that any major chat app offers. This would be a very rare use case as the connection on a mobile can break a lot. However, we already have a persistent connection status notification; don't have a device at hand but I wonder if simply adding a sound to it in notification preferences will work?

**Comment by InfinityLoop1309** [comment]
yes that make sense. but those disconnections with reconnecting counter less than 1 minute or some thing may be ignored to avoid notificating too often

**Comment by oakkitten** [comment]
I feel the inconvenience but I hope you understand that we don't want to introduce extra complexity as this is just such a rare use case. If simply setting sound on the notification doesn't work, I suggest:

* Download the source and making the needed changes and build a version for yourself. Building with AS is usually trivial and we have some instructions in the Wiki I believe. Tinkering with Kotlin might not be so easy. You want to take a look at Notificator.kt. 
* Use some sort of an automation app. I can't suggest any particular one but from what I saw these can inspect notification text and launch timers and play sounds, so this should work.
* Use a WeeChat trigger that plays a sound or something if a relay client hasn't been connected in a while.

**Comment by InfinityLoop1309** [comment]
Thanks for your feedback. Actually I have made a quick fix before I made the feature request, but it was written very dirty. I just think that it would be more gracefully done from a maintainer.
I fully understand your situation. In that case I will keep using my own modified version.
