### ISSUE TITLE
No refresh in xfer buffer

### ISSUE THREAD

**Issue by michnixweiss** [ubergeek42/weechat-android#567]
When I receive a file its handled by xfer. In the shell I can switch now to xfer and accept the file, download is starting.
In the app the xfer buffer can be displayed by unchecking the "hide server-buffer" option. But I cannot send "a" for accepting the file.
Is there a solution or workaround?

Many thanks

EDIT:
I found out, that interaction with xfer is working as expected. But there is no refresh in buf/view. So I can see no progress in file transfer, only possible refresh is to cut connection to weechat and reconnect.

**Comment by michnixweiss** [comment]
Is someone still maintaining this?

**Comment by oakkitten** [comment]
We do not currently support the so-called free content buffers, which include xfer, script, fset buffers, etc. There seems to be no direct support for that in the relay protocol, and supporting these table-like buffers in any capacity would be overkill for us anyway.
