### ISSUE TITLE
Question: How to enable debug logs?

### ISSUE THREAD

**Issue by freedom-foundation** [ubergeek42/weechat-android#583]
how to see debug info because when trying to connect to an ssl relay it reports SSL handshake exception. I need to see why it fails. I am guessing it is because certificates not trusted but the app really should be able to capture why it fails. 
 How to enable debug logs?

**Comment by oakkitten** [comment]
Sorry for a late reply. 

At the moment, you can see the logs in the [Logcat](https://developer.android.com/tools/logcat). You'd have to enable developer options on the phone, install `adb` on your computer, connect the two devices together, and say `adb logcat` to view the logs.

We should definitely be displaying better error messages in the app itself. We use Toasts for this, which was “good enough” before but as these are limited to just two lines on recent Android versions, we should switch to Snackbars.

**Comment by freedom-foundation** [comment]
Kindof a note to self: all of SSL in weechat is broke and it would be better to remove it all. In the meantime you can use irssi with plain-connections only or maybe attack-dog IRC client. For about any of these apps to do SSL right and make it useful pretty much everything in openssl-tool should be availiable from within the app as an advanced security panel of some sort. WITHIN THE APP and apply to and against the ssl which is within the app ( not external libs).
