### ISSUE TITLE
SSH Tunnel: local port cannot be bount

### ISSUE THREAD

**Issue by 0mark** [ubergeek42/weechat-android#59]
I used weechat-android for some weeks with ssh tunnel for some weeks (Its totally awesome!). Then i tried the latest dev version from github, and ssh stopped to work, so i downgraded to the stable version, but the problem remains. Whenever i try to connect i get this message:

Error: PortforwardingL: local port 127.0.0.1:22231 cannot be bound.

The strange thing is, i use port 9001. I tried to remove the app and reinstall, reboot the device, tested other settings (using plain connection and connectbot to make port forwarding works), other ports, restarted weechat, everything i could come up with.

It just wont work anymore.

**Comment by etu** [comment]
Just experinced this issue when trying out the beta app. Found that my issue was that the non-beta app was already connected because they apparantly use the same local port. Just putting it here if people encounter that.

**Comment by ardumont** [comment]
Hello,

I am hitting this issue after having upgraded the android version from 6 to 7 (on a oneplus3 if that matters).

It's the [same error message as the initial comment](https://github.com/ubergeek42/weechat-android/issues/59#issue-10125834) with the [sensibly same screenshot](https://github.com/ubergeek42/weechat-android/issues/59#issuecomment-21084674) (except for the running weechat-android version really :)

I did not touch any weechat-android configuration whatsoever after android upgrade (v.0.12-git installed from f-droid). 
I'm forgetting one important point, weechat-android worked perfectly prior the android upgrade (through ssh tunnel configuration with private key)

Also, nothing changed on the server ;)

So far, I did not successfully reconnected. What I tried and did not help:
- Force stopping the app

- Rebooting the complete phone did not help.

- Taking a look at the relay buffer, i saw some hanging connections (but nothing quite distinguishing the relay connection), disconnecting them all (yes, at the expanse of other clients) and trying to connect again did not help either.

- Purging the application data...? Well, i screwed up that test and direcly uninstalled it (mind plays trick sometimes :)

- Uninstalling the app and reinstalling it then.
After configuration, I have no more error message.
I don't see any buffer though.
I see one new connection in the relay list (the timestamp match the time i hit connection on the phone)... Definitely disconnecting it from the relay buffer stops weechat in the phone (or crash it?)...

Anyway, i'm at a loss for what i can try next.
Any hint would be appreciated, thanks a bunch in advance.

Also, worth mentioning, thanks a lot for weechat-android, it's awesome!

Cheers,

**Comment by ardumont** [comment]
`adb logcat` might help:

So authentication actually succeeds, but address is already in use: 
```
02-11 17:38:20.743 10617 10682 I Jsch    : Authentication succeeded (publickey).
02-11 17:38:20.746 10617 10682 E AbstractConnection: connectOnce(): exception while state == CONNECTING
02-11 17:38:20.746 10617 10682 E AbstractConnection: com.jcraft.jsch.JSchException: PortForwardingL: local port 127.0.0.1:22231 cannot be bound.
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.jcraft.jsch.PortWatcher.<init>(PortWatcher.java:158)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.jcraft.jsch.PortWatcher.addPort$2a866d1d(PortWatcher.java:110)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.jcraft.jsch.Session.setPortForwardingL(Session.java:1798)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.ubergeek42.weechat.relay.connection.SSHConnection.doConnect(SSHConnection.java:4781)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.ubergeek42.weechat.relay.connection.AbstractConnection.access$100(AbstractConnection.java:21)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.ubergeek42.weechat.relay.connection.AbstractConnection$1.run(AbstractConnection.java:52)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at java.lang.Thread.run(Thread.java:761)
02-11 17:38:20.746 10617 10682 E AbstractConnection: Caused by: java.net.BindException: Address already in use
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at java.net.PlainSocketImpl.socketBind(Native Method)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:368)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at java.net.ServerSocket.bind(ServerSocket.java:377)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at java.net.ServerSocket.<init>(ServerSocket.java:237)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    at com.jcraft.jsch.PortWatcher.<init>(PortWatcher.java:150)
02-11 17:38:20.746 10617 10682 E AbstractConnection:    ... 6 more
02-11 17:38:20.746 10617 10682 E RelayService: onException(JSchException)
```

Cheers,

**Comment by oakkitten** [comment]
please try the latest development version, we are not using a fixed local port now. f-droid version seems to be outdated a bit. your last point is weird though; perhaps you can visit us at #weechat-android on freenode?

**Comment by ardumont** [comment]
>we are not using a fixed local port now. 

[Indeed, you no longer do](https://github.com/ubergeek42/weechat-android/commit/05a4472fbf09bd3cdead33283ac0dd23a3b7a287) 

>  please try the latest development version, 

sure as soon as i have time and figured out how to do so :dagger: 

> your last point is weird though

I suppose it's the one about the weechat relay disconnection triggering the android client crash?
It does not happen all the time and i did not try to catch the `adb log` for it as it's a minor inconvenience...
The major one being to not be able to use weechat-android :D 

> perhaps you can visit us at #weechat-android on freenode?

Thanks. Will do as soon as i can but after trying out your proposed hint (if it fails).

Thanks for your time.

**Comment by ardumont** [comment]
> sure as soon as i have time and figured out how to do so :d

Well, thanks again. The [latest development version entertained in the readme](https://github.com/ubergeek42/weechat-android#latest-development-snapshot-) worked.

I guess it'd be great if [f-droid releases could keep up with yours](https://github.com/ubergeek42/weechat-android/issues/282) ;D

Cheers,

**Comment by c-MM** [comment]
Would it be possible to push an updated version to f-droid please? I also upgraded to LinageOS 14.1 and the f-droid binary no longer connects to my relay via ssh-tunnel. I have no play-store installed and can't install the development version.
Thanks a lot for this nice app.

**Comment by c-MM** [comment]
I finally found the direct apk download link (stupid me, didn't see it yesterday).
Thanks a lot, this version works fine on my LinageOS 14.1 (Nougat I think).

Thanks for the great app, I like it a lot. An f-droid update would be fine anyways. :-)

**Comment by smaslennikov** [comment]
I'd like to suggest cutting a new release (re: https://github.com/ubergeek42/weechat-android/issues/377); as I hit this issue, which seems solved in the currently nightly (works for me with the nightly, but not in 0.11 in Android App Store). I ran into this specific issue after updating to Android 6 recently.
