### ISSUE TITLE
Set relay host to localhost if connection type is ssh tunnel

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#62]
Most people going through an ssh tunnel will probably be connecting to localhost, so we should default to this most f the time.  Or at least make the suggestion when selecting ssh tunnel to set it to that.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
