### ISSUE TITLE
Switch buffers in weechat to mark things as read

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#63]
There should be an setting to switch buffers on the weechat side to mark things as read when a buffer is opened/switched to.  This would keep the hotlist from always coming back when you reconnect.

**Comment by ttsda** [comment]
This feature would also be useful when notices are set to be shown on the currently selected buffer.
When using weechat android I frequently miss notices as they show up in another buffer than the one I'm looking at.

**Comment by t3chguy** [comment]
Glowing-Bear does this without switching buffers in WeeChat (in newer versions, try http://latest.glowing-bear.org/)
The bit which handles this should be replicated in weechat-android

**Comment by ubergeek42** [comment]
The bit in glowing bear that does this is here:
https://github.com/glowing-bear/glowing-bear/blob/03ed21f203fd9491f6d72457295c4627425eaeef/js/connection.js#L269

Looks like you can `/buffer set hotlist -1` to clear notifications(along with `/input set_unread_current_buffer` to move current read marker.

**Comment by ttsda** [comment]
ah, great! thanks :)
