### ISSUE TITLE
returning to client after opening web link

### ISSUE THREAD

**Issue by R1cochet** [ubergeek42/weechat-android#67]
On occasion I get an error: "Weechat has stopped running unexpectedly" after opening a link and then pressing the back button to go back to the client.

Steps to reproduce:
Click on a web link in a buffer, the page opens in my browser just fine. Upon hitting the back button to close the browser and get back to client, the client stops running.

The client is still in task bar, but has disconnected from weechat.

This only happens on occasion.

Running android 4.0.3 on an HTC One V.

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
