### ISSUE TITLE
Custom notification options

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#7]
It'd be nice if I could select my own notification ringtone and volume to be used when notifications are enabled.  Also a setting for the notification led would be cool too.

**Comment by a3nm** [comment]
I also think that this would be interesting, especially setting a custom notification sound.

**Comment by oakkitten** [comment]
um you can set custom sound in the app settings or notification settings?

**Comment by a3nm** [comment]
Ah, nevermind, I can indeed do this from the Android settings for this category of notifications (on Android 10). Thanks for pointing this out!
