### ISSUE TITLE
query windows don't show up automatically

### ISSUE THREAD

**Issue by breunigs** [ubergeek42/weechat-android#80]
I’m using the version from the play store. Whenever I query someone (using `/query nick`) the window does not get opened nor does it show up in the buffer list. This also happens for channel joins. Only after reconnecting to the server I am able to open that buffer.

**Comment by zertap** [comment]
Yeah, please fix

**Comment by ubergeek42** [comment]
The buffer should show up in the buffer list, but it won't open automatically(And I don't think there's a reliable/non-hackish way to do that). I just tested with the latest nightly and it works as expected here.

I'm gonna close this for now, but feel free to reopen if it's actually still an issue in the latest nightly.
