### ISSUE TITLE
Use file chooser dialog

### ISSUE THREAD

**Issue by dominikh** [ubergeek42/weechat-android#82]
Some dialogs, like choosing an SSL key, should use a file chooser instead of a plain text input.

**Comment by jiggie42** [comment]
issue type is feature request
feature is present since at least stable v0.13 
recommended to close

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
