### ISSUE TITLE
allow multiple simultanious relay connections

### ISSUE THREAD

**Issue by ikke-t** [ubergeek42/weechat-android#83]
Hi,

I just started using your great app, thanks! I have irc servers both on company intranet (not open to internet) and also use the normal irc servers in internet. I would like to connect to both of the worlds via singe gui (as in xchat + irssiproxy). Here would be the userstory:

As a user I want to connect simultaneously to both weechat in intranet (via separately arranged VPN) and the internet connected weechat relay and see all the channels in one gui.

This would require to save multiple relay connections in preferences, and maintain the connections selected active. All the channels would be visible in the channel menu, and perhaps separated by relay name. Comparable to xchat.

**Comment by dominic-miglar** [comment]
+1

**Comment by oakkitten** [comment]
i don't think we have plans to support this in the nearest future
