### ISSUE TITLE
Command support

### ISSUE THREAD

**Issue by ubergeek42** [ubergeek42/weechat-android#9]
Specifically /clear would be nice to clear the droid app, without sending it to weechat.

**Comment by jiggie42** [comment]
referenced commit 08f0d5b states that it should close this ticket.  Recommended to close, unless someone can think of any additional commands?

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
