### ISSUE TITLE
[Suggestion] Prompt for password

### ISSUE THREAD

**Issue by Phyks** [ubergeek42/weechat-android#93]
Hi,

I've been using this interface for a few days now and I'm really happy with it. But I have some security concerns concerning the password handling... I don't have enough knowledge to dig into the code and see how it is handled in the back.

My concern is that I have to store my password in weechat-android configuration if I want it to work. And, if this password is not strongly protected, anyone could potentially read it (including evil apps).

I'm not a big fan of storing passwords on a pocket mobile device, and I was wondering if there could be a way to add a prompt for the password in a future version ?

Thanks

**Comment by oakkitten** [comment]
we are closing some of the issues that weren't active in a while or may be irrelevant for the latest version (1.0). if you think that this issue is still applicable, please leave a comment.
